// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/a2a/registry.yaml

/// A2a Attributes
/// Identifier of the target agent in an A2A call.
pub const A2A_AGENT_ID: &str = "a2a.agent.id";

/// Human-readable name of the A2A agent serving the request.
pub const A2A_AGENT_NAME: &str = "a2a.agent.name";

/// Endpoint URL of the A2A agent receiving or initiating the call.
pub const A2A_AGENT_URL: &str = "a2a.agent.url";

/// Number of output artifacts produced by a completed A2A task.
pub const A2A_ARTIFACT_COUNT: &str = "a2a.artifact.count";

/// Number of bids received in the A2A auction.
pub const A2A_AUCTION_BID_COUNT: &str = "a2a.auction.bid_count";

/// Clearing price of the A2A auction in normalized units.
pub const A2A_AUCTION_CLEARING_PRICE: &str = "a2a.auction.clearing_price";

/// Unique identifier of the A2A auction used for capability allocation.
pub const A2A_AUCTION_ID: &str = "a2a.auction.id";

/// Agent identifier of the auction winner.
pub const A2A_AUCTION_WINNER_ID: &str = "a2a.auction.winner_id";

/// Compression ratio achieved for the batch, range [0.0, 1.0]. 1.0 = no compression.
pub const A2A_BATCH_COMPRESSION_RATIO: &str = "a2a.batch.compression_ratio";

/// Delivery guarantee policy for the message batch.
pub const A2A_BATCH_DELIVERY_POLICY: &str = "a2a.batch.delivery_policy";

/// Values for [`A2A_BATCH_DELIVERY_POLICY`].
pub mod a2a_batch_delivery_policy {
    /// at_most_once
    pub const AT_MOST_ONCE: &str = "at_most_once";
    /// at_least_once
    pub const AT_LEAST_ONCE: &str = "at_least_once";
    /// exactly_once
    pub const EXACTLY_ONCE: &str = "exactly_once";
}

/// Unique identifier for an A2A message batch.
pub const A2A_BATCH_ID: &str = "a2a.batch.id";

/// Number of messages in the batch.
pub const A2A_BATCH_SIZE: &str = "a2a.batch.size";

/// Composite bid score computed by the auction evaluation strategy, range [0.0, 1.0].
pub const A2A_BID_SCORE: &str = "a2a.bid.score";

/// Strategy used to evaluate and rank agent bids for task allocation.
pub const A2A_BID_STRATEGY: &str = "a2a.bid.strategy";

/// Values for [`A2A_BID_STRATEGY`].
pub mod a2a_bid_strategy {
    /// lowest_cost
    pub const LOWEST_COST: &str = "lowest_cost";
    /// highest_trust
    pub const HIGHEST_TRUST: &str = "highest_trust";
    /// fastest_response
    pub const FASTEST_RESPONSE: &str = "fastest_response";
    /// balanced
    pub const BALANCED: &str = "balanced";
}

/// Identifier of the agent that won the bid evaluation.
pub const A2A_BID_WINNER_ID: &str = "a2a.bid.winner_id";

/// Confidence score for capability matching between requesting and providing agents [0.0, 1.0].
pub const A2A_CAPABILITY_MATCH_SCORE: &str = "a2a.capability.match_score";

/// Name of the capability being advertised or requested in A2A negotiation.
pub const A2A_CAPABILITY_NAME: &str = "a2a.capability.name";

/// Unique identifier for the capability negotiation session.
pub const A2A_CAPABILITY_NEGOTIATION_ID: &str = "a2a.capability.negotiation.id";

/// Outcome of the capability negotiation.
pub const A2A_CAPABILITY_NEGOTIATION_OUTCOME: &str = "a2a.capability.negotiation.outcome";

/// Values for [`A2A_CAPABILITY_NEGOTIATION_OUTCOME`].
pub mod a2a_capability_negotiation_outcome {
    /// accepted
    pub const ACCEPTED: &str = "accepted";
    /// rejected
    pub const REJECTED: &str = "rejected";
    /// deferred
    pub const DEFERRED: &str = "deferred";
    /// partial
    pub const PARTIAL: &str = "partial";
}

/// Number of rounds in the capability negotiation.
pub const A2A_CAPABILITY_NEGOTIATION_ROUNDS: &str = "a2a.capability.negotiation.rounds";

/// The capability name offered by the target agent.
pub const A2A_CAPABILITY_OFFERED: &str = "a2a.capability.offered";

/// The capability name being requested by the source agent.
pub const A2A_CAPABILITY_REQUIRED: &str = "a2a.capability.required";

/// Version of the agent capability being delegated.
pub const A2A_CAPABILITY_VERSION: &str = "a2a.capability.version";

/// Unique identifier for the contract amendment.
pub const A2A_CONTRACT_AMENDMENT_ID: &str = "a2a.contract.amendment.id";

/// Reason for the contract amendment.
pub const A2A_CONTRACT_AMENDMENT_REASON: &str = "a2a.contract.amendment.reason";

/// Values for [`A2A_CONTRACT_AMENDMENT_REASON`].
pub mod a2a_contract_amendment_reason {
    /// scope_change
    pub const SCOPE_CHANGE: &str = "scope_change";
    /// price_adjustment
    pub const PRICE_ADJUSTMENT: &str = "price_adjustment";
    /// timeline_extension
    pub const TIMELINE_EXTENSION: &str = "timeline_extension";
    /// quality_revision
    pub const QUALITY_REVISION: &str = "quality_revision";
}

/// Version number of the amended contract.
pub const A2A_CONTRACT_AMENDMENT_VERSION: &str = "a2a.contract.amendment.version";

/// Unique identifier for the A2A contract dispute.
pub const A2A_CONTRACT_DISPUTE_ID: &str = "a2a.contract.dispute.id";

/// Reason for the contract dispute.
pub const A2A_CONTRACT_DISPUTE_REASON: &str = "a2a.contract.dispute.reason";

/// Values for [`A2A_CONTRACT_DISPUTE_REASON`].
pub mod a2a_contract_dispute_reason {
    /// breach
    pub const BREACH: &str = "breach";
    /// ambiguity
    pub const AMBIGUITY: &str = "ambiguity";
    /// force_majeure
    pub const FORCE_MAJEURE: &str = "force_majeure";
}

/// Current status of the contract dispute.
pub const A2A_CONTRACT_DISPUTE_STATUS: &str = "a2a.contract.dispute.status";

/// Values for [`A2A_CONTRACT_DISPUTE_STATUS`].
pub mod a2a_contract_dispute_status {
    /// open
    pub const OPEN: &str = "open";
    /// arbitrating
    pub const ARBITRATING: &str = "arbitrating";
    /// resolved
    pub const RESOLVED: &str = "resolved";
}

/// Percentage of contract execution completed, range [0.0, 100.0].
pub const A2A_CONTRACT_EXECUTION_PROGRESS_PCT: &str = "a2a.contract.execution.progress_pct";

/// The current execution status of the A2A contract.
pub const A2A_CONTRACT_EXECUTION_STATUS: &str = "a2a.contract.execution.status";

/// Values for [`A2A_CONTRACT_EXECUTION_STATUS`].
pub mod a2a_contract_execution_status {
    /// running
    pub const RUNNING: &str = "running";
    /// completed
    pub const COMPLETED: &str = "completed";
    /// failed
    pub const FAILED: &str = "failed";
    /// disputed
    pub const DISPUTED: &str = "disputed";
}

/// Unix timestamp (milliseconds) when the contract expires.
pub const A2A_CONTRACT_EXPIRY_MS: &str = "a2a.contract.expiry_ms";

/// Unique identifier for an A2A service contract.
pub const A2A_CONTRACT_ID: &str = "a2a.contract.id";

/// SHA-256 hash of the contract terms for integrity verification.
pub const A2A_CONTRACT_TERMS_HASH: &str = "a2a.contract.terms_hash";

/// Number of times the contract terms were violated during the contract lifetime.
pub const A2A_CONTRACT_VIOLATION_COUNT: &str = "a2a.contract.violation_count";

/// Currency unit for the deal value (ISO 4217 or token unit).
pub const A2A_DEAL_CURRENCY: &str = "a2a.deal.currency";

/// Deal expiration time as Unix epoch milliseconds (Armstrong WvdA bounded lifetime).
pub const A2A_DEAL_EXPIRY_MS: &str = "a2a.deal.expiry_ms";

/// Identifier of the deal being created or operated on via A2A.
pub const A2A_DEAL_ID: &str = "a2a.deal.id";

/// Current status of the A2A deal in its lifecycle.
pub const A2A_DEAL_STATUS: &str = "a2a.deal.status";

/// Values for [`A2A_DEAL_STATUS`].
pub mod a2a_deal_status {
    /// pending
    pub const PENDING: &str = "pending";
    /// active
    pub const ACTIVE: &str = "active";
    /// completed
    pub const COMPLETED: &str = "completed";
    /// cancelled
    pub const CANCELLED: &str = "cancelled";
    /// disputed
    pub const DISPUTED: &str = "disputed";
}

/// Type of the A2A deal.
pub const A2A_DEAL_TYPE: &str = "a2a.deal.type";

/// Numeric value associated with the deal (e.g., computational cost, token budget).
pub const A2A_DEAL_VALUE: &str = "a2a.deal.value";

/// Unique identifier for the A2A dispute case.
pub const A2A_DISPUTE_ID: &str = "a2a.dispute.id";

/// The reason for the A2A dispute.
pub const A2A_DISPUTE_REASON: &str = "a2a.dispute.reason";

/// Values for [`A2A_DISPUTE_REASON`].
pub mod a2a_dispute_reason {
    /// quality
    pub const QUALITY: &str = "quality";
    /// sla_breach
    pub const SLA_BREACH: &str = "sla_breach";
    /// payment
    pub const PAYMENT: &str = "payment";
    /// fraud
    pub const FRAUD: &str = "fraud";
    /// technical
    pub const TECHNICAL: &str = "technical";
}

/// Time taken to resolve the dispute in milliseconds.
pub const A2A_DISPUTE_RESOLUTION_MS: &str = "a2a.dispute.resolution_ms";

/// Current resolution status of the A2A dispute.
pub const A2A_DISPUTE_RESOLUTION_STATUS: &str = "a2a.dispute.resolution_status";

/// Values for [`A2A_DISPUTE_RESOLUTION_STATUS`].
pub mod a2a_dispute_resolution_status {
    /// pending
    pub const PENDING: &str = "pending";
    /// resolved
    pub const RESOLVED: &str = "resolved";
    /// escalated
    pub const ESCALATED: &str = "escalated";
}

/// Duration of the A2A operation in milliseconds.
pub const A2A_DURATION_MS: &str = "a2a.duration_ms";

/// Amount held in escrow for the A2A deal.
pub const A2A_ESCROW_AMOUNT: &str = "a2a.escrow.amount";

/// Unique identifier for the A2A escrow holding deal payment.
pub const A2A_ESCROW_ID: &str = "a2a.escrow.id";

/// Condition under which the escrow funds are released.
pub const A2A_ESCROW_RELEASE_CONDITION: &str = "a2a.escrow.release_condition";

/// Values for [`A2A_ESCROW_RELEASE_CONDITION`].
pub mod a2a_escrow_release_condition {
    /// completion
    pub const COMPLETION: &str = "completion";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// manual
    pub const MANUAL: &str = "manual";
    /// dispute
    pub const DISPUTE: &str = "dispute";
}

/// Time taken to release the escrow in milliseconds.
pub const A2A_ESCROW_RELEASE_MS: &str = "a2a.escrow.release_ms";

/// The reason the A2A escrow was released.
pub const A2A_ESCROW_RELEASE_REASON: &str = "a2a.escrow.release_reason";

/// Values for [`A2A_ESCROW_RELEASE_REASON`].
pub mod a2a_escrow_release_reason {
    /// completion
    pub const COMPLETION: &str = "completion";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// dispute
    pub const DISPUTE: &str = "dispute";
    /// manual
    pub const MANUAL: &str = "manual";
}

/// The actual amount released from escrow (may differ from original if penalties applied).
pub const A2A_ESCROW_RELEASED_AMOUNT: &str = "a2a.escrow.released_amount";

/// Current status of the A2A escrow.
pub const A2A_ESCROW_STATUS: &str = "a2a.escrow.status";

/// Values for [`A2A_ESCROW_STATUS`].
pub mod a2a_escrow_status {
    /// pending
    pub const PENDING: &str = "pending";
    /// held
    pub const HELD: &str = "held";
    /// released
    pub const RELEASED: &str = "released";
    /// disputed
    pub const DISPUTED: &str = "disputed";
}

/// The JSON-RPC 2.0 method name for an A2A protocol call.
pub const A2A_JSONRPC_METHOD: &str = "a2a.jsonrpc.method";

/// Unique identifier for knowledge transfer.
pub const A2A_KNOWLEDGE_TRANSFER_ID: &str = "a2a.knowledge.transfer.id";

/// Size of knowledge payload in bytes.
pub const A2A_KNOWLEDGE_TRANSFER_SIZE_BYTES: &str = "a2a.knowledge.transfer.size_bytes";

/// Topic or domain of knowledge being transferred.
pub const A2A_KNOWLEDGE_TRANSFER_TOPIC: &str = "a2a.knowledge.transfer.topic";

/// Encoding format of the A2A message.
pub const A2A_MESSAGE_ENCODING: &str = "a2a.message.encoding";

/// Values for [`A2A_MESSAGE_ENCODING`].
pub mod a2a_message_encoding {
    /// json
    pub const JSON: &str = "json";
    /// msgpack
    pub const MSGPACK: &str = "msgpack";
    /// protobuf
    pub const PROTOBUF: &str = "protobuf";
}

/// Unique identifier for this A2A message, used for deduplication and correlation.
pub const A2A_MESSAGE_ID: &str = "a2a.message.id";

/// Priority level of the A2A message.
pub const A2A_MESSAGE_PRIORITY: &str = "a2a.message.priority";

/// Values for [`A2A_MESSAGE_PRIORITY`].
pub mod a2a_message_priority {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// Role of the sender of an A2A message.
pub const A2A_MESSAGE_ROLE: &str = "a2a.message.role";

/// Values for [`A2A_MESSAGE_ROLE`].
pub mod a2a_message_role {
    /// Message originated from a user or calling agent.
    pub const USER: &str = "user";
    /// Message originated from this agent.
    pub const AGENT: &str = "agent";
}

/// Size of the A2A message payload in bytes.
pub const A2A_MESSAGE_SIZE_BYTES: &str = "a2a.message.size_bytes";

/// Time-to-live for the A2A message in milliseconds.
pub const A2A_MESSAGE_TTL_MS: &str = "a2a.message.ttl_ms";

/// The negotiation round number in a multi-round deal negotiation.
pub const A2A_NEGOTIATION_ROUND: &str = "a2a.negotiation.round";

/// Current state in the A2A negotiation state machine.
pub const A2A_NEGOTIATION_STATE: &str = "a2a.negotiation.state";

/// Values for [`A2A_NEGOTIATION_STATE`].
pub mod a2a_negotiation_state {
    /// proposed
    pub const PROPOSED: &str = "proposed";
    /// counter
    pub const COUNTER: &str = "counter";
    /// accepted
    pub const ACCEPTED: &str = "accepted";
    /// rejected
    pub const REJECTED: &str = "rejected";
    /// expired
    pub const EXPIRED: &str = "expired";
}

/// Current status of an A2A deal negotiation.
pub const A2A_NEGOTIATION_STATUS: &str = "a2a.negotiation.status";

/// Values for [`A2A_NEGOTIATION_STATUS`].
pub mod a2a_negotiation_status {
    /// pending
    pub const PENDING: &str = "pending";
    /// in_progress
    pub const IN_PROGRESS: &str = "in_progress";
    /// accepted
    pub const ACCEPTED: &str = "accepted";
    /// rejected
    pub const REJECTED: &str = "rejected";
    /// counter_offer
    pub const COUNTER_OFFER: &str = "counter_offer";
    /// expired
    pub const EXPIRED: &str = "expired";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
}

/// Maximum time allowed for the negotiation round to complete in milliseconds.
pub const A2A_NEGOTIATION_TIMEOUT_MS: &str = "a2a.negotiation.timeout_ms";

/// The A2A operation name being invoked.
pub const A2A_OPERATION: &str = "a2a.operation";

/// Monetary or credit penalty amount applied to an agent for contract violation.
pub const A2A_PENALTY_AMOUNT: &str = "a2a.penalty.amount";

/// Currency code for the penalty/reward amount (ISO 4217).
pub const A2A_PENALTY_CURRENCY: &str = "a2a.penalty.currency";

/// Reason for applying a penalty to an agent in the A2A marketplace.
pub const A2A_PENALTY_REASON: &str = "a2a.penalty.reason";

/// Values for [`A2A_PENALTY_REASON`].
pub mod a2a_penalty_reason {
    /// sla_violation
    pub const SLA_VIOLATION: &str = "sla_violation";
    /// quality_failure
    pub const QUALITY_FAILURE: &str = "quality_failure";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// fraud
    pub const FRAUD: &str = "fraud";
}

/// Whether the A2A protocol version in use is deprecated.
pub const A2A_PROTOCOL_DEPRECATED: &str = "a2a.protocol.deprecated";

/// Minimum A2A protocol version supported by the endpoint.
pub const A2A_PROTOCOL_MIN_VERSION: &str = "a2a.protocol.min_version";

/// Time taken to negotiate the A2A protocol version in milliseconds.
pub const A2A_PROTOCOL_NEGOTIATION_MS: &str = "a2a.protocol.negotiation_ms";

/// The A2A protocol version in use for this interaction.
pub const A2A_PROTOCOL_VERSION: &str = "a2a.protocol.version";

/// Current depth of the A2A request queue for the target agent.
pub const A2A_QUEUE_DEPTH: &str = "a2a.queue.depth";

/// Categorical trust level derived from the reputation score.
pub const A2A_REPUTATION_CATEGORY: &str = "a2a.reputation.category";

/// Values for [`A2A_REPUTATION_CATEGORY`].
pub mod a2a_reputation_category {
    /// trusted
    pub const TRUSTED: &str = "trusted";
    /// neutral
    pub const NEUTRAL: &str = "neutral";
    /// probation
    pub const PROBATION: &str = "probation";
    /// banned
    pub const BANNED: &str = "banned";
}

/// The absolute change in reputation score from this decay event (always negative or zero).
pub const A2A_REPUTATION_DECAY_DELTA: &str = "a2a.reputation.decay.delta";

/// The rate at which reputation decays per decay trigger event, range [0.0, 1.0].
pub const A2A_REPUTATION_DECAY_RATE: &str = "a2a.reputation.decay.rate";

/// The trigger that caused this reputation decay event.
pub const A2A_REPUTATION_DECAY_TRIGGER: &str = "a2a.reputation.decay.trigger";

/// Values for [`A2A_REPUTATION_DECAY_TRIGGER`].
pub mod a2a_reputation_decay_trigger {
    /// time
    pub const TIME: &str = "time";
    /// interaction
    pub const INTERACTION: &str = "interaction";
    /// violation
    pub const VIOLATION: &str = "violation";
}

/// Time-decay factor applied to older interactions in reputation calculation.
pub const A2A_REPUTATION_DECAY_FACTOR: &str = "a2a.reputation.decay_factor";

/// Number of past interactions used to compute the reputation score.
pub const A2A_REPUTATION_HISTORY_LENGTH: &str = "a2a.reputation.history_length";

/// Total number of interactions used to compute the reputation score.
pub const A2A_REPUTATION_INTERACTION_COUNT: &str = "a2a.reputation.interaction_count";

/// Agent reputation score in range [0.0, 1.0] based on historical interactions.
pub const A2A_REPUTATION_SCORE: &str = "a2a.reputation.score";

/// Number of retry attempts made for this A2A call before success or final failure.
pub const A2A_RETRY_COUNT: &str = "a2a.retry.count";

/// Monetary or credit reward amount granted to an agent for exceeding contract terms.
pub const A2A_REWARD_AMOUNT: &str = "a2a.reward.amount";

/// The strategy used to route A2A requests to available agents.
pub const A2A_ROUTING_STRATEGY: &str = "a2a.routing.strategy";

/// Values for [`A2A_ROUTING_STRATEGY`].
pub mod a2a_routing_strategy {
    /// best_match
    pub const BEST_MATCH: &str = "best_match";
    /// round_robin
    pub const ROUND_ROBIN: &str = "round_robin";
    /// load_balanced
    pub const LOAD_BALANCED: &str = "load_balanced";
    /// priority_queue
    pub const PRIORITY_QUEUE: &str = "priority_queue";
}

/// Identifier of the A2A skill being invoked, matching the AgentCard skill list.
pub const A2A_SKILL_ID: &str = "a2a.skill.id";

/// Whether the A2A operation violated its SLA deadline.
pub const A2A_SLA_BREACH: &str = "a2a.sla.breach";

/// SLA deadline in milliseconds from request initiation. Exceeding this is an SLA breach.
pub const A2A_SLA_DEADLINE_MS: &str = "a2a.sla.deadline_ms";

/// Actual observed latency for this A2A operation in milliseconds.
pub const A2A_SLA_LATENCY_MS: &str = "a2a.sla.latency_ms";

/// Number of SLO breaches in evaluation window.
pub const A2A_SLO_BREACH_COUNT: &str = "a2a.slo.breach_count";

/// SLO compliance rate [0.0, 1.0] over evaluation window.
pub const A2A_SLO_COMPLIANCE_RATE: &str = "a2a.slo.compliance_rate";

/// Identifier for the service level objective being evaluated.
pub const A2A_SLO_ID: &str = "a2a.slo.id";

/// Target latency in milliseconds for SLO compliance.
pub const A2A_SLO_TARGET_LATENCY_MS: &str = "a2a.slo.target_latency_ms";

/// Service initiating the A2A call (sender).
pub const A2A_SOURCE_SERVICE: &str = "a2a.source.service";

/// Service receiving the A2A call (receiver).
pub const A2A_TARGET_SERVICE: &str = "a2a.target.service";

/// Unique identifier for a delegated task in A2A task delegation.
pub const A2A_TASK_ID: &str = "a2a.task.id";

/// Priority level of a delegated A2A task.
pub const A2A_TASK_PRIORITY: &str = "a2a.task.priority";

/// Values for [`A2A_TASK_PRIORITY`].
pub mod a2a_task_priority {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// Lifecycle state of an A2A task.
pub const A2A_TASK_STATE: &str = "a2a.task.state";

/// Values for [`A2A_TASK_STATE`].
pub mod a2a_task_state {
    /// Task has been received but work has not started.
    pub const SUBMITTED: &str = "submitted";
    /// Task is actively being processed.
    pub const WORKING: &str = "working";
    /// Task finished successfully.
    pub const COMPLETED: &str = "completed";
    /// Task terminated with an error.
    pub const FAILED: &str = "failed";
    /// Task was explicitly canceled.
    pub const CANCELED: &str = "canceled";
}

/// Transport protocol used for the A2A exchange.
pub const A2A_TRANSPORT: &str = "a2a.transport";

/// Values for [`A2A_TRANSPORT`].
pub mod a2a_transport {
    /// Standard HTTP JSON-RPC transport.
    pub const HTTP: &str = "http";
    /// WebSocket streaming transport.
    pub const WEBSOCKET: &str = "websocket";
}

/// Minimum fraction of peers required to reach trust consensus, range [0.0, 1.0].
pub const A2A_TRUST_CONSENSUS_THRESHOLD: &str = "a2a.trust.consensus_threshold";

/// Exponential decay factor applied to historical trust scores, range (0.0, 1.0].
pub const A2A_TRUST_DECAY_FACTOR: &str = "a2a.trust.decay_factor";

/// Current trust epoch — increments on membership change or key rotation.
pub const A2A_TRUST_EPOCH: &str = "a2a.trust.epoch";

/// Identifier of the federated trust ring this agent belongs to.
pub const A2A_TRUST_FEDERATION_ID: &str = "a2a.trust.federation_id";

/// Number of peer agents in the trust federation.
pub const A2A_TRUST_PEER_COUNT: &str = "a2a.trust.peer_count";

/// Trust score assigned to an agent interaction, range [0.0, 1.0]. Higher is more trusted.
pub const A2A_TRUST_SCORE: &str = "a2a.trust.score";

/// Unix timestamp (milliseconds) when the trust score was last updated.
pub const A2A_TRUST_UPDATED_AT_MS: &str = "a2a.trust.updated_at_ms";
