// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/agent/registry.yaml

/// Agent Attributes
/// Remaining time budget for the agent operation in milliseconds.
pub const AGENT_BUDGET_REMAINING_MS: &str = "agent.budget.remaining_ms";

/// The priority tier of the agent operation (affects budget allocation).
pub const AGENT_BUDGET_TIER: &str = "agent.budget.tier";

/// Values for [`AGENT_BUDGET_TIER`].
pub mod agent_budget_tier {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// Unique identifier for the agent capability catalog.
pub const AGENT_CAPABILITY_CATALOG_ID: &str = "agent.capability.catalog_id";

/// Version string of the agent capability catalog.
pub const AGENT_CAPABILITY_CATALOG_VERSION: &str = "agent.capability.catalog_version";

/// Number of capabilities registered by this agent.
pub const AGENT_CAPABILITY_COUNT: &str = "agent.capability.count";

/// Scope of the agent capability catalog (local node, cluster, or federated).
pub const AGENT_CAPABILITY_SCOPE: &str = "agent.capability.scope";

/// Values for [`AGENT_CAPABILITY_SCOPE`].
pub mod agent_capability_scope {
    /// local
    pub const LOCAL: &str = "local";
    /// cluster
    pub const CLUSTER: &str = "cluster";
    /// federated
    pub const FEDERATED: &str = "federated";
}

/// Latency in milliseconds for agent coordination messages (round-trip).
pub const AGENT_COORDINATION_LATENCY_MS: &str = "agent.coordination.latency_ms";

/// Confidence score for the agent's decision, range [0.0, 1.0].
pub const AGENT_DECISION_CONFIDENCE: &str = "agent.decision.confidence";

/// The type of decision made by the agent.
pub const AGENT_DECISION_TYPE: &str = "agent.decision.type";

/// Values for [`AGENT_DECISION_TYPE`].
pub mod agent_decision_type {
    /// action
    pub const ACTION: &str = "action";
    /// delegation
    pub const DELEGATION: &str = "delegation";
    /// escalation
    pub const ESCALATION: &str = "escalation";
    /// defer
    pub const DEFER: &str = "defer";
    /// reject
    pub const REJECT: &str = "reject";
}

/// Duration of the critical path through the execution graph in milliseconds.
pub const AGENT_EXECUTION_CRITICAL_PATH_MS: &str = "agent.execution.critical_path_ms";

/// Number of edges (dependencies) in the execution graph.
pub const AGENT_EXECUTION_EDGE_COUNT: &str = "agent.execution.edge_count";

/// Unique identifier for the agent execution graph (DAG of agent steps).
pub const AGENT_EXECUTION_GRAPH_ID: &str = "agent.execution.graph_id";

/// Number of nodes (steps) in the execution graph.
pub const AGENT_EXECUTION_NODE_COUNT: &str = "agent.execution.node_count";

/// Reason the agent handoff was initiated.
pub const AGENT_HANDOFF_REASON: &str = "agent.handoff.reason";

/// Values for [`AGENT_HANDOFF_REASON`].
pub mod agent_handoff_reason {
    /// capability
    pub const CAPABILITY: &str = "capability";
    /// load
    pub const LOAD: &str = "load";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// priority
    pub const PRIORITY: &str = "priority";
}

/// Time taken to transfer state to the receiving agent in milliseconds.
pub const AGENT_HANDOFF_STATE_TRANSFER_MS: &str = "agent.handoff.state_transfer_ms";

/// Identifier of the agent receiving the handoff.
pub const AGENT_HANDOFF_TARGET_ID: &str = "agent.handoff.target_id";

/// Unique identifier of the agent.
pub const AGENT_ID: &str = "agent.id";

/// The LLM model used for agent inference.
pub const AGENT_LLM_MODEL: &str = "agent.llm_model";

/// Current iteration of the agent's main processing loop.
pub const AGENT_LOOP_ITERATION: &str = "agent.loop.iteration";

/// Number of peer agents sharing the same federated memory pool.
pub const AGENT_MEMORY_FEDERATION_PEER_COUNT: &str = "agent.memory.federation.peer_count";

/// Monotonically increasing version counter for federated memory consistency.
pub const AGENT_MEMORY_FEDERATION_VERSION: &str = "agent.memory.federation.version";

/// Identifier of the federated memory pool shared across multiple agents.
pub const AGENT_MEMORY_FEDERATION_ID: &str = "agent.memory.federation_id";

/// Current size of the agent's working memory in tokens or items.
pub const AGENT_MEMORY_SIZE: &str = "agent.memory.size";

/// Latency in milliseconds for synchronizing state with federated memory peers.
pub const AGENT_MEMORY_SYNC_LATENCY_MS: &str = "agent.memory.sync.latency_ms";

/// Type of memory the agent is accessing or updating.
pub const AGENT_MEMORY_TYPE: &str = "agent.memory.type";

/// Values for [`AGENT_MEMORY_TYPE`].
pub mod agent_memory_type {
    /// short_term
    pub const SHORT_TERM: &str = "short_term";
    /// long_term
    pub const LONG_TERM: &str = "long_term";
    /// episodic
    pub const EPISODIC: &str = "episodic";
    /// semantic
    pub const SEMANTIC: &str = "semantic";
}

/// Number of messages exchanged by this agent during the current operation.
pub const AGENT_MESSAGE_COUNT: &str = "agent.message.count";

/// Node identifier for the agent (hostname, cluster node, etc).
pub const AGENT_NODE: &str = "agent.node";

/// Identifier of the orchestrating agent supervising this agent (Armstrong supervision tree).
pub const AGENT_ORCHESTRATOR_ID: &str = "agent.orchestrator.id";

/// Outcome of the agent decision.
pub const AGENT_OUTCOME: &str = "agent.outcome";

/// Values for [`AGENT_OUTCOME`].
pub mod agent_outcome {
    /// success
    pub const SUCCESS: &str = "success";
    /// failure
    pub const FAILURE: &str = "failure";
    /// escalated
    pub const ESCALATED: &str = "escalated";
}

/// Identifier of the agent pipeline being executed.
pub const AGENT_PIPELINE_ID: &str = "agent.pipeline.id";

/// Retry policy for the agent pipeline stage.
pub const AGENT_PIPELINE_RETRY_POLICY: &str = "agent.pipeline.retry_policy";

/// Values for [`AGENT_PIPELINE_RETRY_POLICY`].
pub mod agent_pipeline_retry_policy {
    /// none
    pub const NONE: &str = "none";
    /// fixed_delay
    pub const FIXED_DELAY: &str = "fixed_delay";
    /// exponential_backoff
    pub const EXPONENTIAL_BACKOFF: &str = "exponential_backoff";
    /// circuit_breaker
    pub const CIRCUIT_BREAKER: &str = "circuit_breaker";
}

/// Current stage name in the agent pipeline.
pub const AGENT_PIPELINE_STAGE: &str = "agent.pipeline.stage";

/// Total number of stages in the pipeline.
pub const AGENT_PIPELINE_STAGE_COUNT: &str = "agent.pipeline.stage_count";

/// Change in confidence score from start to end of the reasoning trace, range [-1.0, 1.0].
pub const AGENT_REASONING_CONFIDENCE_DELTA: &str = "agent.reasoning.confidence_delta";

/// Duration in milliseconds of the complete reasoning trace.
pub const AGENT_REASONING_DURATION_MS: &str = "agent.reasoning.duration_ms";

/// Number of reasoning steps in the agent's chain-of-thought trace.
pub const AGENT_REASONING_STEP_COUNT: &str = "agent.reasoning.step_count";

/// Unique identifier for an agent reasoning trace (chain-of-thought record).
pub const AGENT_REASONING_TRACE_ID: &str = "agent.reasoning.trace_id";

/// Number of child agents spawned by this agent in the current session.
pub const AGENT_SPAWN_COUNT: &str = "agent.spawn.count";

/// Time in milliseconds from spawn request to agent ready state.
pub const AGENT_SPAWN_LATENCY_MS: &str = "agent.spawn.latency_ms";

/// Identifier of the parent agent that initiated the spawn operation.
pub const AGENT_SPAWN_PARENT_ID: &str = "agent.spawn.parent_id";

/// Strategy used to create the spawned agent.
pub const AGENT_SPAWN_STRATEGY: &str = "agent.spawn.strategy";

/// Values for [`AGENT_SPAWN_STRATEGY`].
pub mod agent_spawn_strategy {
    /// on_demand
    pub const ON_DEMAND: &str = "on_demand";
    /// pre_warmed
    pub const PRE_WARMED: &str = "pre_warmed";
    /// pooled
    pub const POOLED: &str = "pooled";
}

/// The current execution status of the agent task.
pub const AGENT_TASK_STATUS: &str = "agent.task.status";

/// Values for [`AGENT_TASK_STATUS`].
pub mod agent_task_status {
    /// pending
    pub const PENDING: &str = "pending";
    /// running
    pub const RUNNING: &str = "running";
    /// completed
    pub const COMPLETED: &str = "completed";
    /// failed
    pub const FAILED: &str = "failed";
    /// cancelled
    pub const CANCELLED: &str = "cancelled";
}

/// Timestamp when the agent decision was made (ISO 8601 format).
pub const AGENT_TIMESTAMP: &str = "agent.timestamp";

/// Total token count for the agent inference.
pub const AGENT_TOKEN_COUNT: &str = "agent.token_count";

/// The coordination topology of agents in this multi-agent system.
pub const AGENT_TOPOLOGY_TYPE: &str = "agent.topology.type";

/// Values for [`AGENT_TOPOLOGY_TYPE`].
pub mod agent_topology_type {
    /// pipeline
    pub const PIPELINE: &str = "pipeline";
    /// fan_out
    pub const FAN_OUT: &str = "fan_out";
    /// hierarchical
    pub const HIERARCHICAL: &str = "hierarchical";
    /// mesh
    pub const MESH: &str = "mesh";
    /// star
    pub const STAR: &str = "star";
}

/// Version of the agent code/model being executed.
pub const AGENT_VERSION: &str = "agent.version";

/// Unique identifier for the workflow checkpoint.
pub const AGENT_WORKFLOW_CHECKPOINT_ID: &str = "agent.workflow.checkpoint_id";

/// Step number at which the checkpoint was captured.
pub const AGENT_WORKFLOW_CHECKPOINT_STEP: &str = "agent.workflow.checkpoint_step";

/// Number of times this workflow has been resumed from a checkpoint.
pub const AGENT_WORKFLOW_RESUME_COUNT: &str = "agent.workflow.resume_count";
