// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/board/registry.yaml

/// Board Attributes
/// Number of detected bottleneck activities
pub const BOARD_KPI_BOTTLENECK_COUNT: &str = "board.kpi_bottleneck_count";

/// Conformance score [0.0-1.0]: 0.0 (no conformance) to 1.0 (perfect)
pub const BOARD_KPI_CONFORMANCE_SCORE: &str = "board.kpi_conformance_score";

/// Average case cycle time in milliseconds
pub const BOARD_KPI_CYCLE_TIME_AVG_MS: &str = "board.kpi_cycle_time_avg_ms";

/// Total number of events processed (capped at 10,000)
pub const BOARD_KPI_EVENTS_PROCESSED: &str = "board.kpi_events_processed";

/// Whether the event log was truncated to respect the 10,000 event batch limit
pub const BOARD_KPI_TRUNCATED: &str = "board.kpi_truncated";

/// Number of unique process variants
pub const BOARD_KPI_VARIANT_COUNT: &str = "board.kpi_variant_count";

/// Error type if KPI computation failed
pub const BOARD_KPI_ERROR: &str = "board.kpi_error";

/// Conway score [0.0-1.0]: boundary handoff time / total cycle time
pub const BOARD_CONWAY_SCORE: &str = "board.conway_score";

/// Number of departments with Conway violations detected
pub const BOARD_CONWAY_VIOLATION_COUNT: &str = "board.conway_violation_count";

/// Type of board escalation emitted
pub const BOARD_ESCALATION_TYPE: &str = "board.escalation_type";

/// Values for [`BOARD_ESCALATION_TYPE`].
pub mod board_escalation_type {
    /// Structural org boundary bottleneck requiring board decision
    pub const CONWAY_VIOLATION: &str = "conway_violation";
}

/// Number of board escalation events emitted this check
pub const BOARD_ESCALATIONS_EMITTED: &str = "board.escalations_emitted";

/// Whether the briefing includes the STRUCTURAL DECISIONS REQUIRED section
pub const BOARD_HAS_STRUCTURAL_ISSUES: &str = "board.has_structural_issues";

/// Number of conformance_violation healing events emitted
pub const BOARD_HEALINGS_TRIGGERED: &str = "board.healings_triggered";

/// ISO 8601 timestamp when Canopy received the intelligence from BusinessOS.
pub const BOARD_INTELLIGENCE_RECEIVED_AT: &str = "board.intelligence_received_at";

/// Origin system that produced the board intelligence payload.
pub const BOARD_INTELLIGENCE_SOURCE: &str = "board.intelligence_source";

/// Whether a Conway violation was detected (boundary time > 40% of cycle time)
pub const BOARD_IS_VIOLATION: &str = "board.is_violation";

/// Number of active cases synced to Oxigraph in this L0 sync run.
pub const BOARD_L0_SYNC_CASE_COUNT: &str = "board.l0_sync.case_count";

/// Number of handoff events synced to Oxigraph in this L0 sync run.
pub const BOARD_L0_SYNC_HANDOFF_COUNT: &str = "board.l0_sync.handoff_count";

/// Number of departments with Little's Law queue violations
pub const BOARD_LITTLES_LAW_ALERT_COUNT: &str = "board.littles_law_alert_count";

/// Department or process identifier being checked
pub const BOARD_PROCESS_ID: &str = "board.process_id";

/// Number of sections in the board briefing (5 standard + 1 if Conway violations)
pub const BOARD_SECTION_COUNT: &str = "board.section_count";

/// Count of Conway violations requiring board decision
pub const BOARD_STRUCTURAL_ISSUE_COUNT: &str = "board.structural_issue_count";
