// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/bos/registry.yaml

/// Bos Attributes
/// Name of the BusinessOS AI service or agent handling the operation.
pub const BOS_AGENT_SERVICE: &str = "bos.agent.service";

/// Identity of the actor performing the audited operation.
pub const BOS_AUDIT_ACTOR_ID: &str = "bos.audit.actor_id";

/// Type of audit event recorded.
pub const BOS_AUDIT_EVENT_TYPE: &str = "bos.audit.event_type";

/// Values for [`BOS_AUDIT_EVENT_TYPE`].
pub mod bos_audit_event_type {
    /// data_access
    pub const DATA_ACCESS: &str = "data_access";
    /// config_change
    pub const CONFIG_CHANGE: &str = "config_change";
    /// permission_grant
    pub const PERMISSION_GRANT: &str = "permission_grant";
    /// compliance_check
    pub const COMPLIANCE_CHECK: &str = "compliance_check";
    /// gap_detection
    pub const GAP_DETECTION: &str = "gap_detection";
}

/// Unique identifier for a compliance audit trail entry.
pub const BOS_AUDIT_TRAIL_ID: &str = "bos.audit.trail.id";

/// Control ID within the compliance framework.
pub const BOS_COMPLIANCE_CONTROL_ID: &str = "bos.compliance.control_id";

/// Compliance framework being evaluated or enforced.
pub const BOS_COMPLIANCE_FRAMEWORK: &str = "bos.compliance.framework";

/// Values for [`BOS_COMPLIANCE_FRAMEWORK`].
pub mod bos_compliance_framework {
    /// SOC2
    pub const SOC2: &str = "SOC2";
    /// HIPAA
    pub const HIPAA: &str = "HIPAA";
    /// GDPR
    pub const GDPR: &str = "GDPR";
    /// SOX
    pub const SOX: &str = "SOX";
    /// CUSTOM
    pub const CUSTOM: &str = "CUSTOM";
}

/// Whether the compliance check passed (true) or failed (false).
pub const BOS_COMPLIANCE_PASSED: &str = "bos.compliance.passed";

/// Identifier of the specific compliance rule being checked.
pub const BOS_COMPLIANCE_RULE_ID: &str = "bos.compliance.rule_id";

/// Severity level of a compliance rule violation.
pub const BOS_COMPLIANCE_SEVERITY: &str = "bos.compliance.severity";

/// Values for [`BOS_COMPLIANCE_SEVERITY`].
pub mod bos_compliance_severity {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// medium
    pub const MEDIUM: &str = "medium";
    /// low
    pub const LOW: &str = "low";
}

/// Unique identifier for a recorded decision in BusinessOS.
pub const BOS_DECISION_ID: &str = "bos.decision.id";

/// The outcome of a business decision.
pub const BOS_DECISION_OUTCOME: &str = "bos.decision.outcome";

/// Values for [`BOS_DECISION_OUTCOME`].
pub mod bos_decision_outcome {
    /// approved
    pub const APPROVED: &str = "approved";
    /// rejected
    pub const REJECTED: &str = "rejected";
    /// deferred
    pub const DEFERRED: &str = "deferred";
    /// escalated
    pub const ESCALATED: &str = "escalated";
}

/// Classification of the decision recorded.
pub const BOS_DECISION_TYPE: &str = "bos.decision.type";

/// Values for [`BOS_DECISION_TYPE`].
pub mod bos_decision_type {
    /// architectural
    pub const ARCHITECTURAL: &str = "architectural";
    /// operational
    pub const OPERATIONAL: &str = "operational";
    /// strategic
    pub const STRATEGIC: &str = "strategic";
    /// compliance
    pub const COMPLIANCE: &str = "compliance";
}

/// Identifier for a detected compliance gap.
pub const BOS_GAP_ID: &str = "bos.gap.id";

/// Target days to remediate the detected gap.
pub const BOS_GAP_REMEDIATION_DAYS: &str = "bos.gap.remediation_days";

/// Severity of the detected compliance gap.
pub const BOS_GAP_SEVERITY: &str = "bos.gap.severity";

/// Values for [`BOS_GAP_SEVERITY`].
pub mod bos_gap_severity {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// medium
    pub const MEDIUM: &str = "medium";
    /// low
    pub const LOW: &str = "low";
}

/// The current status of a compliance gap.
pub const BOS_GAP_STATUS: &str = "bos.gap.status";

/// Values for [`BOS_GAP_STATUS`].
pub mod bos_gap_status {
    /// open
    pub const OPEN: &str = "open";
    /// in_remediation
    pub const IN_REMEDIATION: &str = "in_remediation";
    /// resolved
    pub const RESOLVED: &str = "resolved";
    /// accepted_risk
    pub const ACCEPTED_RISK: &str = "accepted_risk";
}

/// Process discovery algorithm requested by BOS CLI.
pub const BOS_GATEWAY_ALGORITHM: &str = "bos.gateway.algorithm";

/// Values for [`BOS_GATEWAY_ALGORITHM`].
pub mod bos_gateway_algorithm {
    /// inductive_miner
    pub const INDUCTIVE_MINER: &str = "inductive_miner";
    /// alpha_miner
    pub const ALPHA_MINER: &str = "alpha_miner";
    /// heuristics_miner
    pub const HEURISTICS_MINER: &str = "heuristics_miner";
}

/// Conformance fitness score [0.0, 1.0] from pm4py-rust.
pub const BOS_GATEWAY_FITNESS: &str = "bos.gateway.fitness";

/// Wall-clock latency in milliseconds for the gateway round-trip.
pub const BOS_GATEWAY_LATENCY_MS: &str = "bos.gateway.latency_ms";

/// Identifier of the process model returned by pm4py-rust.
pub const BOS_GATEWAY_MODEL_ID: &str = "bos.gateway.model_id";

/// Number of process traces in the event log.
pub const BOS_GATEWAY_NUM_TRACES: &str = "bos.gateway.num_traces";

/// Version of the compliance policy rule set applied.
pub const BOS_POLICY_VERSION: &str = "bos.policy.version";

/// Unique identifier for a BusinessOS workspace.
pub const BOS_WORKSPACE_ID: &str = "bos.workspace.id";

/// Human-readable name of the BusinessOS workspace.
pub const BOS_WORKSPACE_NAME: &str = "bos.workspace.name";
