// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/business_os/registry.yaml

/// Business Os Attributes
/// Type of audit event in the BusinessOS audit trail.
pub const BUSINESS_OS_AUDIT_EVENT_TYPE: &str = "business_os.audit.event_type";

/// Values for [`BUSINESS_OS_AUDIT_EVENT_TYPE`].
pub mod business_os_audit_event_type {
    /// create
    pub const CREATE: &str = "create";
    /// update
    pub const UPDATE: &str = "update";
    /// delete
    pub const DELETE: &str = "delete";
    /// access
    pub const ACCESS: &str = "access";
    /// export
    pub const EXPORT: &str = "export";
}

/// The compliance framework being evaluated or enforced.
pub const BUSINESS_OS_COMPLIANCE_FRAMEWORK: &str = "business_os.compliance.framework";

/// Values for [`BUSINESS_OS_COMPLIANCE_FRAMEWORK`].
pub mod business_os_compliance_framework {
    /// SOC2
    pub const SOC2: &str = "SOC2";
    /// HIPAA
    pub const HIPAA: &str = "HIPAA";
    /// GDPR
    pub const GDPR: &str = "GDPR";
    /// SOX
    pub const SOX: &str = "SOX";
}

/// The integration pattern used to connect an external service.
pub const BUSINESS_OS_INTEGRATION_TYPE: &str = "business_os.integration.type";

/// Values for [`BUSINESS_OS_INTEGRATION_TYPE`].
pub mod business_os_integration_type {
    /// webhook
    pub const WEBHOOK: &str = "webhook";
    /// api_pull
    pub const API_PULL: &str = "api_pull";
    /// file_sync
    pub const FILE_SYNC: &str = "file_sync";
    /// realtime_stream
    pub const REALTIME_STREAM: &str = "realtime_stream";
}
