// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/canopy/registry.yaml

/// Canopy Attributes
/// Action performed by the Canopy adapter.
pub const CANOPY_ADAPTER_ACTION: &str = "canopy.adapter.action";

/// Cumulative error count from the adapter since last reset.
pub const CANOPY_ADAPTER_ERROR_COUNT: &str = "canopy.adapter.error_count";

/// Name of the Canopy adapter being invoked.
pub const CANOPY_ADAPTER_NAME: &str = "canopy.adapter.name";

/// The type of Canopy adapter handling the request.
pub const CANOPY_ADAPTER_TYPE: &str = "canopy.adapter.type";

/// Values for [`CANOPY_ADAPTER_TYPE`].
pub mod canopy_adapter_type {
    /// osa
    pub const OSA: &str = "osa";
    /// mcp
    pub const MCP: &str = "mcp";
    /// business_os
    pub const BUSINESS_OS: &str = "business_os";
    /// webhook
    pub const WEBHOOK: &str = "webhook";
}

/// Time budget allocated for the Canopy operation in milliseconds.
pub const CANOPY_BUDGET_MS: &str = "canopy.budget.ms";

/// Source agent or service that originated the command.
pub const CANOPY_COMMAND_SOURCE: &str = "canopy.command.source";

/// Target agent or service for the command.
pub const CANOPY_COMMAND_TARGET: &str = "canopy.command.target";

/// Type of command being dispatched through Canopy.
pub const CANOPY_COMMAND_TYPE: &str = "canopy.command.type";

/// Values for [`CANOPY_COMMAND_TYPE`].
pub mod canopy_command_type {
    /// agent_dispatch
    pub const AGENT_DISPATCH: &str = "agent_dispatch";
    /// workflow_trigger
    pub const WORKFLOW_TRIGGER: &str = "workflow_trigger";
    /// data_query
    pub const DATA_QUERY: &str = "data_query";
    /// heartbeat_check
    pub const HEARTBEAT_CHECK: &str = "heartbeat_check";
    /// config_reload
    pub const CONFIG_RELOAD: &str = "config_reload";
    /// execute
    pub const EXECUTE: &str = "execute";
    /// query
    pub const QUERY: &str = "query";
    /// route
    pub const ROUTE: &str = "route";
    /// broadcast
    pub const BROADCAST: &str = "broadcast";
    /// sync
    pub const SYNC: &str = "sync";
    /// delegate
    pub const DELEGATE: &str = "delegate";
}

/// Number of state conflicts detected during workspace synchronization.
pub const CANOPY_CONFLICT_COUNT: &str = "canopy.conflict.count";

/// Round-trip latency of the heartbeat probe in milliseconds (Armstrong WvdA bounded).
pub const CANOPY_HEARTBEAT_LATENCY_MS: &str = "canopy.heartbeat.latency_ms";

/// Consecutive missed heartbeats before this probe was sent (liveness indicator).
pub const CANOPY_HEARTBEAT_MISSED_COUNT: &str = "canopy.heartbeat.missed_count";

/// Monotonically increasing sequence number of this heartbeat probe for ordering.
pub const CANOPY_HEARTBEAT_SEQUENCE_NUM: &str = "canopy.heartbeat.sequence_num";

/// Health status reported by the heartbeat.
pub const CANOPY_HEARTBEAT_STATUS: &str = "canopy.heartbeat.status";

/// Values for [`CANOPY_HEARTBEAT_STATUS`].
pub mod canopy_heartbeat_status {
    /// healthy
    pub const HEALTHY: &str = "healthy";
    /// degraded
    pub const DEGRADED: &str = "degraded";
    /// critical
    pub const CRITICAL: &str = "critical";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
}

/// Priority tier of the heartbeat dispatch.
pub const CANOPY_HEARTBEAT_TIER: &str = "canopy.heartbeat.tier";

/// Values for [`CANOPY_HEARTBEAT_TIER`].
pub mod canopy_heartbeat_tier {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// The type of workspace operation being performed.
pub const CANOPY_OPERATION_TYPE: &str = "canopy.operation.type";

/// Values for [`CANOPY_OPERATION_TYPE`].
pub mod canopy_operation_type {
    /// read
    pub const READ: &str = "read";
    /// write
    pub const WRITE: &str = "write";
    /// subscribe
    pub const SUBSCRIBE: &str = "subscribe";
    /// publish
    pub const PUBLISH: &str = "publish";
}

/// Number of peer nodes participating in workspace synchronization.
pub const CANOPY_PEER_COUNT: &str = "canopy.peer.count";

/// The version of the Canopy workspace protocol in use.
pub const CANOPY_PROTOCOL_VERSION: &str = "canopy.protocol.version";

/// Time in milliseconds for the Canopy workspace to respond to a command.
pub const CANOPY_RESPONSE_TIME_MS: &str = "canopy.response_time_ms";

/// Unique identifier for the Canopy workspace session.
pub const CANOPY_SESSION_ID: &str = "canopy.session.id";

/// Signal Theory mode of the workspace signal (M in S=(M,G,T,F,W)).
pub const CANOPY_SIGNAL_MODE: &str = "canopy.signal.mode";

/// Compression ratio achieved on the snapshot (uncompressed/compressed), >= 1.0.
pub const CANOPY_SNAPSHOT_COMPRESSION_RATIO: &str = "canopy.snapshot.compression_ratio";

/// Unique identifier of the canopy workspace snapshot.
pub const CANOPY_SNAPSHOT_ID: &str = "canopy.snapshot.id";

/// Size of the serialized snapshot in bytes.
pub const CANOPY_SNAPSHOT_SIZE_BYTES: &str = "canopy.snapshot.size_bytes";

/// The synchronization strategy used for workspace state reconciliation.
pub const CANOPY_SYNC_STRATEGY: &str = "canopy.sync.strategy";

/// Values for [`CANOPY_SYNC_STRATEGY`].
pub mod canopy_sync_strategy {
    /// immediate
    pub const IMMEDIATE: &str = "immediate";
    /// batched
    pub const BATCHED: &str = "batched";
    /// eventual
    pub const EVENTUAL: &str = "eventual";
    /// conflict_free
    pub const CONFLICT_FREE: &str = "conflict_free";
}

/// Unique identifier for the Canopy workspace session.
pub const CANOPY_WORKSPACE_ID: &str = "canopy.workspace.id";
