// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/chatmangpt/registry.yaml

/// Chatmangpt Attributes
/// Unique identifier of the agent processing the operation.
pub const CHATMANGPT_AGENT_ID: &str = "chatmangpt.agent.id";

/// Whether the operation exceeded its time budget.
pub const CHATMANGPT_BUDGET_EXCEEDED: &str = "chatmangpt.budget.exceeded";

/// Time budget allocated for the operation in milliseconds.
pub const CHATMANGPT_BUDGET_TIME_MS: &str = "chatmangpt.budget.time_ms";

/// Deployment environment for this ChatmanGPT instance.
pub const CHATMANGPT_DEPLOYMENT: &str = "chatmangpt.deployment";

/// Values for [`CHATMANGPT_DEPLOYMENT`].
pub mod chatmangpt_deployment {
    /// development
    pub const DEVELOPMENT: &str = "development";
    /// staging
    pub const STAGING: &str = "staging";
    /// production
    pub const PRODUCTION: &str = "production";
}

/// Shared identifier for a single Weaver live-check or CI run so spans across projects (OSA, Canopy, BusinessOS, pm4py-rust) can be filtered as one audit story.
pub const CHATMANGPT_RUN_CORRELATION_ID: &str = "chatmangpt.run.correlation_id";

/// Priority tier of the operation, used for budget enforcement.
pub const CHATMANGPT_SERVICE_TIER: &str = "chatmangpt.service.tier";

/// Values for [`CHATMANGPT_SERVICE_TIER`].
pub mod chatmangpt_service_tier {
    /// Critical priority tier — highest resource budget
    pub const CRITICAL: &str = "critical";
    /// High priority tier
    pub const HIGH: &str = "high";
    /// Normal priority tier
    pub const NORMAL: &str = "normal";
    /// Low priority tier — lowest resource budget
    pub const LOW: &str = "low";
}

/// Unique identifier for the ChatmanGPT session.
pub const CHATMANGPT_SESSION_ID: &str = "chatmangpt.session.id";

/// Number of times the model was switched during the session.
pub const CHATMANGPT_SESSION_MODEL_SWITCHES: &str = "chatmangpt.session.model_switches";

/// Total tokens consumed in the session so far.
pub const CHATMANGPT_SESSION_TOKEN_COUNT: &str = "chatmangpt.session.token_count";

/// Number of conversation turns in the session.
pub const CHATMANGPT_SESSION_TURN_COUNT: &str = "chatmangpt.session.turn_count";

/// Version of the ChatmanGPT system emitting this telemetry.
pub const CHATMANGPT_VERSION: &str = "chatmangpt.version";

/// Wave number of the ChatmanGPT development phase that produced this span.
pub const CHATMANGPT_WAVE: &str = "chatmangpt.wave";
