// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/conformance/registry.yaml

/// Conformance Attributes
/// Conformance fitness score [0.0, 1.0] measuring how well the trace fits the model.
pub const CONFORMANCE_FITNESS: &str = "conformance.fitness";

/// Conformance precision score [0.0, 1.0] measuring model over-fitting.
pub const CONFORMANCE_PRECISION: &str = "conformance.precision";
