// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/connector/registry.yaml

/// Enterprise Connector Attributes
/// Timeout in milliseconds for the connector's external API call (WvdA deadlock-freedom).
pub const CONNECTOR_API_TIMEOUT_MS: &str = "connector.api_timeout_ms";

/// Number of distinct process cases (traces) extracted.
pub const CONNECTOR_EXTRACTED_CASE_COUNT: &str = "connector.extracted_case_count";

/// Number of events successfully extracted from source records.
pub const CONNECTOR_EXTRACTED_EVENT_COUNT: &str = "connector.extracted_event_count";

/// Wall-clock time in milliseconds for the full extraction operation.
pub const CONNECTOR_EXTRACTION_TIME_MS: &str = "connector.extraction_time_ms";

/// Name identifying the connector instance.
pub const CONNECTOR_NAME: &str = "connector.name";

/// Number of raw source records fetched from the connector.
pub const CONNECTOR_SOURCE_RECORD_COUNT: &str = "connector.source_record_count";

/// The type of enterprise connector.
pub const CONNECTOR_TYPE: &str = "connector.type";

/// Values for [`CONNECTOR_TYPE`].
pub mod connector_type {
    /// SAP OData v2/v4 connector
    pub const SAP: &str = "sap";
    /// Salesforce SOQL connector
    pub const SALESFORCE: &str = "salesforce";
    /// ServiceNow Table API connector
    pub const SERVICENOW: &str = "servicenow";
    /// Local CSV file connector
    pub const CSV: &str = "csv";
    /// Inbound webhook JSON connector
    pub const WEBHOOK: &str = "webhook";
}
