// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/connector/spans.yaml

/// Span for SAP OData extraction. Emitted by SapODataConnector::extract().
pub const CONNECTOR_SAP_EXTRACT_SPAN: &str = "connector.sap.extract";

/// Span for Salesforce SOQL extraction. Emitted by SalesforceConnector::extract().
pub const CONNECTOR_SALESFORCE_EXTRACT_SPAN: &str = "connector.salesforce.extract";

/// Span for ServiceNow Table API extraction. Emitted by ServiceNowConnector::extract().
pub const CONNECTOR_SERVICENOW_EXTRACT_SPAN: &str = "connector.servicenow.extract";
