// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/consensus/registry.yaml

/// Consensus Attributes
/// Block height (sequence number) of the committed decision in the consensus log.
pub const CONSENSUS_BLOCK_HEIGHT: &str = "consensus.block.height";

/// Hash of the proposed block in this consensus round.
pub const CONSENSUS_BLOCK_HASH: &str = "consensus.block_hash";

/// Number of byzantine faults detected in the current epoch.
pub const CONSENSUS_BYZANTINE_DETECTED_FAULTS: &str = "consensus.byzantine.detected_faults";

/// Number of quorum size adjustments made during byzantine recovery.
pub const CONSENSUS_BYZANTINE_QUORUM_ADJUSTMENTS: &str = "consensus.byzantine.quorum_adjustments";

/// Round number at which byzantine fault recovery was initiated.
pub const CONSENSUS_BYZANTINE_RECOVERY_ROUND: &str = "consensus.byzantine.recovery_round";

/// Number of Byzantine (malicious/faulty) nodes detected in the current consensus view.
pub const CONSENSUS_BYZANTINE_FAULTS: &str = "consensus.byzantine_faults";

/// Hash or compact representation of the decided value (for audit/tracing purposes).
pub const CONSENSUS_DECISION_VALUE: &str = "consensus.decision.value";

/// Duration of the consensus epoch in milliseconds.
pub const CONSENSUS_EPOCH_DURATION_MS: &str = "consensus.epoch.duration_ms";

/// The consensus round number at which the epoch was finalized.
pub const CONSENSUS_EPOCH_FINALIZATION_ROUND: &str = "consensus.epoch.finalization.round";

/// Number of validator signatures collected for epoch finalization proof.
pub const CONSENSUS_EPOCH_FINALIZATION_SIGNATURE_COUNT: &str =
    "consensus.epoch.finalization.signature_count";

/// Monotonically increasing epoch identifier for the consensus protocol.
pub const CONSENSUS_EPOCH_ID: &str = "consensus.epoch.id";

/// Unique identifier for the key rotation event within a consensus epoch.
pub const CONSENSUS_EPOCH_KEY_ROTATION_ID: &str = "consensus.epoch.key_rotation_id";

/// Duration of the key rotation operation in milliseconds.
pub const CONSENSUS_EPOCH_KEY_ROTATION_MS: &str = "consensus.epoch.key_rotation_ms";

/// Reason that triggered the epoch key rotation.
pub const CONSENSUS_EPOCH_KEY_ROTATION_REASON: &str = "consensus.epoch.key_rotation_reason";

/// Values for [`CONSENSUS_EPOCH_KEY_ROTATION_REASON`].
pub mod consensus_epoch_key_rotation_reason {
    /// scheduled
    pub const SCHEDULED: &str = "scheduled";
    /// compromise
    pub const COMPROMISE: &str = "compromise";
    /// membership_change
    pub const MEMBERSHIP_CHANGE: &str = "membership_change";
}

/// Number of leader changes that occurred during this epoch.
pub const CONSENSUS_EPOCH_LEADER_CHANGES: &str = "consensus.epoch.leader_changes";

/// Hash of the quorum membership set for integrity verification.
pub const CONSENSUS_EPOCH_QUORUM_SNAPSHOT_HASH: &str = "consensus.epoch.quorum_snapshot_hash";

/// Round number at which the quorum snapshot was taken.
pub const CONSENSUS_EPOCH_QUORUM_SNAPSHOT_ROUND: &str = "consensus.epoch.quorum_snapshot_round";

/// Number of nodes in the quorum at snapshot time.
pub const CONSENSUS_EPOCH_QUORUM_SNAPSHOT_SIZE: &str = "consensus.epoch.quorum_snapshot_size";

/// Round number at which this epoch began.
pub const CONSENSUS_EPOCH_START_ROUND: &str = "consensus.epoch.start_round";

/// The epoch number transitioning from.
pub const CONSENSUS_EPOCH_TRANSITION_FROM_EPOCH: &str = "consensus.epoch.transition.from_epoch";

/// The epoch number transitioning to.
pub const CONSENSUS_EPOCH_TRANSITION_TO_EPOCH: &str = "consensus.epoch.transition.to_epoch";

/// Trigger that initiated the epoch transition.
pub const CONSENSUS_EPOCH_TRANSITION_TRIGGER: &str = "consensus.epoch.transition.trigger";

/// Values for [`CONSENSUS_EPOCH_TRANSITION_TRIGGER`].
pub mod consensus_epoch_transition_trigger {
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// quorum_change
    pub const QUORUM_CHANGE: &str = "quorum_change";
    /// key_rotation
    pub const KEY_ROTATION: &str = "key_rotation";
}

/// Number of Byzantine failures detected in the current view.
pub const CONSENSUS_FAILURE_COUNT: &str = "consensus.failure.count";

/// Depth of the detected fork — number of diverged blocks.
pub const CONSENSUS_FORK_DEPTH: &str = "consensus.fork.depth";

/// Whether a fork was detected in the consensus chain.
pub const CONSENSUS_FORK_DETECTED: &str = "consensus.fork.detected";

/// Strategy used to resolve the detected fork.
pub const CONSENSUS_FORK_RESOLUTION_STRATEGY: &str = "consensus.fork.resolution_strategy";

/// Values for [`CONSENSUS_FORK_RESOLUTION_STRATEGY`].
pub mod consensus_fork_resolution_strategy {
    /// longest_chain
    pub const LONGEST_CHAIN: &str = "longest_chain";
    /// highest_vote
    pub const HIGHEST_VOTE: &str = "highest_vote";
    /// epoch_based
    pub const EPOCH_BASED: &str = "epoch_based";
}

/// Latency of the consensus round in milliseconds.
pub const CONSENSUS_LATENCY_MS: &str = "consensus.latency_ms";

/// The node ID of the current consensus leader.
pub const CONSENSUS_LEADER_ID: &str = "consensus.leader.id";

/// Number of leader rotations since consensus started.
pub const CONSENSUS_LEADER_ROTATION_COUNT: &str = "consensus.leader.rotation_count";

/// Leader selection score used in the rotation algorithm [0.0, 1.0].
pub const CONSENSUS_LEADER_SCORE: &str = "consensus.leader.score";

/// Duration of the current leader's tenure in milliseconds.
pub const CONSENSUS_LEADER_TENURE_MS: &str = "consensus.leader.tenure_ms";

/// Number of consecutive rounds completed to prove liveness of the protocol.
pub const CONSENSUS_LIVENESS_PROOF_ROUNDS: &str = "consensus.liveness.proof_rounds";

/// Ratio of elapsed time to view timeout — approaching 1.0 means view change imminent.
pub const CONSENSUS_LIVENESS_TIMEOUT_RATIO: &str = "consensus.liveness.timeout_ratio";

/// Network diameter in hops — the longest shortest path between any two nodes.
pub const CONSENSUS_NETWORK_DIAMETER_HOPS: &str = "consensus.network.diameter_hops";

/// Average node degree (connections per node) in the consensus network topology.
pub const CONSENSUS_NETWORK_NODE_DEGREE: &str = "consensus.network.node_degree";

/// Number of network partitions detected in the consensus cluster.
pub const CONSENSUS_NETWORK_PARTITION_COUNT: &str = "consensus.network.partition_count";

/// Whether a network partition has been detected affecting consensus.
pub const CONSENSUS_NETWORK_PARTITION_DETECTED: &str = "consensus.network.partition_detected";

/// Time taken to recover network connectivity in milliseconds.
pub const CONSENSUS_NETWORK_RECOVERY_DURATION_MS: &str = "consensus.network.recovery.duration_ms";

/// Number of nodes that rejoined the consensus cluster during recovery.
pub const CONSENSUS_NETWORK_RECOVERY_NODES_REJOINED: &str =
    "consensus.network.recovery.nodes_rejoined";

/// Number of consensus rounds missed during network outage.
pub const CONSENSUS_NETWORK_RECOVERY_ROUNDS_MISSED: &str =
    "consensus.network.recovery.rounds_missed";

/// Strategy used to recover consensus network connectivity.
pub const CONSENSUS_NETWORK_RECOVERY_STRATEGY: &str = "consensus.network.recovery.strategy";

/// Values for [`CONSENSUS_NETWORK_RECOVERY_STRATEGY`].
pub mod consensus_network_recovery_strategy {
    /// reconnect
    pub const RECONNECT: &str = "reconnect";
    /// rejoin
    pub const REJOIN: &str = "rejoin";
    /// bootstrap
    pub const BOOTSTRAP: &str = "bootstrap";
}

/// Time in milliseconds for the network to recover from a partition event.
pub const CONSENSUS_NETWORK_RECOVERY_MS: &str = "consensus.network.recovery_ms";

/// The topology type of the consensus network.
pub const CONSENSUS_NETWORK_TOPOLOGY_TYPE: &str = "consensus.network.topology_type";

/// Values for [`CONSENSUS_NETWORK_TOPOLOGY_TYPE`].
pub mod consensus_network_topology_type {
    /// ring
    pub const RING: &str = "ring";
    /// mesh
    pub const MESH: &str = "mesh";
    /// star
    pub const STAR: &str = "star";
    /// bus
    pub const BUS: &str = "bus";
}

/// Node identifier for the consensus round (hostname, cluster node, etc).
pub const CONSENSUS_NODE: &str = "consensus.node";

/// Identifier of the consensus node.
pub const CONSENSUS_NODE_ID: &str = "consensus.node_id";

/// Whether a network partition was detected in the consensus cluster.
pub const CONSENSUS_PARTITION_DETECTED: &str = "consensus.partition.detected";

/// The strategy used to heal the consensus state after partition recovery.
pub const CONSENSUS_PARTITION_HEAL_STRATEGY: &str = "consensus.partition.heal_strategy";

/// Values for [`CONSENSUS_PARTITION_HEAL_STRATEGY`].
pub mod consensus_partition_heal_strategy {
    /// majority_wins
    pub const MAJORITY_WINS: &str = "majority_wins";
    /// epoch_fence
    pub const EPOCH_FENCE: &str = "epoch_fence";
    /// leader_arbitration
    pub const LEADER_ARBITRATION: &str = "leader_arbitration";
    /// rollback
    pub const ROLLBACK: &str = "rollback";
}

/// Duration (ms) for which the partition was isolated before healing began.
pub const CONSENSUS_PARTITION_ISOLATION_MS: &str = "consensus.partition.isolation_ms";

/// Time in milliseconds to recover from the network partition.
pub const CONSENSUS_PARTITION_RECOVERY_MS: &str = "consensus.partition.recovery_ms";

/// Number of nodes in the detected partition.
pub const CONSENSUS_PARTITION_SIZE: &str = "consensus.partition.size";

/// Strategy used to resolve the network partition.
pub const CONSENSUS_PARTITION_STRATEGY: &str = "consensus.partition.strategy";

/// Values for [`CONSENSUS_PARTITION_STRATEGY`].
pub mod consensus_partition_strategy {
    /// majority_wins
    pub const MAJORITY_WINS: &str = "majority_wins";
    /// epoch_based
    pub const EPOCH_BASED: &str = "epoch_based";
    /// manual
    pub const MANUAL: &str = "manual";
}

/// The current phase of the HotStuff BFT consensus protocol.
pub const CONSENSUS_PHASE: &str = "consensus.phase";

/// Values for [`CONSENSUS_PHASE`].
pub mod consensus_phase {
    /// HotStuff PREPARE phase — leader proposes
    pub const PREPARE: &str = "prepare";
    /// HotStuff PRE-COMMIT phase — collect prepare votes
    pub const PRE_COMMIT: &str = "pre_commit";
    /// HotStuff COMMIT phase — collect pre-commit votes
    pub const COMMIT: &str = "commit";
    /// HotStuff DECIDE phase — finalize block
    pub const DECIDE: &str = "decide";
    /// View change triggered by leader timeout
    pub const VIEW_CHANGE: &str = "view_change";
}

/// Number of new replicas admitted to the quorum during this growth operation.
pub const CONSENSUS_QUORUM_ADMITTED_COUNT: &str = "consensus.quorum.admitted_count";

/// Current quorum size before the growth operation.
pub const CONSENSUS_QUORUM_CURRENT_SIZE: &str = "consensus.quorum.current_size";

/// Rate of quorum size growth per epoch, as a fraction of current quorum size.
pub const CONSENSUS_QUORUM_GROWTH_RATE: &str = "consensus.quorum.growth_rate";

/// Health status of the quorum — based on how many replicas are reachable relative to quorum threshold.
pub const CONSENSUS_QUORUM_HEALTH: &str = "consensus.quorum.health";

/// Values for [`CONSENSUS_QUORUM_HEALTH`].
pub mod consensus_quorum_health {
    /// healthy
    pub const HEALTHY: &str = "healthy";
    /// degraded
    pub const DEGRADED: &str = "degraded";
    /// critical
    pub const CRITICAL: &str = "critical";
}

/// New quorum size after the shrink operation completes.
pub const CONSENSUS_QUORUM_SHRINK_NEW_SIZE: &str = "consensus.quorum.shrink.new_size";

/// The reason for shrinking the consensus quorum.
pub const CONSENSUS_QUORUM_SHRINK_REASON: &str = "consensus.quorum.shrink.reason";

/// Values for [`CONSENSUS_QUORUM_SHRINK_REASON`].
pub mod consensus_quorum_shrink_reason {
    /// node_failure
    pub const NODE_FAILURE: &str = "node_failure";
    /// config_change
    pub const CONFIG_CHANGE: &str = "config_change";
    /// rebalance
    pub const REBALANCE: &str = "rebalance";
    /// decommission
    pub const DECOMMISSION: &str = "decommission";
}

/// Number of nodes removed from the quorum in this shrink operation.
pub const CONSENSUS_QUORUM_SHRINK_REMOVED_COUNT: &str = "consensus.quorum.shrink.removed_count";

/// Fault tolerance margin remaining after shrink, as fraction [0.0, 1.0].
pub const CONSENSUS_QUORUM_SHRINK_SAFETY_MARGIN: &str = "consensus.quorum.shrink.safety_margin";

/// Target quorum size after growth operation completes.
pub const CONSENSUS_QUORUM_TARGET_SIZE: &str = "consensus.quorum.target_size";

/// Number of votes required for quorum (typically 2f+1 for f Byzantine faults).
pub const CONSENSUS_QUORUM_SIZE: &str = "consensus.quorum_size";

/// Total number of replicas participating in the consensus protocol.
pub const CONSENSUS_REPLICA_COUNT: &str = "consensus.replica.count";

/// Replication lag in milliseconds — how far behind the slowest replica is.
pub const CONSENSUS_REPLICA_LAG_MS: &str = "consensus.replica.lag_ms";

/// The round number within the BFT consensus protocol.
pub const CONSENSUS_ROUND_NUM: &str = "consensus.round_num";

/// Phase of the BFT consensus round.
pub const CONSENSUS_ROUND_TYPE: &str = "consensus.round_type";

/// Values for [`CONSENSUS_ROUND_TYPE`].
pub mod consensus_round_type {
    /// BFT prepare phase
    pub const PREPARE: &str = "prepare";
    /// BFT promise phase
    pub const PROMISE: &str = "promise";
    /// BFT accept phase
    pub const ACCEPT: &str = "accept";
    /// BFT learn phase
    pub const LEARN: &str = "learn";
}

/// Interval between consecutive safety checks in milliseconds.
pub const CONSENSUS_SAFETY_CHECK_INTERVAL_MS: &str = "consensus.safety.check_interval_ms";

/// Achieved safety quorum ratio during the consensus round, range [0.0, 1.0].
pub const CONSENSUS_SAFETY_QUORUM_RATIO: &str = "consensus.safety.quorum_ratio";

/// Minimum fraction of replicas required for a safe consensus decision [0.0, 1.0]. Typical: 0.67 (2/3).
pub const CONSENSUS_SAFETY_THRESHOLD: &str = "consensus.safety.threshold";

/// Unique identifier for the safety violation event.
pub const CONSENSUS_SAFETY_VIOLATION_ID: &str = "consensus.safety.violation.id";

/// Severity level of the safety violation.
pub const CONSENSUS_SAFETY_VIOLATION_SEVERITY: &str = "consensus.safety.violation.severity";

/// Values for [`CONSENSUS_SAFETY_VIOLATION_SEVERITY`].
pub mod consensus_safety_violation_severity {
    /// Potential safety violation detected, system remains safe
    pub const WARNING: &str = "warning";
    /// Safety violation confirmed, immediate intervention required
    pub const CRITICAL: &str = "critical";
    /// Unrecoverable safety violation, consensus must restart
    pub const FATAL: &str = "fatal";
}

/// Type of consensus safety violation detected.
pub const CONSENSUS_SAFETY_VIOLATION_TYPE: &str = "consensus.safety.violation.type";

/// Values for [`CONSENSUS_SAFETY_VIOLATION_TYPE`].
pub mod consensus_safety_violation_type {
    /// Replica voted for conflicting blocks in the same phase
    pub const DOUBLE_VOTE: &str = "double_vote";
    /// Replica sent conflicting messages violating protocol rules
    pub const EQUIVOCATION: &str = "equivocation";
    /// Decision made without sufficient quorum majority
    pub const QUORUM_BREACH: &str = "quorum_breach";
}

/// Number of safety violations detected in the current consensus epoch.
pub const CONSENSUS_SAFETY_VIOLATION_COUNT: &str = "consensus.safety.violation_count";

/// Number of valid cryptographic signatures collected in this round.
pub const CONSENSUS_SIGNATURE_COUNT: &str = "consensus.signature_count";

/// Rate at which the consensus threshold is adapted per round, range [0.0, 1.0].
pub const CONSENSUS_THRESHOLD_ADAPTATION_RATE: &str = "consensus.threshold.adaptation_rate";

/// Current consensus threshold value (fraction of replicas required for quorum), range (0.5, 1.0].
pub const CONSENSUS_THRESHOLD_CURRENT: &str = "consensus.threshold.current";

/// Target fault tolerance ratio (max fraction of Byzantine faults tolerated), range [0.0, 0.5).
pub const CONSENSUS_THRESHOLD_FAULT_TOLERANCE_TARGET: &str =
    "consensus.threshold.fault_tolerance_target";

/// Number of negative votes cast.
pub const CONSENSUS_THRESHOLD_NAY_COUNT: &str = "consensus.threshold.nay_count";

/// The voting threshold type required for consensus.
pub const CONSENSUS_THRESHOLD_VOTE_TYPE: &str = "consensus.threshold.vote_type";

/// Values for [`CONSENSUS_THRESHOLD_VOTE_TYPE`].
pub mod consensus_threshold_vote_type {
    /// supermajority
    pub const SUPERMAJORITY: &str = "supermajority";
    /// simple
    pub const SIMPLE: &str = "simple";
    /// unanimous
    pub const UNANIMOUS: &str = "unanimous";
}

/// Number of affirmative votes cast.
pub const CONSENSUS_THRESHOLD_YEA_COUNT: &str = "consensus.threshold.yea_count";

/// Timeout in milliseconds for the current consensus round.
pub const CONSENSUS_TIMEOUT_MS: &str = "consensus.timeout_ms";

/// Timestamp when the consensus round occurred (ISO 8601 format).
pub const CONSENSUS_TIMESTAMP: &str = "consensus.timestamp";

/// Version of the consensus protocol/implementation being executed.
pub const CONSENSUS_VERSION: &str = "consensus.version";

/// Duration of the current consensus view in milliseconds.
pub const CONSENSUS_VIEW_DURATION_MS: &str = "consensus.view.duration_ms";

/// Exponential backoff delay applied before attempting view change.
pub const CONSENSUS_VIEW_CHANGE_BACKOFF_MS: &str = "consensus.view_change.backoff_ms";

/// Duration of the view change protocol in milliseconds.
pub const CONSENSUS_VIEW_CHANGE_DURATION_MS: &str = "consensus.view_change.duration_ms";

/// Reason that triggered the view change.
pub const CONSENSUS_VIEW_CHANGE_REASON: &str = "consensus.view_change.reason";

/// Values for [`CONSENSUS_VIEW_CHANGE_REASON`].
pub mod consensus_view_change_reason {
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// leader_failure
    pub const LEADER_FAILURE: &str = "leader_failure";
    /// network_partition
    pub const NETWORK_PARTITION: &str = "network_partition";
    /// manual
    pub const MANUAL: &str = "manual";
    /// equivocation
    pub const EQUIVOCATION: &str = "equivocation";
}

/// The current view number in the HotStuff protocol (monotonically increasing).
pub const CONSENSUS_VIEW_NUMBER: &str = "consensus.view_number";

/// Timeout in milliseconds for the current view (Armstrong fault tolerance budget).
pub const CONSENSUS_VIEW_TIMEOUT_MS: &str = "consensus.view_timeout_ms";

/// Current number of votes collected for this round.
pub const CONSENSUS_VOTE_COUNT: &str = "consensus.vote_count";
