// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/conversation/registry.yaml

/// Conversation Attributes
/// Current context window usage in tokens for this conversation.
pub const CONVERSATION_CONTEXT_TOKENS: &str = "conversation.context_tokens";

/// Unique identifier for this conversation session.
pub const CONVERSATION_ID: &str = "conversation.id";

/// Role of the message sender in the conversation.
pub const CONVERSATION_MESSAGE_ROLE: &str = "conversation.message.role";

/// Values for [`CONVERSATION_MESSAGE_ROLE`].
pub mod conversation_message_role {
    /// user
    pub const USER: &str = "user";
    /// assistant
    pub const ASSISTANT: &str = "assistant";
    /// system
    pub const SYSTEM: &str = "system";
    /// tool
    pub const TOOL: &str = "tool";
}

/// The LLM model driving this conversation (same as llm.model but conversation-scoped).
pub const CONVERSATION_MODEL: &str = "conversation.model";

/// Current phase of the conversation lifecycle.
pub const CONVERSATION_PHASE: &str = "conversation.phase";

/// Values for [`CONVERSATION_PHASE`].
pub mod conversation_phase {
    /// init
    pub const INIT: &str = "init";
    /// active
    pub const ACTIVE: &str = "active";
    /// waiting
    pub const WAITING: &str = "waiting";
    /// complete
    pub const COMPLETE: &str = "complete";
    /// error
    pub const ERROR: &str = "error";
}

/// Token count of the compressed summary after context compression.
pub const CONVERSATION_SUMMARY_TOKENS: &str = "conversation.summary.tokens";

/// Cumulative number of tool calls made during this conversation.
pub const CONVERSATION_TOOL_CALLS: &str = "conversation.tool_calls";

/// Total number of turns (human+assistant message pairs) in this conversation.
pub const CONVERSATION_TURN_COUNT: &str = "conversation.turn_count";

/// Anonymized identifier of the user in this conversation (for correlation, not PII).
pub const CONVERSATION_USER_ID: &str = "conversation.user_id";
