// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/decision/spans.yaml

/// Groq-powered workflow decision — classifying a YAWL WCP pattern and selecting next action.
///
/// Span: `span.decision.workflow`
/// Kind: `internal`
/// Stability: `development`
pub const DECISION_WORKFLOW_SPAN: &str = "decision.workflow";
