// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/decision/registry.yaml

/// Decision Attributes
/// JSON-encoded result of the Groq workflow decision (e.g. action, confidence).
pub const DECISION_RESULT: &str = "decision.result";

/// The YAWL Workflow Control-flow Pattern identifier that the Groq decision targets.
pub const DECISION_WCP_PATTERN: &str = "decision.wcp_pattern";
