// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/error/registry.yaml

/// Error Attributes
/// Describes a class of error the operation ended with.
pub const ERROR_TYPE: &str = "error.type";

/// Values for [`ERROR_TYPE`].
pub mod error_type {
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// cancelled
    pub const CANCELLED: &str = "cancelled";
    /// internal
    pub const INTERNAL: &str = "internal";
    /// unavailable
    pub const UNAVAILABLE: &str = "unavailable";
}
