// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/event/registry.yaml

/// Event Attributes
/// ID of the event that directly caused this event (parent-child causality chain).
pub const EVENT_CAUSATION_ID: &str = "event.causation_id";

/// Correlation ID linking related events across distributed services (trace-level grouping).
pub const EVENT_CORRELATION_ID: &str = "event.correlation_id";

/// Delivery status of the event in the event bus.
pub const EVENT_DELIVERY_STATUS: &str = "event.delivery.status";

/// Values for [`EVENT_DELIVERY_STATUS`].
pub mod event_delivery_status {
    /// delivered
    pub const DELIVERED: &str = "delivered";
    /// failed
    pub const FAILED: &str = "failed";
    /// retrying
    pub const RETRYING: &str = "retrying";
    /// dropped
    pub const DROPPED: &str = "dropped";
}

/// The domain of the structured event.
pub const EVENT_DOMAIN: &str = "event.domain";

/// Values for [`EVENT_DOMAIN`].
pub mod event_domain {
    /// agent
    pub const AGENT: &str = "agent";
    /// compliance
    pub const COMPLIANCE: &str = "compliance";
    /// healing
    pub const HEALING: &str = "healing";
    /// workflow
    pub const WORKFLOW: &str = "workflow";
    /// system
    pub const SYSTEM: &str = "system";
}

/// Number of handlers that received this event.
pub const EVENT_HANDLER_COUNT: &str = "event.handler.count";

/// The name of the event (e.g., "agent.started", "compliance.violation.detected").
pub const EVENT_NAME: &str = "event.name";

/// Whether this event is a replay of a previously emitted event (idempotency tracking).
pub const EVENT_REPLAY: &str = "event.replay";

/// Number of routing filters applied to determine event delivery targets.
pub const EVENT_ROUTING_FILTER_COUNT: &str = "event.routing.filter_count";

/// Routing strategy used to deliver the event to subscribers.
pub const EVENT_ROUTING_STRATEGY: &str = "event.routing.strategy";

/// Values for [`EVENT_ROUTING_STRATEGY`].
pub mod event_routing_strategy {
    /// broadcast
    pub const BROADCAST: &str = "broadcast";
    /// unicast
    pub const UNICAST: &str = "unicast";
    /// multicast
    pub const MULTICAST: &str = "multicast";
    /// topic_based
    pub const TOPIC_BASED: &str = "topic_based";
    /// content_based
    pub const CONTENT_BASED: &str = "content_based";
}

/// Schema version of the event payload (for schema evolution tracking).
pub const EVENT_SCHEMA_VERSION: &str = "event.schema.version";

/// The severity level of the event.
pub const EVENT_SEVERITY: &str = "event.severity";

/// Values for [`EVENT_SEVERITY`].
pub mod event_severity {
    /// debug
    pub const DEBUG: &str = "debug";
    /// info
    pub const INFO: &str = "info";
    /// warn
    pub const WARN: &str = "warn";
    /// error
    pub const ERROR: &str = "error";
    /// fatal
    pub const FATAL: &str = "fatal";
}

/// The source component that emitted the event.
pub const EVENT_SOURCE: &str = "event.source";

/// Service that emitted this event (e.g., osa, businessos, canopy).
pub const EVENT_SOURCE_SERVICE: &str = "event.source.service";

/// Number of subscribers that received the event.
pub const EVENT_SUBSCRIBER_COUNT: &str = "event.subscriber.count";

/// Service that is the intended consumer of this event.
pub const EVENT_TARGET_SERVICE: &str = "event.target.service";

/// Schema version of the event payload for forward-compatibility tracking.
pub const EVENT_VERSION: &str = "event.version";
