// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/groq/registry.yaml

/// Groq Attributes
/// The Groq model identifier used for the LLM call.
pub const GROQ_MODEL: &str = "groq.model";

/// Number of prompt tokens consumed by the Groq LLM call.
pub const GROQ_PROMPT_TOKENS: &str = "groq.prompt_tokens";
