// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/healing/registry.yaml

/// Healing Attributes
/// Current retry attempt number (1-indexed) for adaptive retry logic.
pub const HEALING_RETRY_ADAPTIVE_ATTEMPT: &str = "healing.retry.adaptive.attempt";

/// Backoff duration in milliseconds before the next retry attempt.
pub const HEALING_RETRY_ADAPTIVE_BACKOFF_MS: &str = "healing.retry.adaptive.backoff_ms";

/// Backoff strategy for adaptive retries during healing.
pub const HEALING_RETRY_ADAPTIVE_STRATEGY: &str = "healing.retry.adaptive.strategy";

/// Values for [`HEALING_RETRY_ADAPTIVE_STRATEGY`].
pub mod healing_retry_adaptive_strategy {
    /// Exponential backoff (2^attempt * base_ms)
    pub const EXPONENTIAL: &str = "exponential";
    /// Linear backoff (attempt * base_ms)
    pub const LINEAR: &str = "linear";
    /// Fibonacci backoff sequence
    pub const FIBONACCI: &str = "fibonacci";
    /// Constant backoff (base_ms)
    pub const CONSTANT: &str = "constant";
}

/// Learning rate used to adjust the adaptive healing threshold — controls how quickly it adapts.
pub const HEALING_ADAPTIVE_LEARNING_RATE: &str = "healing.adaptive.learning_rate";

/// Current adaptive healing threshold — dynamically adjusted based on system behavior.
pub const HEALING_ADAPTIVE_THRESHOLD_CURRENT: &str = "healing.adaptive.threshold_current";

/// Maximum allowed value for the adaptive healing threshold.
pub const HEALING_ADAPTIVE_THRESHOLD_MAX: &str = "healing.adaptive.threshold_max";

/// Minimum allowed value for the adaptive healing threshold.
pub const HEALING_ADAPTIVE_THRESHOLD_MIN: &str = "healing.adaptive.threshold_min";

/// Identifier of the OSA agent that owns the healing operation.
pub const HEALING_AGENT_ID: &str = "healing.agent_id";

/// Baseline observation window in milliseconds used for anomaly detection.
pub const HEALING_ANOMALY_BASELINE_MS: &str = "healing.anomaly.baseline_ms";

/// Method used to detect the system anomaly.
pub const HEALING_ANOMALY_DETECTION_METHOD: &str = "healing.anomaly.detection_method";

/// Values for [`HEALING_ANOMALY_DETECTION_METHOD`].
pub mod healing_anomaly_detection_method {
    /// statistical
    pub const STATISTICAL: &str = "statistical";
    /// ml
    pub const ML: &str = "ml";
    /// rule_based
    pub const RULE_BASED: &str = "rule_based";
    /// hybrid
    pub const HYBRID: &str = "hybrid";
}

/// Anomaly score for the detected system behavior, range [0.0, 1.0]. Higher = more anomalous.
pub const HEALING_ANOMALY_SCORE: &str = "healing.anomaly.score";

/// Score threshold above which behavior is classified as anomalous, range [0.0, 1.0].
pub const HEALING_ANOMALY_THRESHOLD: &str = "healing.anomaly.threshold";

/// Current healing attempt number (1-indexed) for this failure event.
pub const HEALING_ATTEMPT: &str = "healing.attempt";

/// The number of healing attempts made for this failure (1-indexed).
pub const HEALING_ATTEMPT_NUMBER: &str = "healing.attempt_number";

/// Fraction of healing requests dropped due to backpressure [0.0, 1.0].
pub const HEALING_BACKPRESSURE_DROP_RATE: &str = "healing.backpressure.drop_rate";

/// Current backpressure level in the healing pipeline.
pub const HEALING_BACKPRESSURE_LEVEL: &str = "healing.backpressure.level";

/// Values for [`HEALING_BACKPRESSURE_LEVEL`].
pub mod healing_backpressure_level {
    /// none
    pub const NONE: &str = "none";
    /// low
    pub const LOW: &str = "low";
    /// medium
    pub const MEDIUM: &str = "medium";
    /// high
    pub const HIGH: &str = "high";
    /// critical
    pub const CRITICAL: &str = "critical";
}

/// Current number of healing requests queued.
pub const HEALING_BACKPRESSURE_QUEUE_DEPTH: &str = "healing.backpressure.queue_depth";

/// Depth of the cascade failure chain — number of chained failures detected.
pub const HEALING_CASCADE_DEPTH: &str = "healing.cascade.depth";

/// Whether a cascade failure was detected during healing (multiple correlated failures).
pub const HEALING_CASCADE_DETECTED: &str = "healing.cascade.detected";

/// Compression ratio of the healing checkpoint data, range [0.0, 1.0].
pub const HEALING_CHECKPOINT_COMPRESSION_RATIO: &str = "healing.checkpoint.compression_ratio";

/// Unique identifier for the healing checkpoint.
pub const HEALING_CHECKPOINT_ID: &str = "healing.checkpoint.id";

/// Time taken to restore from the checkpoint in milliseconds.
pub const HEALING_CHECKPOINT_RESTORE_MS: &str = "healing.checkpoint.restore_ms";

/// Size of the healing checkpoint in bytes.
pub const HEALING_CHECKPOINT_SIZE_BYTES: &str = "healing.checkpoint.size_bytes";

/// Total number of calls passed through the circuit breaker in current window.
pub const HEALING_CIRCUIT_BREAKER_CALL_COUNT: &str = "healing.circuit_breaker.call_count";

/// Number of consecutive failures that triggered the circuit breaker.
pub const HEALING_CIRCUIT_BREAKER_FAILURE_COUNT: &str = "healing.circuit_breaker.failure_count";

/// Time in milliseconds before the circuit breaker attempts half-open reset.
pub const HEALING_CIRCUIT_BREAKER_RESET_MS: &str = "healing.circuit_breaker.reset_ms";

/// Current state of the healing circuit breaker.
pub const HEALING_CIRCUIT_BREAKER_STATE: &str = "healing.circuit_breaker.state";

/// Values for [`HEALING_CIRCUIT_BREAKER_STATE`].
pub mod healing_circuit_breaker_state {
    /// closed
    pub const CLOSED: &str = "closed";
    /// open
    pub const OPEN: &str = "open";
    /// half_open
    pub const HALF_OPEN: &str = "half_open";
}

/// Data replication lag of the cold standby at the time of promotion, in milliseconds.
pub const HEALING_COLD_STANDBY_DATA_LAG_MS: &str = "healing.cold_standby.data_lag_ms";

/// Unique identifier of the cold standby instance being promoted.
pub const HEALING_COLD_STANDBY_ID: &str = "healing.cold_standby.id";

/// Readiness state of the cold standby instance.
pub const HEALING_COLD_STANDBY_READINESS: &str = "healing.cold_standby.readiness";

/// Values for [`HEALING_COLD_STANDBY_READINESS`].
pub mod healing_cold_standby_readiness {
    /// cold
    pub const COLD: &str = "cold";
    /// warming
    pub const WARMING: &str = "warming";
    /// ready
    pub const READY: &str = "ready";
    /// failed
    pub const FAILED: &str = "failed";
}

/// Time in milliseconds required to warm up the cold standby before it can serve traffic.
pub const HEALING_COLD_STANDBY_WARMUP_MS: &str = "healing.cold_standby.warmup_ms";

/// Confidence score for the failure mode classification, in range [0.0, 1.0].
pub const HEALING_CONFIDENCE: &str = "healing.confidence";

/// The diagnosis mode or strategy used in the healing classify operation.
pub const HEALING_DIAGNOSIS_MODE: &str = "healing.diagnosis.mode";

/// The current stage of the healing diagnosis pipeline.
pub const HEALING_DIAGNOSIS_STAGE: &str = "healing.diagnosis_stage";

/// Values for [`HEALING_DIAGNOSIS_STAGE`].
pub mod healing_diagnosis_stage {
    /// Initial anomaly detection phase
    pub const DETECTION: &str = "detection";
    /// Failure mode classification phase
    pub const CLASSIFICATION: &str = "classification";
    /// Verification of classification accuracy
    pub const VERIFICATION: &str = "verification";
    /// Escalation to human operator
    pub const ESCALATION: &str = "escalation";
}

/// Escalation level when automatic healing fails — determines alerting response.
pub const HEALING_ESCALATION_LEVEL: &str = "healing.escalation.level";

/// Values for [`HEALING_ESCALATION_LEVEL`].
pub mod healing_escalation_level {
    /// none
    pub const NONE: &str = "none";
    /// warn
    pub const WARN: &str = "warn";
    /// critical
    pub const CRITICAL: &str = "critical";
    /// page
    pub const PAGE: &str = "page";
}

/// Human-readable reason explaining why the healing operation was escalated to a human operator.
pub const HEALING_ESCALATION_REASON: &str = "healing.escalation_reason";

/// Duration (ms) of the failover operation from start to completion.
pub const HEALING_FAILOVER_DURATION_MS: &str = "healing.failover.duration_ms";

/// The identifier of the source (failing) system component.
pub const HEALING_FAILOVER_SOURCE_ID: &str = "healing.failover.source_id";

/// The identifier of the target (replacement) system component.
pub const HEALING_FAILOVER_TARGET_ID: &str = "healing.failover.target_id";

/// The type of failover transition being performed.
pub const HEALING_FAILOVER_TYPE: &str = "healing.failover.type";

/// Values for [`HEALING_FAILOVER_TYPE`].
pub mod healing_failover_type {
    /// warm_to_cold
    pub const WARM_TO_COLD: &str = "warm_to_cold";
    /// primary_to_warm
    pub const PRIMARY_TO_WARM: &str = "primary_to_warm";
    /// primary_to_cold
    pub const PRIMARY_TO_COLD: &str = "primary_to_cold";
    /// geographic
    pub const GEOGRAPHIC: &str = "geographic";
}

/// The classified failure mode detected by the healing diagnosis engine.
pub const HEALING_FAILURE_MODE: &str = "healing.failure_mode";

/// Values for [`HEALING_FAILURE_MODE`].
pub mod healing_failure_mode {
    /// Circular wait between processes
    pub const DEADLOCK: &str = "deadlock";
    /// Operation exceeded its time budget
    pub const TIMEOUT: &str = "timeout";
    /// Non-deterministic state conflict between processes
    pub const RACE_CONDITION: &str = "race_condition";
    /// Unbounded memory growth detected
    pub const MEMORY_LEAK: &str = "memory_leak";
    /// Failure propagated from upstream dependency
    pub const CASCADING_FAILURE: &str = "cascading_failure";
    /// Process stuck with no forward progress
    pub const STAGNATION: &str = "stagnation";
    /// Processes active but making no progress
    pub const LIVELOCK: &str = "livelock";
}

/// Process fingerprint hash for identifying similar failure patterns.
pub const HEALING_FINGERPRINT: &str = "healing.fingerprint";

/// The outcome result of the healing fix operation.
pub const HEALING_FIX_RESULT: &str = "healing.fix.result";

/// Values for [`HEALING_FIX_RESULT`].
pub mod healing_fix_result {
    /// success
    pub const SUCCESS: &str = "success";
    /// partial
    pub const PARTIAL: &str = "partial";
    /// failed
    pub const FAILED: &str = "failed";
}

/// Duration of the healing intervention in milliseconds.
pub const HEALING_INTERVENTION_DURATION_MS: &str = "healing.intervention.duration_ms";

/// Outcome of the healing intervention.
pub const HEALING_INTERVENTION_OUTCOME: &str = "healing.intervention.outcome";

/// Values for [`HEALING_INTERVENTION_OUTCOME`].
pub mod healing_intervention_outcome {
    /// success
    pub const SUCCESS: &str = "success";
    /// partial
    pub const PARTIAL: &str = "partial";
    /// failed
    pub const FAILED: &str = "failed";
    /// escalated
    pub const ESCALATED: &str = "escalated";
}

/// Intervention effectiveness score in range [0.0, 1.0] — higher is more effective.
pub const HEALING_INTERVENTION_SCORE: &str = "healing.intervention.score";

/// Type of healing intervention applied.
pub const HEALING_INTERVENTION_TYPE: &str = "healing.intervention.type";

/// Values for [`HEALING_INTERVENTION_TYPE`].
pub mod healing_intervention_type {
    /// automatic
    pub const AUTOMATIC: &str = "automatic";
    /// manual
    pub const MANUAL: &str = "manual";
    /// assisted
    pub const ASSISTED: &str = "assisted";
    /// deferred
    pub const DEFERRED: &str = "deferred";
}

/// Current iteration count in the recovery loop.
pub const HEALING_ITERATION: &str = "healing.iteration";

/// Percentage of requests shed (dropped) during this load shedding event, range [0.0, 100.0].
pub const HEALING_LOAD_SHEDDING_SHED_PCT: &str = "healing.load_shedding.shed_pct";

/// The strategy used to select which requests to shed.
pub const HEALING_LOAD_SHEDDING_STRATEGY: &str = "healing.load_shedding.strategy";

/// Values for [`HEALING_LOAD_SHEDDING_STRATEGY`].
pub mod healing_load_shedding_strategy {
    /// random
    pub const RANDOM: &str = "random";
    /// priority
    pub const PRIORITY: &str = "priority";
    /// oldest
    pub const OLDEST: &str = "oldest";
}

/// The load threshold (0.0-1.0) at which load shedding is triggered.
pub const HEALING_LOAD_SHEDDING_THRESHOLD: &str = "healing.load_shedding.threshold";

/// Maximum number of healing attempts before escalation.
pub const HEALING_MAX_ATTEMPTS: &str = "healing.max_attempts";

/// Maximum number of recovery iterations before escalation (WvdA liveness bound).
pub const HEALING_MAX_ITERATIONS: &str = "healing.max_iterations";

/// Compression ratio of the memory snapshot, range [0.0, 1.0] (1.0 = no compression).
pub const HEALING_MEMORY_COMPRESSION_RATIO: &str = "healing.memory.compression_ratio";

/// Duration in milliseconds to restore the system state from a memory snapshot.
pub const HEALING_MEMORY_RESTORE_MS: &str = "healing.memory.restore_ms";

/// Unique identifier for a healing memory snapshot used for state preservation.
pub const HEALING_MEMORY_SNAPSHOT_ID: &str = "healing.memory.snapshot_id";

/// Size in bytes of the healing memory snapshot.
pub const HEALING_MEMORY_SNAPSHOT_SIZE_BYTES: &str = "healing.memory.snapshot_size_bytes";

/// Mean time to recovery in milliseconds for the healing operation.
pub const HEALING_MTTR_MS: &str = "healing.mttr_ms";

/// Identifier of the healing pattern matched from the pattern library.
pub const HEALING_PATTERN_ID: &str = "healing.pattern.id";

/// Number of patterns currently loaded in the healing pattern library.
pub const HEALING_PATTERN_LIBRARY_SIZE: &str = "healing.pattern.library_size";

/// Confidence score for the matched healing pattern, range [0.0, 1.0].
pub const HEALING_PATTERN_MATCH_CONFIDENCE: &str = "healing.pattern.match_confidence";

/// Total execution time of the playbook in milliseconds.
pub const HEALING_PLAYBOOK_EXECUTION_MS: &str = "healing.playbook.execution_ms";

/// Identifier of the recovery playbook being executed.
pub const HEALING_PLAYBOOK_ID: &str = "healing.playbook.id";

/// Total number of steps in the recovery playbook.
pub const HEALING_PLAYBOOK_STEP_COUNT: &str = "healing.playbook.step_count";

/// Current step number being executed in the playbook.
pub const HEALING_PLAYBOOK_STEP_CURRENT: &str = "healing.playbook.step_current";

/// Confidence score for the failure prediction [0.0, 1.0].
pub const HEALING_PREDICTION_CONFIDENCE: &str = "healing.prediction.confidence";

/// Time horizon in milliseconds for which the failure prediction is made.
pub const HEALING_PREDICTION_HORIZON_MS: &str = "healing.prediction.horizon_ms";

/// Name or version of the predictive model used for failure prediction.
pub const HEALING_PREDICTION_MODEL: &str = "healing.prediction.model";

/// Whether the quarantine is currently active.
pub const HEALING_QUARANTINE_ACTIVE: &str = "healing.quarantine.active";

/// Duration in milliseconds the component remained in quarantine.
pub const HEALING_QUARANTINE_DURATION_MS: &str = "healing.quarantine.duration_ms";

/// Unique identifier for the quarantine zone applied to an isolated component.
pub const HEALING_QUARANTINE_ID: &str = "healing.quarantine.id";

/// Reason the component was placed into quarantine.
pub const HEALING_QUARANTINE_REASON: &str = "healing.quarantine.reason";

/// Values for [`HEALING_QUARANTINE_REASON`].
pub mod healing_quarantine_reason {
    /// anomaly
    pub const ANOMALY: &str = "anomaly";
    /// compliance
    pub const COMPLIANCE: &str = "compliance";
    /// cascade_risk
    pub const CASCADE_RISK: &str = "cascade_risk";
    /// manual
    pub const MANUAL: &str = "manual";
}

/// Maximum burst size above the base rate limit.
pub const HEALING_RATE_LIMIT_BURST_SIZE: &str = "healing.rate_limit.burst_size";

/// Current observed request rate per second.
pub const HEALING_RATE_LIMIT_CURRENT_RATE: &str = "healing.rate_limit.current_rate";

/// Maximum allowed recovery requests per second.
pub const HEALING_RATE_LIMIT_REQUESTS_PER_SEC: &str = "healing.rate_limit.requests_per_sec";

/// The recovery action taken by the reflex arc.
pub const HEALING_RECOVERY_ACTION: &str = "healing.recovery_action";

/// Whether the healing operation reached a terminal state (success or escalated).
pub const HEALING_RECOVERY_COMPLETE: &str = "healing.recovery_complete";

/// The recovery strategy selected by the healing engine.
pub const HEALING_RECOVERY_STRATEGY: &str = "healing.recovery_strategy";

/// Values for [`HEALING_RECOVERY_STRATEGY`].
pub mod healing_recovery_strategy {
    /// Restart the affected process
    pub const RESTART: &str = "restart";
    /// Rollback to last known good state
    pub const ROLLBACK: &str = "rollback";
    /// Open circuit breaker to shed load
    pub const CIRCUIT_BREAK: &str = "circuit_break";
    /// Isolate the failing component
    pub const ISOLATE: &str = "isolate";
    /// Gracefully degrade to reduced functionality
    pub const DEGRADE: &str = "degrade";
}

/// The named reflex arc triggered during healing.
pub const HEALING_REFLEX_ARC: &str = "healing.reflex_arc";

/// The repair strategy applied during healing recovery.
pub const HEALING_REPAIR_STRATEGY: &str = "healing.repair.strategy";

/// Values for [`HEALING_REPAIR_STRATEGY`].
pub mod healing_repair_strategy {
    /// restart
    pub const RESTART: &str = "restart";
    /// rollback
    pub const ROLLBACK: &str = "rollback";
    /// failover
    pub const FAILOVER: &str = "failover";
    /// rebalance
    pub const REBALANCE: &str = "rebalance";
}

/// Identifier of the checkpoint or snapshot used as the rollback target.
pub const HEALING_ROLLBACK_CHECKPOINT_ID: &str = "healing.rollback.checkpoint_id";

/// Time in milliseconds to complete the rollback operation.
pub const HEALING_ROLLBACK_RECOVERY_MS: &str = "healing.rollback.recovery_ms";

/// Strategy used to roll back the system to a known-good state.
pub const HEALING_ROLLBACK_STRATEGY: &str = "healing.rollback.strategy";

/// Values for [`HEALING_ROLLBACK_STRATEGY`].
pub mod healing_rollback_strategy {
    /// checkpoint
    pub const CHECKPOINT: &str = "checkpoint";
    /// snapshot
    pub const SNAPSHOT: &str = "snapshot";
    /// incremental
    pub const INCREMENTAL: &str = "incremental";
}

/// Whether the rollback operation completed successfully.
pub const HEALING_ROLLBACK_SUCCESS: &str = "healing.rollback.success";

/// Identifier of the root cause failure that triggered this cascade.
pub const HEALING_ROOT_CAUSE_ID: &str = "healing.root_cause.id";

/// Whether autonomous self-healing is enabled for this component.
pub const HEALING_SELF_HEALING_ENABLED: &str = "healing.self_healing.enabled";

/// Fraction of self-healing attempts that succeeded, range [0.0, 1.0].
pub const HEALING_SELF_HEALING_SUCCESS_RATE: &str = "healing.self_healing.success_rate";

/// Number of times self-healing has been triggered in the current session.
pub const HEALING_SELF_HEALING_TRIGGER_COUNT: &str = "healing.self_healing.trigger_count";

/// Total duration in milliseconds of the recovery simulation run.
pub const HEALING_SIMULATION_DURATION_MS: &str = "healing.simulation.duration_ms";

/// Number of distinct failure modes simulated in this recovery simulation.
pub const HEALING_SIMULATION_FAILURE_MODE_COUNT: &str = "healing.simulation.failure_mode_count";

/// Unique identifier for a healing recovery simulation run.
pub const HEALING_SIMULATION_ID: &str = "healing.simulation.id";

/// Fraction of simulated recovery scenarios that succeeded, range [0.0, 1.0].
pub const HEALING_SIMULATION_SUCCESS_RATE: &str = "healing.simulation.success_rate";

/// Time window in milliseconds over which surge is detected.
pub const HEALING_SURGE_DETECTION_WINDOW_MS: &str = "healing.surge.detection_window_ms";

/// Strategy applied to mitigate healing request surge.
pub const HEALING_SURGE_MITIGATION_STRATEGY: &str = "healing.surge.mitigation_strategy";

/// Values for [`HEALING_SURGE_MITIGATION_STRATEGY`].
pub mod healing_surge_mitigation_strategy {
    /// shed
    pub const SHED: &str = "shed";
    /// queue
    pub const QUEUE: &str = "queue";
    /// throttle
    pub const THROTTLE: &str = "throttle";
}

/// Multiplier applied to baseline thresholds to detect a healing surge.
pub const HEALING_SURGE_THRESHOLD_MULTIPLIER: &str = "healing.surge.threshold_multiplier";

/// Maximum time budget for the healing operation in milliseconds (WvdA deadlock freedom).
pub const HEALING_TIMEOUT_MS: &str = "healing.timeout_ms";

/// Execution time in milliseconds for the healing verification operation.
pub const HEALING_VERIFICATION_EXECUTION_TIME_MS: &str = "healing.verification.execution_time_ms";

/// Number of tests that failed during healing verification.
pub const HEALING_VERIFICATION_FAILED_TESTS: &str = "healing.verification.failed_tests";

/// Number of tests that passed during healing verification.
pub const HEALING_VERIFICATION_PASSED_TESTS: &str = "healing.verification.passed_tests";

/// Overall verification status for the healing operation.
pub const HEALING_VERIFICATION_STATUS: &str = "healing.verification.status";

/// Values for [`HEALING_VERIFICATION_STATUS`].
pub mod healing_verification_status {
    /// pass
    pub const PASS: &str = "pass";
    /// fail
    pub const FAIL: &str = "fail";
    /// inconclusive
    pub const INCONCLUSIVE: &str = "inconclusive";
}

/// Unique identifier for the warm standby replica.
pub const HEALING_WARM_STANDBY_ID: &str = "healing.warm_standby.id";

/// Activation latency of the warm standby in milliseconds — time from trigger to live.
pub const HEALING_WARM_STANDBY_LATENCY_MS: &str = "healing.warm_standby.latency_ms";

/// Readiness state of the warm standby replica.
pub const HEALING_WARM_STANDBY_READINESS: &str = "healing.warm_standby.readiness";

/// Values for [`HEALING_WARM_STANDBY_READINESS`].
pub mod healing_warm_standby_readiness {
    /// ready
    pub const READY: &str = "ready";
    /// warming
    pub const WARMING: &str = "warming";
    /// unavailable
    pub const UNAVAILABLE: &str = "unavailable";
}

/// Number of warm standby replicas available for failover.
pub const HEALING_WARM_STANDBY_REPLICA_COUNT: &str = "healing.warm_standby.replica_count";
