// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/host/registry.yaml

/// Host Attributes
/// Hardware architecture of the host.
pub const HOST_ARCH: &str = "host.arch";

/// Hostname of the system.
pub const HOST_NAME: &str = "host.name";
