// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/jtbd/registry.yaml

/// Jtbd Attributes
/// HotStuff BFT block hash — tamper-proof contract ID for blockchain validation.
pub const JTBD_CONTRACT_BLOCK_HASH: &str = "jtbd.contract.block_hash";

/// Number of consensus nodes that validated and signed the contract.
pub const JTBD_CONTRACT_CONSENSUS_NODES: &str = "jtbd.contract.consensus_nodes";

/// Total contract value in USD for closed contracts.
pub const JTBD_CONTRACT_CONTRACT_VALUE_USD: &str = "jtbd.contract.contract_value_usd";

/// Number of contracts successfully closed and signed.
pub const JTBD_CONTRACT_CONTRACTS_CLOSED: &str = "jtbd.contract.contracts_closed";

/// FIBO (Financial Industry Business Ontology) validation result — true if contract conforms to ontology.
pub const JTBD_CONTRACT_FIBO_VALIDATED: &str = "jtbd.contract.fibo_validated";

/// Legal/compliance framework enforced (e.g., "SOX", "GDPR", "HIPAA", "CCPA").
pub const JTBD_CONTRACT_FRAMEWORK: &str = "jtbd.contract.framework";

/// ISO8601 contract signature timestamp.
pub const JTBD_CONTRACT_SIGNED_AT: &str = "jtbd.contract.signed_at";

/// Number of deals advanced to next pipeline stage.
pub const JTBD_DEAL_DEALS_PROGRESSED: &str = "jtbd.deal.deals_progressed";

/// ISO8601 forecast close date for progressed deals.
pub const JTBD_DEAL_FORECAST_CLOSE_DATE: &str = "jtbd.deal.forecast_close_date";

/// Total pipeline value of progressed deals in USD.
pub const JTBD_DEAL_PIPELINE_VALUE_USD: &str = "jtbd.deal.pipeline_value_usd";

/// CRM pipeline stage before progression (e.g., "qualify", "proposal", "negotiation").
pub const JTBD_DEAL_STAGE_FROM: &str = "jtbd.deal.stage_from";

/// CRM pipeline stage after progression.
pub const JTBD_DEAL_STAGE_TO: &str = "jtbd.deal.stage_to";

/// DMAIC phase name — identifies the current phase in a DMAIC (Define/Measure/Analyze/Improve/Control) cycle.
pub const JTBD_DMAIC_PHASE_NAME: &str = "jtbd.dmaic.phase_name";

/// Values for [`JTBD_DMAIC_PHASE_NAME`].
pub mod jtbd_dmaic_phase_name {
    /// define
    pub const DEFINE: &str = "define";
    /// measure
    pub const MEASURE: &str = "measure";
    /// analyze
    pub const ANALYZE: &str = "analyze";
    /// improve
    pub const IMPROVE: &str = "improve";
    /// control
    pub const CONTROL: &str = "control";
}

/// Number of contacts evaluated in ICP qualification.
pub const JTBD_ICP_CONTACTS_EVALUATED: &str = "jtbd.icp.contacts_evaluated";

/// Number of contacts qualified as ICP targets.
pub const JTBD_ICP_CONTACTS_QUALIFIED: &str = "jtbd.icp.contacts_qualified";

/// ICP qualification rate — ratio of qualified contacts to evaluated contacts (0.0-1.0).
pub const JTBD_ICP_QUALIFICATION_RATE: &str = "jtbd.icp.qualification_rate";

/// Number of contacts enrolled in outreach sequence.
pub const JTBD_OUTREACH_CONTACTS_ENROLLED: &str = "jtbd.outreach.contacts_enrolled";

/// Total messages queued for this outreach sequence.
pub const JTBD_OUTREACH_MESSAGES_QUEUED: &str = "jtbd.outreach.messages_queued";

/// Messages remaining within daily rate limit for outreach platform.
pub const JTBD_OUTREACH_RATE_LIMIT_REMAINING: &str = "jtbd.outreach.rate_limit_remaining";

/// Identifier of the outreach sequence being executed.
pub const JTBD_OUTREACH_SEQUENCE_ID: &str = "jtbd.outreach.sequence_id";

/// Current step number within the outreach sequence (1-indexed).
pub const JTBD_OUTREACH_STEP_NUMBER: &str = "jtbd.outreach.step_number";

/// Process model type used for PI analysis (petri_net, dfg, event_log, bpmn).
pub const JTBD_PI_MODEL_TYPE: &str = "jtbd.pi.model_type";

/// Natural language query submitted to process intelligence engine.
pub const JTBD_PI_QUERY: &str = "jtbd.pi.query";

/// Number of tokens in the plain-English response from process intelligence engine.
pub const JTBD_PI_RESPONSE_TOKENS: &str = "jtbd.pi.response_tokens";

/// Java 26 retrofit complexity score (0.0-1.0) — higher indicates more complex migration.
pub const JTBD_RETROFIT_COMPLEXITY_SCORE: &str = "jtbd.retrofit.complexity_score";

/// Estimated days to complete full Java 26 retrofit.
pub const JTBD_RETROFIT_ESTIMATED_DAYS: &str = "jtbd.retrofit.estimated_days";

/// Source to target Java version gap (e.g., "17 -> 26").
pub const JTBD_RETROFIT_JAVA_VERSION_GAP: &str = "jtbd.retrofit.java_version_gap";

/// Number of Java modules analyzed during retrofit assessment.
pub const JTBD_RETROFIT_MODULES_ANALYZED: &str = "jtbd.retrofit.modules_analyzed";

/// Enumerated JTBD scenario identifier — identifies the job-to-be-done being instrumented.
pub const JTBD_SCENARIO_ID: &str = "jtbd.scenario.id";

/// Values for [`JTBD_SCENARIO_ID`].
pub mod jtbd_scenario_id {
    /// agent_decision_loop
    pub const AGENT_DECISION_LOOP: &str = "agent_decision_loop";
    /// process_discovery
    pub const PROCESS_DISCOVERY: &str = "process_discovery";
    /// compliance_check
    pub const COMPLIANCE_CHECK: &str = "compliance_check";
    /// cross_system_handoff
    pub const CROSS_SYSTEM_HANDOFF: &str = "cross_system_handoff";
    /// workspace_sync
    pub const WORKSPACE_SYNC: &str = "workspace_sync";
    /// consensus_round
    pub const CONSENSUS_ROUND: &str = "consensus_round";
    /// healing_recovery
    pub const HEALING_RECOVERY: &str = "healing_recovery";
    /// a2a_deal_lifecycle
    pub const A2A_DEAL_LIFECYCLE: &str = "a2a_deal_lifecycle";
    /// mcp_tool_execution
    pub const MCP_TOOL_EXECUTION: &str = "mcp_tool_execution";
    /// conformance_drift
    pub const CONFORMANCE_DRIFT: &str = "conformance_drift";
    /// yawl_v6_checkpoint
    pub const YAWL_V6_CHECKPOINT: &str = "yawl_v6_checkpoint";
    /// icp_qualification
    pub const ICP_QUALIFICATION: &str = "icp_qualification";
    /// retrofit_complexity_scoring
    pub const RETROFIT_COMPLEXITY_SCORING: &str = "retrofit_complexity_scoring";
    /// outreach_sequence_execution
    pub const OUTREACH_SEQUENCE_EXECUTION: &str = "outreach_sequence_execution";
    /// deal_progression
    pub const DEAL_PROGRESSION: &str = "deal_progression";
    /// contract_closure
    pub const CONTRACT_CLOSURE: &str = "contract_closure";
    /// process_intelligence_query
    pub const PROCESS_INTELLIGENCE_QUERY: &str = "process_intelligence_query";
}

/// Final outcome of the scenario step — success, failure, timeout, or fallback activated.
pub const JTBD_SCENARIO_OUTCOME: &str = "jtbd.scenario.outcome";

/// Values for [`JTBD_SCENARIO_OUTCOME`].
pub mod jtbd_scenario_outcome {
    /// success
    pub const SUCCESS: &str = "success";
    /// failure
    pub const FAILURE: &str = "failure";
    /// timeout
    pub const TIMEOUT: &str = "timeout";
    /// fallback
    pub const FALLBACK: &str = "fallback";
}

/// Human-readable name of the current scenario step (e.g., "fetch_agent_definition", "classify_failure").
pub const JTBD_SCENARIO_STEP: &str = "jtbd.scenario.step";

/// Ordinal position of this step within the scenario (1-indexed).
pub const JTBD_SCENARIO_STEP_NUM: &str = "jtbd.scenario.step_num";

/// Total number of steps expected in this scenario execution.
pub const JTBD_SCENARIO_STEP_TOTAL: &str = "jtbd.scenario.step_total";

/// ChatmanGPT system executing this JTBD scenario step.
pub const JTBD_SCENARIO_SYSTEM: &str = "jtbd.scenario.system";

/// Values for [`JTBD_SCENARIO_SYSTEM`].
pub mod jtbd_scenario_system {
    /// osa
    pub const OSA: &str = "osa";
    /// businessos
    pub const BUSINESSOS: &str = "businessos";
    /// canopy
    pub const CANOPY: &str = "canopy";
    /// pm4py_rust
    pub const PM4PY_RUST: &str = "pm4py_rust";
}

/// Wave identifier for the scenario (e.g., "wave12", "wave13"). Defaults to "wave12".
pub const JTBD_SCENARIO_WAVE: &str = "jtbd.scenario.wave";

/// Human-readable error description when scenario.outcome is failure or timeout.
pub const JTBD_SCENARIO_ERROR_REASON: &str = "jtbd.scenario.error_reason";

/// Outcome of the DMAIC phase — completed successfully, failed, or skipped.
pub const JTBD_DMAIC_PHASE_OUTCOME: &str = "jtbd.dmaic.phase_outcome";

/// Values for [`JTBD_DMAIC_PHASE_OUTCOME`].
pub mod jtbd_dmaic_phase_outcome {
    /// completed
    pub const COMPLETED: &str = "completed";
    /// failed
    pub const FAILED: &str = "failed";
    /// skipped
    pub const SKIPPED: &str = "skipped";
}

/// JTBD scenario identifier associated with this DMAIC phase transition.
pub const JTBD_DMAIC_SCENARIO_ID: &str = "jtbd.dmaic.scenario_id";

/// Identifier of the agent executing or participating in this scenario step.
pub const JTBD_SCENARIO_AGENT_ID: &str = "jtbd.scenario.agent_id";

/// Fitness score of the discovered process model against the event log (0.0-1.0). Higher values indicate better replay fitness.
pub const JTBD_SCENARIO_FITNESS: &str = "jtbd.scenario.fitness";

/// Iteration or attempt number within a repeating loop (e.g., retry attempt, consensus round iteration).
pub const JTBD_SCENARIO_ITERATION: &str = "jtbd.scenario.iteration";

/// Measured latency (elapsed time) for this scenario step in milliseconds.
pub const JTBD_SCENARIO_LATENCY_MS: &str = "jtbd.scenario.latency_ms";

/// Format of the process model produced or consumed by this scenario step (e.g., "pnml", "bpmn", "dfg").
pub const JTBD_SCENARIO_MODEL_FORMAT: &str = "jtbd.scenario.model_format";

/// Number of places in the Petri net model produced by this scenario step.
pub const JTBD_SCENARIO_PLACE_COUNT: &str = "jtbd.scenario.place_count";

/// Identifier of the Claude Code task or work item associated with this scenario step.
pub const JTBD_SCENARIO_TASK_ID: &str = "jtbd.scenario.task_id";

/// Jaeger trace ID or OpenTelemetry trace link for full observability of this scenario step.
pub const JTBD_SCENARIO_TRACE_LINK: &str = "jtbd.scenario.trace_link";

/// Number of transitions in the Petri net model produced by this scenario step.
pub const JTBD_SCENARIO_TRANSITION_COUNT: &str = "jtbd.scenario.transition_count";
