// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/llm/registry.yaml

/// Llm Attributes
/// Compression ratio for context (original_tokens / compressed_tokens).
pub const LLM_CONTEXT_COMPRESSION_RATIO: &str = "llm.context.compression.ratio";

/// Strategy used for context compression.
pub const LLM_CONTEXT_COMPRESSION_STRATEGY: &str = "llm.context.compression.strategy";

/// Values for [`LLM_CONTEXT_COMPRESSION_STRATEGY`].
pub mod llm_context_compression_strategy {
    /// summarize
    pub const SUMMARIZE: &str = "summarize";
    /// truncate
    pub const TRUNCATE: &str = "truncate";
    /// sliding_window
    pub const SLIDING_WINDOW: &str = "sliding_window";
    /// selective
    pub const SELECTIVE: &str = "selective";
}

/// Number of tokens saved through compression.
pub const LLM_CONTEXT_COMPRESSION_TOKENS_SAVED: &str = "llm.context.compression.tokens_saved";

/// The unique identifier of the LLM adapter being applied.
pub const LLM_ADAPTER_ID: &str = "llm.adapter.id";

/// The strategy for merging adapter weights with the base model (e.g., additive, weighted).
pub const LLM_ADAPTER_MERGE_STRATEGY: &str = "llm.adapter.merge_strategy";

/// The type of parameter-efficient adapter being applied to the base model.
pub const LLM_ADAPTER_TYPE: &str = "llm.adapter.type";

/// Values for [`LLM_ADAPTER_TYPE`].
pub mod llm_adapter_type {
    /// lora
    pub const LORA: &str = "lora";
    /// prefix
    pub const PREFIX: &str = "prefix";
    /// prompt_tuning
    pub const PROMPT_TUNING: &str = "prompt_tuning";
    /// adapter
    pub const ADAPTER: &str = "adapter";
    /// ia3
    pub const IA3: &str = "ia3";
}

/// Average latency per request in the batch in milliseconds.
pub const LLM_BATCH_AVG_LATENCY_MS: &str = "llm.batch.avg_latency_ms";

/// Fraction of batch requests that completed successfully, range [0.0, 1.0].
pub const LLM_BATCH_COMPLETION_RATE: &str = "llm.batch.completion_rate";

/// Unique identifier for the LLM batch inference job.
pub const LLM_BATCH_JOB_ID: &str = "llm.batch.job_id";

/// Priority level of the batch inference job.
pub const LLM_BATCH_PRIORITY: &str = "llm.batch.priority";

/// Values for [`LLM_BATCH_PRIORITY`].
pub mod llm_batch_priority {
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// Number of requests in the batch inference job.
pub const LLM_BATCH_REQUEST_COUNT: &str = "llm.batch.request_count";

/// Reason the cached LLM response was evicted.
pub const LLM_CACHE_EVICTION_REASON: &str = "llm.cache.eviction_reason";

/// Values for [`LLM_CACHE_EVICTION_REASON`].
pub mod llm_cache_eviction_reason {
    /// ttl_expired
    pub const TTL_EXPIRED: &str = "ttl_expired";
    /// capacity
    pub const CAPACITY: &str = "capacity";
    /// invalidated
    pub const INVALIDATED: &str = "invalidated";
}

/// Whether the LLM response was served from a semantic cache.
pub const LLM_CACHE_HIT: &str = "llm.cache.hit";

/// Hash of the cache key used to identify the cached LLM response.
pub const LLM_CACHE_KEY_HASH: &str = "llm.cache.key_hash";

/// Time-to-live for the cached LLM response in milliseconds.
pub const LLM_CACHE_TTL_MS: &str = "llm.cache.ttl_ms";

/// Whether chain-of-thought prompting was used for this request.
pub const LLM_CHAIN_OF_THOUGHT_ENABLED: &str = "llm.chain_of_thought.enabled";

/// Number of chain-of-thought reasoning steps in this LLM response.
pub const LLM_CHAIN_OF_THOUGHT_STEPS: &str = "llm.chain_of_thought.steps";

/// Maximum token limit for the LLM context window.
pub const LLM_CONTEXT_MAX_TOKENS: &str = "llm.context.max_tokens";

/// Number of messages in the conversation context sent to the LLM.
pub const LLM_CONTEXT_MESSAGES_COUNT: &str = "llm.context.messages_count";

/// Number of times context overflow was handled in the session.
pub const LLM_CONTEXT_OVERFLOW_COUNT: &str = "llm.context.overflow_count";

/// Strategy used when context exceeds max_tokens.
pub const LLM_CONTEXT_OVERFLOW_STRATEGY: &str = "llm.context.overflow_strategy";

/// Values for [`LLM_CONTEXT_OVERFLOW_STRATEGY`].
pub mod llm_context_overflow_strategy {
    /// truncate
    pub const TRUNCATE: &str = "truncate";
    /// summarize
    pub const SUMMARIZE: &str = "summarize";
    /// compress
    pub const COMPRESS: &str = "compress";
    /// reject
    pub const REJECT: &str = "reject";
    /// sliding_window
    pub const SLIDING_WINDOW: &str = "sliding_window";
}

/// Context window utilization ratio [0.0, 1.0].
pub const LLM_CONTEXT_UTILIZATION: &str = "llm.context.utilization";

/// Cost of input tokens for this LLM request in USD.
pub const LLM_COST_INPUT: &str = "llm.cost.input";

/// Cost of output tokens for this LLM request in USD.
pub const LLM_COST_OUTPUT: &str = "llm.cost.output";

/// Total cost of the LLM request in USD (input + output combined).
pub const LLM_COST_TOTAL: &str = "llm.cost.total";

/// Compression ratio of student vs teacher model size [0.0, 1.0].
pub const LLM_DISTILLATION_COMPRESSION_RATIO: &str = "llm.distillation.compression_ratio";

/// KL divergence loss between teacher and student distributions.
pub const LLM_DISTILLATION_KL_DIVERGENCE: &str = "llm.distillation.kl_divergence";

/// Identifier of the student model being trained.
pub const LLM_DISTILLATION_STUDENT_MODEL: &str = "llm.distillation.student_model";

/// Identifier of the teacher model providing soft targets.
pub const LLM_DISTILLATION_TEACHER_MODEL: &str = "llm.distillation.teacher_model";

/// Dimensionality of the generated embedding vectors.
pub const LLM_EMBEDDING_DIMENSIONS: &str = "llm.embedding.dimensions";

/// The embedding model used to generate vector representations.
pub const LLM_EMBEDDING_MODEL: &str = "llm.embedding.model";

/// Cosine similarity threshold above which embeddings are considered semantically similar.
pub const LLM_EMBEDDING_SIMILARITY_THRESHOLD: &str = "llm.embedding.similarity_threshold";

/// Whether the evaluation score meets or exceeds the quality threshold.
pub const LLM_EVALUATION_PASSES_THRESHOLD: &str = "llm.evaluation.passes_threshold";

/// Name of the evaluation rubric used to score the response.
pub const LLM_EVALUATION_RUBRIC: &str = "llm.evaluation.rubric";

/// Quality evaluation score for the LLM response, range [0.0, 1.0].
pub const LLM_EVALUATION_SCORE: &str = "llm.evaluation.score";

/// User feedback signal for the LLM response.
pub const LLM_FEEDBACK_THUMBS: &str = "llm.feedback.thumbs";

/// Values for [`LLM_FEEDBACK_THUMBS`].
pub mod llm_feedback_thumbs {
    /// up
    pub const UP: &str = "up";
    /// down
    pub const DOWN: &str = "down";
    /// neutral
    pub const NEUTRAL: &str = "neutral";
}

/// Number of few-shot examples included in the prompt.
pub const LLM_FEW_SHOT_EXAMPLE_COUNT: &str = "llm.few_shot.example_count";

/// Time in milliseconds to retrieve and rank few-shot examples.
pub const LLM_FEW_SHOT_RETRIEVAL_MS: &str = "llm.few_shot.retrieval_ms";

/// Strategy used to select few-shot examples.
pub const LLM_FEW_SHOT_SELECTION_STRATEGY: &str = "llm.few_shot.selection_strategy";

/// Values for [`LLM_FEW_SHOT_SELECTION_STRATEGY`].
pub mod llm_few_shot_selection_strategy {
    /// random
    pub const RANDOM: &str = "random";
    /// similarity
    pub const SIMILARITY: &str = "similarity";
    /// diverse
    pub const DIVERSE: &str = "diverse";
    /// stratified
    pub const STRATIFIED: &str = "stratified";
}

/// The base model being fine-tuned.
pub const LLM_FINETUNE_BASE_MODEL: &str = "llm.finetune.base_model";

/// Number of training examples in the fine-tuning dataset.
pub const LLM_FINETUNE_DATASET_SIZE: &str = "llm.finetune.dataset_size";

/// Unique identifier for the fine-tuning job.
pub const LLM_FINETUNE_JOB_ID: &str = "llm.finetune.job_id";

/// Final training loss value at the end of fine-tuning.
pub const LLM_FINETUNE_LOSS_FINAL: &str = "llm.finetune.loss_final";

/// Total number of training steps in the fine-tuning job.
pub const LLM_FINETUNE_TRAINING_STEPS: &str = "llm.finetune.training_steps";

/// Time in milliseconds from LLM function call generation to handler response.
pub const LLM_FUNCTION_CALL_LATENCY_MS: &str = "llm.function_call.latency_ms";

/// Name of the function being invoked through the LLM function calling interface.
pub const LLM_FUNCTION_CALL_NAME: &str = "llm.function_call.name";

/// Strategy used to route function calls from the LLM response to handlers.
pub const LLM_FUNCTION_CALL_ROUTING_STRATEGY: &str = "llm.function_call.routing_strategy";

/// Values for [`LLM_FUNCTION_CALL_ROUTING_STRATEGY`].
pub mod llm_function_call_routing_strategy {
    /// direct
    pub const DIRECT: &str = "direct";
    /// fallback
    pub const FALLBACK: &str = "fallback";
    /// parallel
    pub const PARALLEL: &str = "parallel";
    /// sequential
    pub const SEQUENTIAL: &str = "sequential";
}

/// Whether any guardrail was triggered for this LLM request or response.
pub const LLM_GUARDRAIL_TRIGGERED: &str = "llm.guardrail.triggered";

/// The type of guardrail that was evaluated or triggered.
pub const LLM_GUARDRAIL_TYPE: &str = "llm.guardrail.type";

/// Values for [`LLM_GUARDRAIL_TYPE`].
pub mod llm_guardrail_type {
    /// content_filter
    pub const CONTENT_FILTER: &str = "content_filter";
    /// pii_detection
    pub const PII_DETECTION: &str = "pii_detection";
    /// prompt_injection
    pub const PROMPT_INJECTION: &str = "prompt_injection";
    /// hallucination_check
    pub const HALLUCINATION_CHECK: &str = "hallucination_check";
    /// rate_limit
    pub const RATE_LIMIT: &str = "rate_limit";
}

/// Total end-to-end latency of the LLM inference call in milliseconds.
pub const LLM_LATENCY_MS: &str = "llm.latency_ms";

/// Scaling factor for LoRA weight updates (alpha/rank determines effective learning rate).
pub const LLM_LORA_ALPHA: &str = "llm.lora.alpha";

/// Identifier of the base model being adapted with LoRA.
pub const LLM_LORA_BASE_MODEL: &str = "llm.lora.base_model";

/// Rank of the LoRA decomposition matrices (controls adaptation capacity).
pub const LLM_LORA_RANK: &str = "llm.lora.rank";

/// Comma-separated list of model modules targeted by LoRA adaptation.
pub const LLM_LORA_TARGET_MODULES: &str = "llm.lora.target_modules";

/// Number of trainable parameters added by LoRA (much smaller than full fine-tune).
pub const LLM_LORA_TRAINABLE_PARAMS: &str = "llm.lora.trainable_params";

/// The model identifier used for the LLM inference call.
pub const LLM_MODEL: &str = "llm.model";

/// Version identifier of the LLM model used.
pub const LLM_MODEL_VERSION: &str = "llm.model.version";

/// The model family/provider for this LLM inference (e.g., gpt, claude, gemini).
pub const LLM_MODEL_FAMILY: &str = "llm.model_family";

/// Values for [`LLM_MODEL_FAMILY`].
pub mod llm_model_family {
    /// gpt
    pub const GPT: &str = "gpt";
    /// claude
    pub const CLAUDE: &str = "claude";
    /// gemini
    pub const GEMINI: &str = "gemini";
    /// llama
    pub const LLAMA: &str = "llama";
    /// mistral
    pub const MISTRAL: &str = "mistral";
}

/// Total size in bytes of all non-text multi-modal inputs (images, audio, etc.).
pub const LLM_MULTIMODAL_INPUT_SIZE_BYTES: &str = "llm.multimodal.input_size_bytes";

/// Primary input modality type for a multi-modal LLM request.
pub const LLM_MULTIMODAL_INPUT_TYPE: &str = "llm.multimodal.input_type";

/// Values for [`LLM_MULTIMODAL_INPUT_TYPE`].
pub mod llm_multimodal_input_type {
    /// text
    pub const TEXT: &str = "text";
    /// image
    pub const IMAGE: &str = "image";
    /// audio
    pub const AUDIO: &str = "audio";
    /// video
    pub const VIDEO: &str = "video";
    /// document
    pub const DOCUMENT: &str = "document";
}

/// Number of distinct modalities present in the multi-modal LLM input.
pub const LLM_MULTIMODAL_MODALITY_COUNT: &str = "llm.multimodal.modality_count";

/// Duration in milliseconds spent processing multi-modal inputs before inference.
pub const LLM_MULTIMODAL_PROCESSING_MS: &str = "llm.multimodal.processing_ms";

/// Token count of the fully rendered prompt after variable substitution.
pub const LLM_PROMPT_RENDERED_TOKENS: &str = "llm.prompt.rendered_tokens";

/// Identifier of the prompt template used to generate the LLM request.
pub const LLM_PROMPT_TEMPLATE_ID: &str = "llm.prompt.template_id";

/// Number of template variables substituted in the rendered prompt.
pub const LLM_PROMPT_VARIABLE_COUNT: &str = "llm.prompt.variable_count";

/// Version of the prompt template.
pub const LLM_PROMPT_VERSION: &str = "llm.prompt.version";

/// The LLM provider name.
pub const LLM_PROVIDER: &str = "llm.provider";

/// Total token count of the retrieved context injected into the LLM prompt.
pub const LLM_RAG_CONTEXT_WINDOW_TOKENS: &str = "llm.rag.context_window_tokens";

/// Number of documents retrieved (top-k) in the RAG retrieval step.
pub const LLM_RAG_RETRIEVAL_K: &str = "llm.rag.retrieval_k";

/// Minimum similarity score [0.0, 1.0] for retrieved documents to be included.
pub const LLM_RAG_SIMILARITY_THRESHOLD: &str = "llm.rag.similarity_threshold";

/// Unique identifier for this LLM API request, from the provider response.
pub const LLM_REQUEST_ID: &str = "llm.request.id";

/// Number of retry attempts for this LLM request (e.g., due to rate limits or errors).
pub const LLM_RETRY_COUNT: &str = "llm.retry.count";

/// Safety score for this LLM response, range [0.0, 1.0]. Lower = less safe.
pub const LLM_SAFETY_SCORE: &str = "llm.safety.score";

/// Maximum number of tokens to generate in the LLM response.
pub const LLM_SAMPLING_MAX_TOKENS: &str = "llm.sampling.max_tokens";

/// Random seed for deterministic LLM sampling. -1 means non-deterministic.
pub const LLM_SAMPLING_SEED: &str = "llm.sampling.seed";

/// LLM sampling temperature controlling output randomness, range [0.0, 2.0].
pub const LLM_SAMPLING_TEMPERATURE: &str = "llm.sampling.temperature";

/// Nucleus sampling probability threshold, range [0.0, 1.0].
pub const LLM_SAMPLING_TOP_P: &str = "llm.sampling.top_p";

/// The reason the LLM stopped generating tokens.
pub const LLM_STOP_REASON: &str = "llm.stop_reason";

/// Values for [`LLM_STOP_REASON`].
pub mod llm_stop_reason {
    /// max_tokens
    pub const MAX_TOKENS: &str = "max_tokens";
    /// stop_sequence
    pub const STOP_SEQUENCE: &str = "stop_sequence";
    /// length
    pub const LENGTH: &str = "length";
    /// end_turn
    pub const END_TURN: &str = "end_turn";
    /// tool_use
    pub const TOOL_USE: &str = "tool_use";
}

/// Number of streaming chunks received for a streaming LLM response.
pub const LLM_STREAMING_CHUNK_COUNT: &str = "llm.streaming.chunk_count";

/// Whether the streaming response completed successfully without interruption.
pub const LLM_STREAMING_COMPLETE: &str = "llm.streaming.complete";

/// Time to first token in milliseconds (TTFT) for streaming responses.
pub const LLM_STREAMING_FIRST_TOKEN_MS: &str = "llm.streaming.first_token_ms";

/// Average token generation rate for streaming responses.
pub const LLM_STREAMING_TOKENS_PER_SECOND: &str = "llm.streaming.tokens_per_second";

/// Output format enforced by the structured output schema.
pub const LLM_STRUCTURED_OUTPUT_FORMAT: &str = "llm.structured_output.format";

/// Values for [`LLM_STRUCTURED_OUTPUT_FORMAT`].
pub mod llm_structured_output_format {
    /// json
    pub const JSON: &str = "json";
    /// xml
    pub const XML: &str = "xml";
    /// yaml
    pub const YAML: &str = "yaml";
    /// markdown
    pub const MARKDOWN: &str = "markdown";
}

/// Identifier of the JSON schema used to validate the structured output.
pub const LLM_STRUCTURED_OUTPUT_SCHEMA_ID: &str = "llm.structured_output.schema_id";

/// Time in milliseconds to validate the LLM output against the structured schema.
pub const LLM_STRUCTURED_OUTPUT_VALIDATION_MS: &str = "llm.structured_output.validation_ms";

/// Sampling temperature used for the LLM inference (0.0 = deterministic).
pub const LLM_TEMPERATURE: &str = "llm.temperature";

/// Remaining token budget for the current LLM session or context window.
pub const LLM_TOKEN_BUDGET_REMAINING: &str = "llm.token.budget_remaining";

/// Number of tokens in the LLM completion/output response.
pub const LLM_TOKEN_COMPLETION_COUNT: &str = "llm.token.completion_count";

/// Number of input (prompt) tokens sent to the LLM.
pub const LLM_TOKEN_INPUT: &str = "llm.token.input";

/// Number of output (completion) tokens received from the LLM.
pub const LLM_TOKEN_OUTPUT: &str = "llm.token.output";

/// Number of tokens in the prompt/input sent to the LLM.
pub const LLM_TOKEN_PROMPT_COUNT: &str = "llm.token.prompt_count";

/// Number of tool calls made during this LLM inference.
pub const LLM_TOOL_CALL_COUNT: &str = "llm.tool.call_count";

/// Number of orchestration steps executed in the LLM tool pipeline.
pub const LLM_TOOL_ORCHESTRATION_STEP_COUNT: &str = "llm.tool.orchestration.step_count";

/// Strategy used to orchestrate multiple LLM tool calls.
pub const LLM_TOOL_ORCHESTRATION_STRATEGY: &str = "llm.tool.orchestration.strategy";

/// Values for [`LLM_TOOL_ORCHESTRATION_STRATEGY`].
pub mod llm_tool_orchestration_strategy {
    /// sequential
    pub const SEQUENTIAL: &str = "sequential";
    /// parallel
    pub const PARALLEL: &str = "parallel";
    /// conditional
    pub const CONDITIONAL: &str = "conditional";
    /// retry
    pub const RETRY: &str = "retry";
}

/// Fraction of orchestration steps that completed successfully [0.0, 1.0].
pub const LLM_TOOL_ORCHESTRATION_SUCCESS_RATE: &str = "llm.tool.orchestration.success_rate";

/// Duration in milliseconds of the LLM response validation.
pub const LLM_VALIDATION_DURATION_MS: &str = "llm.validation.duration_ms";

/// Category of validation error encountered when validating the LLM response.
pub const LLM_VALIDATION_ERROR_TYPE: &str = "llm.validation.error_type";

/// Values for [`LLM_VALIDATION_ERROR_TYPE`].
pub mod llm_validation_error_type {
    /// format
    pub const FORMAT: &str = "format";
    /// type
    pub const TYPE_MISMATCH: &str = "type";
    /// required
    pub const REQUIRED_FIELD: &str = "required";
    /// enum
    pub const ENUM_VIOLATION: &str = "enum";
}

/// Fraction of validation checks that passed, range [0.0, 1.0].
pub const LLM_VALIDATION_PASS_RATE: &str = "llm.validation.pass_rate";

/// Identifier of the JSON schema used to validate the LLM response.
pub const LLM_VALIDATION_SCHEMA_ID: &str = "llm.validation.schema_id";
