// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/mcp/registry.yaml

/// Mcp Attributes
/// Number of currently active connections in the pool.
pub const MCP_CONNECTION_POOL_ACTIVE_COUNT: &str = "mcp.connection.pool.active_count";

/// Number of idle connections available in the pool.
pub const MCP_CONNECTION_POOL_IDLE_COUNT: &str = "mcp.connection.pool.idle_count";

/// Total size (max connections) of the MCP connection pool.
pub const MCP_CONNECTION_POOL_SIZE: &str = "mcp.connection.pool.size";

/// Time in milliseconds the request waited to acquire a connection.
pub const MCP_CONNECTION_POOL_WAIT_MS: &str = "mcp.connection.pool.wait_ms";

/// Unique identifier for this MCP client-server connection.
pub const MCP_CONNECTION_ID: &str = "mcp.connection.id";

/// Transport protocol used for this MCP connection.
pub const MCP_CONNECTION_TRANSPORT: &str = "mcp.connection.transport";

/// Values for [`MCP_CONNECTION_TRANSPORT`].
pub mod mcp_connection_transport {
    /// stdio
    pub const STDIO: &str = "stdio";
    /// http
    pub const HTTP: &str = "http";
    /// sse
    pub const SSE: &str = "sse";
    /// streamable-http
    pub const STREAMABLE_HTTP: &str = "streamable-http";
}

/// Transport protocol used for MCP communication.
pub const MCP_PROTOCOL: &str = "mcp.protocol";

/// Values for [`MCP_PROTOCOL`].
pub mod mcp_protocol {
    /// stdio
    pub const STDIO: &str = "stdio";
    /// http
    pub const HTTP: &str = "http";
    /// sse
    pub const SSE: &str = "sse";
    /// streamable-http
    pub const STREAMABLE_HTTP: &str = "streamable-http";
}

/// MCP protocol version negotiated for this connection.
pub const MCP_PROTOCOL_VERSION: &str = "mcp.protocol.version";

/// Number of active MCP servers in the registry.
pub const MCP_REGISTRY_SERVER_COUNT: &str = "mcp.registry.server_count";

/// Number of tools registered with this MCP server.
pub const MCP_REGISTRY_TOOL_COUNT: &str = "mcp.registry.tool_count";

/// MIME type of the MCP resource content.
pub const MCP_RESOURCE_MIME_TYPE: &str = "mcp.resource.mime_type";

/// Size of the MCP resource content in bytes.
pub const MCP_RESOURCE_SIZE_BYTES: &str = "mcp.resource.size_bytes";

/// URI identifying the MCP resource being accessed.
pub const MCP_RESOURCE_URI: &str = "mcp.resource.uri";

/// Duration of the health check in milliseconds.
pub const MCP_SERVER_HEALTH_CHECK_DURATION_MS: &str = "mcp.server.health.check_duration_ms";

/// Health status of the MCP server.
pub const MCP_SERVER_HEALTH_STATUS: &str = "mcp.server.health.status";

/// Values for [`MCP_SERVER_HEALTH_STATUS`].
pub mod mcp_server_health_status {
    /// healthy
    pub const HEALTHY: &str = "healthy";
    /// degraded
    pub const DEGRADED: &str = "degraded";
    /// unhealthy
    pub const UNHEALTHY: &str = "unhealthy";
    /// unknown
    pub const UNKNOWN: &str = "unknown";
}

/// Number of tools registered on the MCP server.
pub const MCP_SERVER_HEALTH_TOOL_COUNT: &str = "mcp.server.health.tool_count";

/// Uptime of the MCP server in milliseconds.
pub const MCP_SERVER_HEALTH_UPTIME_MS: &str = "mcp.server.health.uptime_ms";

/// Error rate of the MCP server as a fraction [0.0, 1.0].
pub const MCP_SERVER_METRICS_ERROR_RATE: &str = "mcp.server.metrics.error_rate";

/// 99th percentile latency in milliseconds for MCP server request handling.
pub const MCP_SERVER_METRICS_P99_LATENCY_MS: &str = "mcp.server.metrics.p99_latency_ms";

/// Total number of requests received by the MCP server.
pub const MCP_SERVER_METRICS_REQUEST_COUNT: &str = "mcp.server.metrics.request_count";

/// Name of the MCP server hosting the tool.
pub const MCP_SERVER_NAME: &str = "mcp.server.name";

/// Session identifier for the MCP client-server connection.
pub const MCP_SESSION_ID: &str = "mcp.session.id";

/// Average latency (ms) for MCP tool invocations in the reporting window.
pub const MCP_TOOL_ANALYTICS_AVG_LATENCY_MS: &str = "mcp.tool.analytics.avg_latency_ms";

/// Total number of calls made to this MCP tool in the current reporting window.
pub const MCP_TOOL_ANALYTICS_CALL_COUNT: &str = "mcp.tool.analytics.call_count";

/// Error rate for MCP tool invocations in the reporting window, range [0.0, 1.0].
pub const MCP_TOOL_ANALYTICS_ERROR_RATE: &str = "mcp.tool.analytics.error_rate";

/// Whether the tool response was served from cache.
pub const MCP_TOOL_CACHE_HIT: &str = "mcp.tool.cache.hit";

/// Cache key used for tool response lookup.
pub const MCP_TOOL_CACHE_KEY: &str = "mcp.tool.cache.key";

/// Cache time-to-live in milliseconds.
pub const MCP_TOOL_CACHE_TTL_MS: &str = "mcp.tool.cache.ttl_ms";

/// Number of steps completed successfully in the composition chain.
pub const MCP_TOOL_COMPOSITION_COMPLETED_STEPS: &str = "mcp.tool.composition.completed_steps";

/// Number of tool steps in the composition chain.
pub const MCP_TOOL_COMPOSITION_STEP_COUNT: &str = "mcp.tool.composition.step_count";

/// The composition strategy for chaining multiple MCP tools together.
pub const MCP_TOOL_COMPOSITION_STRATEGY: &str = "mcp.tool.composition.strategy";

/// Values for [`MCP_TOOL_COMPOSITION_STRATEGY`].
pub mod mcp_tool_composition_strategy {
    /// sequential
    pub const SEQUENTIAL: &str = "sequential";
    /// parallel
    pub const PARALLEL: &str = "parallel";
    /// fallback
    pub const FALLBACK: &str = "fallback";
    /// pipeline
    pub const PIPELINE: &str = "pipeline";
}

/// Total timeout for the entire composition chain in milliseconds.
pub const MCP_TOOL_COMPOSITION_TIMEOUT_MS: &str = "mcp.tool.composition.timeout_ms";

/// Unique identifier for a composed tool pipeline.
pub const MCP_TOOL_COMPOSITION_ID: &str = "mcp.tool.composition_id";

/// Total latency in milliseconds for the composed tool pipeline execution.
pub const MCP_TOOL_COMPOSITION_LATENCY_MS: &str = "mcp.tool.composition_latency_ms";

/// Whether the MCP tool is deprecated.
pub const MCP_TOOL_DEPRECATED: &str = "mcp.tool.deprecated";

/// The deprecation policy applied to the tool.
pub const MCP_TOOL_DEPRECATION_POLICY: &str = "mcp.tool.deprecation.policy";

/// Values for [`MCP_TOOL_DEPRECATION_POLICY`].
pub mod mcp_tool_deprecation_policy {
    /// immediate
    pub const IMMEDIATE: &str = "immediate";
    /// grace_period
    pub const GRACE_PERIOD: &str = "grace_period";
    /// warn_only
    pub const WARN_ONLY: &str = "warn_only";
}

/// Reason the tool was deprecated (if applicable).
pub const MCP_TOOL_DEPRECATION_REASON: &str = "mcp.tool.deprecation.reason";

/// The name of the replacement tool that supersedes the deprecated tool.
pub const MCP_TOOL_DEPRECATION_REPLACEMENT_TOOL: &str = "mcp.tool.deprecation.replacement_tool";

/// Unix timestamp (ms) when the deprecated tool will be removed.
pub const MCP_TOOL_DEPRECATION_SUNSET_DATE_MS: &str = "mcp.tool.deprecation.sunset_date_ms";

/// Size in bytes of the tool input payload.
pub const MCP_TOOL_INPUT_SIZE: &str = "mcp.tool.input_size";

/// Name of the MCP tool being invoked.
pub const MCP_TOOL_NAME: &str = "mcp.tool.name";

/// Size in bytes of the tool output payload.
pub const MCP_TOOL_OUTPUT_SIZE: &str = "mcp.tool.output_size";

/// Number of results returned by the MCP tool.
pub const MCP_TOOL_RESULT_COUNT: &str = "mcp.tool.result_count";

/// Number of retry attempts for a tool execution (0 = first attempt succeeded).
pub const MCP_TOOL_RETRY_COUNT: &str = "mcp.tool.retry_count";

/// Hash of the tool's input/output JSON schema (for schema drift detection).
pub const MCP_TOOL_SCHEMA_HASH: &str = "mcp.tool.schema_hash";

/// Configured timeout in milliseconds for tool execution (Armstrong budget constraint).
pub const MCP_TOOL_TIMEOUT_MS: &str = "mcp.tool.timeout_ms";

/// Version of the MCP tool being invoked.
pub const MCP_TOOL_VERSION: &str = "mcp.tool.version";

/// Number of transport-level errors since last reset.
pub const MCP_TRANSPORT_ERROR_COUNT: &str = "mcp.transport.error_count";

/// Latency of the MCP transport connection in milliseconds.
pub const MCP_TRANSPORT_LATENCY_MS: &str = "mcp.transport.latency_ms";

/// Number of reconnection attempts for the MCP transport.
pub const MCP_TRANSPORT_RECONNECT_COUNT: &str = "mcp.transport.reconnect_count";

/// Transport protocol used by the MCP connection.
pub const MCP_TRANSPORT_TYPE: &str = "mcp.transport.type";

/// Values for [`MCP_TRANSPORT_TYPE`].
pub mod mcp_transport_type {
    /// stdio
    pub const STDIO: &str = "stdio";
    /// http
    pub const HTTP: &str = "http";
    /// sse
    pub const SSE: &str = "sse";
    /// websocket
    pub const WEBSOCKET: &str = "websocket";
    /// streamable-http
    pub const STREAMABLE_HTTP: &str = "streamable-http";
}
