// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/ocpm/registry.yaml

/// Ocpm Attributes
/// Overall conformance fitness score [0.0-1.0]
pub const OCPM_CONFORMANCE_FITNESS: &str = "ocpm.conformance.fitness";

/// Total number of directly-follows edges in the OCDFG
pub const OCPM_DFG_EDGE_COUNT: &str = "ocpm.dfg.edge.count";

/// Object type for which the DFG was computed
pub const OCPM_DFG_OBJECT_TYPE: &str = "ocpm.dfg.object_type";

/// Whether the LLM answer was grounded in real OCEL process data (vs offline fallback)
pub const OCPM_LLM_GROUNDED: &str = "ocpm.llm.grounded";

/// Number of bottleneck edges detected
pub const OCPM_PERFORMANCE_BOTTLENECK_COUNT: &str = "ocpm.performance.bottleneck.count";

/// Object type for which performance was computed
pub const OCPM_PERFORMANCE_OBJECT_TYPE: &str = "ocpm.performance.object_type";

/// Mean end-to-end throughput time in seconds for this object type
pub const OCPM_PERFORMANCE_THROUGHPUT_MEAN_SECS: &str = "ocpm.performance.throughput_mean_secs";

/// Type of conformance deviation detected
pub const OCPM_CONFORMANCE_DEVIATION_TYPE: &str = "ocpm.conformance.deviation_type";

/// Values for [`OCPM_CONFORMANCE_DEVIATION_TYPE`].
pub mod ocpm_conformance_deviation_type {
    /// Token replay found missing tokens (activity executed without prerequisite)
    pub const MISSING_TOKEN: &str = "missing_token";
    /// Token replay found remaining tokens after final state (incomplete execution)
    pub const REMAINING_TOKEN: &str = "remaining_token";
    /// Required activity was absent from the object lifecycle
    pub const MISSING_ACTIVITY: &str = "missing_activity";
}

/// Object type for per-type fitness score
pub const OCPM_CONFORMANCE_OBJECT_TYPE: &str = "ocpm.conformance.object_type";

/// Activity name associated with the OCEL event
pub const OCPM_EVENT_ACTIVITY: &str = "ocpm.event.activity";

/// Number of events in the OCEL log processed by this operation
pub const OCPM_EVENT_COUNT: &str = "ocpm.event.count";

/// Number of tokens in the OCEL context injected as system message
pub const OCPM_LLM_CONTEXT_TOKENS: &str = "ocpm.llm.context_tokens";

/// LLM model used to answer the process intelligence query
pub const OCPM_LLM_MODEL: &str = "ocpm.llm.model";

/// Unique identifier of the object instance
pub const OCPM_OBJECT_ID: &str = "ocpm.object_id";

/// Object type name in the OCEL 2.0 log (e.g. 'order', 'item', 'invoice')
pub const OCPM_OBJECT_TYPE: &str = "ocpm.object_type";

/// Number of distinct object types in the OCEL log
pub const OCPM_OBJECT_TYPE_COUNT: &str = "ocpm.object_type.count";
