// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/osa/registry.yaml

/// Osa Attributes
/// Wall-clock duration in milliseconds for the provider call.
pub const OSA_DURATION_MS: &str = "osa.duration_ms";

/// Model identifier used for this chat completion.
pub const OSA_MODEL: &str = "osa.model";

/// LLM provider used for this chat completion.
pub const OSA_PROVIDER: &str = "osa.provider";

/// Values for [`OSA_PROVIDER`].
pub mod osa_provider {
    /// anthropic
    pub const ANTHROPIC: &str = "anthropic";
    /// ollama
    pub const OLLAMA: &str = "ollama";
    /// cohere
    pub const COHERE: &str = "cohere";
    /// google
    pub const GOOGLE: &str = "google";
    /// replicate
    pub const REPLICATE: &str = "replicate";
    /// openai
    pub const OPENAI: &str = "openai";
}
