// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/other/registry.yaml

/// Other Attributes
/// The diagnosis mode or classification strategy used (e.g., deterministic, probabilistic).
pub const DIAGNOSIS_MODE: &str = "diagnosis_mode";

/// Execution time in milliseconds for healing operation.
pub const EXECUTION_TIME_MS: &str = "execution_time_ms";

/// Number of tests that failed.
pub const FAILED_TESTS: &str = "failed_tests";

/// Outcome of the healing fix operation.
pub const FIX_RESULT: &str = "fix_result";

/// Values for [`FIX_RESULT`].
pub mod fix_result {
    /// success
    pub const SUCCESS: &str = "success";
    /// partial
    pub const PARTIAL: &str = "partial";
    /// failed
    pub const FAILED: &str = "failed";
}

/// Node identifier or name.
pub const NODE: &str = "node";

/// Number of tests that passed.
pub const PASSED_TESTS: &str = "passed_tests";

/// Consensus round number.
pub const ROUND_NUM: &str = "round_num";

/// Timestamp in milliseconds since Unix epoch.
pub const TIMESTAMP: &str = "timestamp";

/// Tool identifier or name.
pub const TOOL: &str = "tool";

/// Verification status.
pub const VERIFICATION_STATUS: &str = "verification_status";

/// Values for [`VERIFICATION_STATUS`].
pub mod verification_status {
    /// pass
    pub const PASS: &str = "pass";
    /// fail
    pub const FAIL: &str = "fail";
}

/// Version identifier or string.
pub const VERSION: &str = "version";
