// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/process/registry.yaml

/// Process Attributes
/// Name of the process activity (event class) from the XES log.
pub const PROCESS_MINING_ACTIVITY: &str = "process.mining.activity";

/// Relative frequency of this activity in the process log [0.0, 1.0].
pub const PROCESS_MINING_ACTIVITY_FREQUENCY: &str = "process.mining.activity.frequency";

/// Waiting time before an activity was executed in milliseconds.
pub const PROCESS_MINING_ACTIVITY_WAITING_MS: &str = "process.mining.activity.waiting_ms";

/// Process discovery algorithm used.
pub const PROCESS_MINING_ALGORITHM: &str = "process.mining.algorithm";

/// Values for [`PROCESS_MINING_ALGORITHM`].
pub mod process_mining_algorithm {
    /// alpha_miner
    pub const ALPHA_MINER: &str = "alpha_miner";
    /// inductive_miner
    pub const INDUCTIVE_MINER: &str = "inductive_miner";
    /// heuristics_miner
    pub const HEURISTICS_MINER: &str = "heuristics_miner";
    /// heuristic_miner
    pub const HEURISTIC_MINER: &str = "heuristic_miner";
    /// directly_follows
    pub const DIRECTLY_FOLLOWS: &str = "directly_follows";
}

/// Total alignment cost for token-based or alignment-based conformance checking. Lower is better.
pub const PROCESS_MINING_ALIGNMENT_COST: &str = "process.mining.alignment.cost";

/// Change in fitness score compared to the previous alignment computation.
pub const PROCESS_MINING_ALIGNMENT_FITNESS_DELTA: &str = "process.mining.alignment.fitness_delta";

/// Total number of moves (log moves + model moves) in the computed alignment.
pub const PROCESS_MINING_ALIGNMENT_MOVE_COUNT: &str = "process.mining.alignment.move_count";

/// Length of the optimal synchronization path found by the alignment algorithm.
pub const PROCESS_MINING_ALIGNMENT_OPTIMAL_PATH_LENGTH: &str =
    "process.mining.alignment.optimal_path_length";

/// Anomaly score for the detected process deviation [0.0, 1.0].
pub const PROCESS_MINING_ANOMALY_SCORE: &str = "process.mining.anomaly.score";

/// Name of the activity identified as a bottleneck in the process model.
pub const PROCESS_MINING_BOTTLENECK_ACTIVITY: &str = "process.mining.bottleneck.activity";

/// Estimated total time impact in milliseconds caused by this bottleneck across all cases.
pub const PROCESS_MINING_BOTTLENECK_IMPACT_MS: &str = "process.mining.bottleneck.impact_ms";

/// Ordinal rank of the bottleneck among all detected bottlenecks (1 = most severe).
pub const PROCESS_MINING_BOTTLENECK_RANK: &str = "process.mining.bottleneck.rank";

/// Composite bottleneck severity score for an activity, range [0.0, 1.0]. Higher = more severe.
pub const PROCESS_MINING_BOTTLENECK_SCORE: &str = "process.mining.bottleneck.score";

/// Average waiting time in milliseconds at the identified bottleneck activity.
pub const PROCESS_MINING_BOTTLENECK_WAIT_MS: &str = "process.mining.bottleneck.wait_ms";

/// Total throughput time for a case in milliseconds from first to last event.
pub const PROCESS_MINING_CASE_THROUGHPUT_MS: &str = "process.mining.case.throughput_ms";

/// Identifier for the process variant (unique execution path) of this case.
pub const PROCESS_MINING_CASE_VARIANT_ID: &str = "process.mining.case.variant_id";

/// Number of process cases (traces) in the event log being analyzed.
pub const PROCESS_MINING_CASE_COUNT: &str = "process.mining.case_count";

/// Identifier of the process case (instance) in the event log.
pub const PROCESS_MINING_CASE_ID: &str = "process.mining.case_id";

/// Algorithm used to cluster process mining cases.
pub const PROCESS_MINING_CLUSTER_ALGORITHM: &str = "process.mining.cluster.algorithm";

/// Values for [`PROCESS_MINING_CLUSTER_ALGORITHM`].
pub mod process_mining_cluster_algorithm {
    /// kmeans
    pub const KMEANS: &str = "kmeans";
    /// dbscan
    pub const DBSCAN: &str = "dbscan";
    /// hierarchical
    pub const HIERARCHICAL: &str = "hierarchical";
    /// spectral
    pub const SPECTRAL: &str = "spectral";
}

/// Number of cases assigned to this cluster.
pub const PROCESS_MINING_CLUSTER_CASE_COUNT: &str = "process.mining.cluster.case_count";

/// Identifier for the case cluster produced by the clustering algorithm.
pub const PROCESS_MINING_CLUSTER_ID: &str = "process.mining.cluster.id";

/// Silhouette score measuring cluster quality, range [-1.0, 1.0].
pub const PROCESS_MINING_CLUSTER_SILHOUETTE_SCORE: &str = "process.mining.cluster.silhouette_score";

/// The complexity metric applied to the process model.
pub const PROCESS_MINING_COMPLEXITY_METRIC: &str = "process.mining.complexity.metric";

/// Values for [`PROCESS_MINING_COMPLEXITY_METRIC`].
pub mod process_mining_complexity_metric {
    /// cyclomatic
    pub const CYCLOMATIC: &str = "cyclomatic";
    /// cognitive
    pub const COGNITIVE: &str = "cognitive";
    /// structural
    pub const STRUCTURAL: &str = "structural";
}

/// Complexity score of the discovered process model.
pub const PROCESS_MINING_COMPLEXITY_SCORE: &str = "process.mining.complexity.score";

/// Number of distinct process variants contributing to complexity.
pub const PROCESS_MINING_COMPLEXITY_VARIANT_COUNT: &str = "process.mining.complexity.variant_count";

/// Minimum conformance threshold per case — cases below this are flagged as violations.
pub const PROCESS_MINING_CONFORMANCE_CASE_THRESHOLD: &str =
    "process.mining.conformance.case_threshold";

/// Number of deviating traces in the conformance checking result.
pub const PROCESS_MINING_CONFORMANCE_DEVIATION_COUNT: &str =
    "process.mining.conformance.deviation_count";

/// Type of conformance deviation detected during trace alignment.
pub const PROCESS_MINING_CONFORMANCE_DEVIATION_TYPE: &str =
    "process.mining.conformance.deviation_type";

/// Values for [`PROCESS_MINING_CONFORMANCE_DEVIATION_TYPE`].
pub mod process_mining_conformance_deviation_type {
    /// Expected activity not found in trace
    pub const MISSING_ACTIVITY: &str = "missing_activity";
    /// Unexpected activity found in trace
    pub const EXTRA_ACTIVITY: &str = "extra_activity";
    /// Activities in wrong execution order
    pub const WRONG_ORDER: &str = "wrong_order";
    /// Loop constraints violated
    pub const LOOP_VIOLATION: &str = "loop_violation";
}

/// Computation time for the repair operation in milliseconds.
pub const PROCESS_MINING_CONFORMANCE_REPAIR_COST_MS: &str =
    "process.mining.conformance.repair_cost_ms";

/// Number of repair operations applied to achieve conformance.
pub const PROCESS_MINING_CONFORMANCE_REPAIR_COUNT: &str = "process.mining.conformance.repair_count";

/// Number of repair moves needed to align non-conforming traces.
pub const PROCESS_MINING_CONFORMANCE_REPAIR_STEPS: &str = "process.mining.conformance.repair_steps";

/// Type of conformance repair operation applied to the trace.
pub const PROCESS_MINING_CONFORMANCE_REPAIR_TYPE: &str = "process.mining.conformance.repair_type";

/// Values for [`PROCESS_MINING_CONFORMANCE_REPAIR_TYPE`].
pub mod process_mining_conformance_repair_type {
    /// insert
    pub const INSERT: &str = "insert";
    /// delete
    pub const DELETE: &str = "delete";
    /// move
    pub const MOVE: &str = "move";
    /// replace
    pub const REPLACE: &str = "replace";
}

/// Fitness score after repair operations, range [0.0, 1.0].
pub const PROCESS_MINING_CONFORMANCE_REPAIRED_FITNESS: &str =
    "process.mining.conformance.repaired_fitness";

/// Overall conformance fitness score measuring how well event traces follow the process model. Range [0.0, 1.0].
pub const PROCESS_MINING_CONFORMANCE_SCORE: &str = "process.mining.conformance.score";

/// Number of cases violating the conformance threshold.
pub const PROCESS_MINING_CONFORMANCE_VIOLATION_COUNT: &str =
    "process.mining.conformance.violation_count";

/// The visualization technique used for conformance checking results.
pub const PROCESS_MINING_CONFORMANCE_VISUALIZATION_TYPE: &str =
    "process.mining.conformance.visualization_type";

/// Values for [`PROCESS_MINING_CONFORMANCE_VISUALIZATION_TYPE`].
pub mod process_mining_conformance_visualization_type {
    /// token_replay
    pub const TOKEN_REPLAY: &str = "token_replay";
    /// alignment
    pub const ALIGNMENT: &str = "alignment";
    /// footprint
    pub const FOOTPRINT: &str = "footprint";
    /// anti_alignment
    pub const ANTI_ALIGNMENT: &str = "anti_alignment";
}

/// Confidence score for the decision outcome prediction [0.0, 1.0].
pub const PROCESS_MINING_DECISION_CONFIDENCE: &str = "process.mining.decision.confidence";

/// The outcome chosen at the decision point.
pub const PROCESS_MINING_DECISION_OUTCOME: &str = "process.mining.decision.outcome";

/// Identifier of the decision point in the process model.
pub const PROCESS_MINING_DECISION_POINT_ID: &str = "process.mining.decision.point_id";

/// Number of decision rules evaluated at the decision point.
pub const PROCESS_MINING_DECISION_RULE_COUNT: &str = "process.mining.decision.rule_count";

/// Type of conformance deviation found during trace alignment.
pub const PROCESS_MINING_DEVIATION_TYPE: &str = "process.mining.deviation.type";

/// Values for [`PROCESS_MINING_DEVIATION_TYPE`].
pub mod process_mining_deviation_type {
    /// skip
    pub const SKIP: &str = "skip";
    /// insert
    pub const INSERT: &str = "insert";
    /// move_model
    pub const MOVE_MODEL: &str = "move_model";
    /// move_log
    pub const MOVE_LOG: &str = "move_log";
}

/// Number of edges in the Directly-Follows Graph.
pub const PROCESS_MINING_DFG_EDGE_COUNT: &str = "process.mining.dfg.edge_count";

/// Number of nodes (activities) in the Directly-Follows Graph.
pub const PROCESS_MINING_DFG_NODE_COUNT: &str = "process.mining.dfg.node_count";

/// The magnitude of drift correction applied (change in fitness/conformance score).
pub const PROCESS_MINING_DRIFT_CORRECTION_DELTA: &str = "process.mining.drift.correction.delta";

/// Time taken (ms) to apply the drift correction.
pub const PROCESS_MINING_DRIFT_CORRECTION_DURATION_MS: &str =
    "process.mining.drift.correction.duration_ms";

/// The type of correction applied to address the detected process drift.
pub const PROCESS_MINING_DRIFT_CORRECTION_TYPE: &str = "process.mining.drift.correction_type";

/// Values for [`PROCESS_MINING_DRIFT_CORRECTION_TYPE`].
pub mod process_mining_drift_correction_type {
    /// retrain
    pub const RETRAIN: &str = "retrain";
    /// threshold_adjust
    pub const THRESHOLD_ADJUST: &str = "threshold_adjust";
    /// model_swap
    pub const MODEL_SWAP: &str = "model_swap";
    /// incremental_update
    pub const INCREMENTAL_UPDATE: &str = "incremental_update";
}

/// Whether concept drift was detected in the current event window.
pub const PROCESS_MINING_DRIFT_DETECTED: &str = "process.mining.drift.detected";

/// Severity classification of the detected concept drift.
pub const PROCESS_MINING_DRIFT_SEVERITY: &str = "process.mining.drift.severity";

/// Values for [`PROCESS_MINING_DRIFT_SEVERITY`].
pub mod process_mining_drift_severity {
    /// none
    pub const NONE: &str = "none";
    /// gradual
    pub const GRADUAL: &str = "gradual";
    /// sudden
    pub const SUDDEN: &str = "sudden";
    /// incremental
    pub const INCREMENTAL: &str = "incremental";
}

/// Identifier of the base process model being enhanced.
pub const PROCESS_MINING_ENHANCEMENT_BASE_MODEL_ID: &str =
    "process.mining.enhancement.base_model_id";

/// Percentage of cases covered by the enhanced model, range [0.0, 100.0].
pub const PROCESS_MINING_ENHANCEMENT_COVERAGE_PCT: &str = "process.mining.enhancement.coverage_pct";

/// Duration in milliseconds of the model enhancement operation.
pub const PROCESS_MINING_ENHANCEMENT_DURATION_MS: &str = "process.mining.enhancement.duration_ms";

/// Relative improvement rate achieved by the enhancement, range [0.0, 1.0].
pub const PROCESS_MINING_ENHANCEMENT_IMPROVEMENT_RATE: &str =
    "process.mining.enhancement.improvement_rate";

/// Unique identifier of the base process model being enhanced.
pub const PROCESS_MINING_ENHANCEMENT_MODEL_ID: &str = "process.mining.enhancement.model_id";

/// The perspective from which the process model is being enhanced.
pub const PROCESS_MINING_ENHANCEMENT_PERSPECTIVE: &str = "process.mining.enhancement.perspective";

/// Values for [`PROCESS_MINING_ENHANCEMENT_PERSPECTIVE`].
pub mod process_mining_enhancement_perspective {
    /// performance
    pub const PERFORMANCE: &str = "performance";
    /// conformance
    pub const CONFORMANCE: &str = "conformance";
    /// organizational
    pub const ORGANIZATIONAL: &str = "organizational";
    /// decision
    pub const DECISION: &str = "decision";
}

/// Quality score of the enhanced process model, range [0.0, 1.0].
pub const PROCESS_MINING_ENHANCEMENT_QUALITY_SCORE: &str =
    "process.mining.enhancement.quality_score";

/// Type of process model enhancement applied — augmenting a discovered model with additional perspectives.
pub const PROCESS_MINING_ENHANCEMENT_TYPE: &str = "process.mining.enhancement.type";

/// Values for [`PROCESS_MINING_ENHANCEMENT_TYPE`].
pub mod process_mining_enhancement_type {
    /// performance
    pub const PERFORMANCE: &str = "performance";
    /// conformance
    pub const CONFORMANCE: &str = "conformance";
    /// organizational
    pub const ORGANIZATIONAL: &str = "organizational";
    /// social_network
    pub const SOCIAL_NETWORK: &str = "social_network";
}

/// Number of raw events before abstraction.
pub const PROCESS_MINING_EVENT_ABSTRACTION_INPUT_COUNT: &str =
    "process.mining.event.abstraction_input_count";

/// Abstraction level of the process mining event.
pub const PROCESS_MINING_EVENT_ABSTRACTION_LEVEL: &str = "process.mining.event.abstraction_level";

/// Values for [`PROCESS_MINING_EVENT_ABSTRACTION_LEVEL`].
pub mod process_mining_event_abstraction_level {
    /// raw
    pub const RAW: &str = "raw";
    /// activity
    pub const ACTIVITY: &str = "activity";
    /// case
    pub const CASE: &str = "case";
    /// process
    pub const PROCESS: &str = "process";
}

/// Number of mapping rules applied during event abstraction.
pub const PROCESS_MINING_EVENT_ABSTRACTION_MAPPING_RULES: &str =
    "process.mining.event.abstraction_mapping_rules";

/// Number of abstracted events after abstraction.
pub const PROCESS_MINING_EVENT_ABSTRACTION_OUTPUT_COUNT: &str =
    "process.mining.event.abstraction_output_count";

/// Sequence number of this event within the trace (0-indexed).
pub const PROCESS_MINING_EVENT_SEQUENCE_NUMBER: &str = "process.mining.event.sequence_number";

/// Number of events in the process trace.
pub const PROCESS_MINING_EVENT_COUNT: &str = "process.mining.event_count";

/// Fitness score [0.0, 1.0] measuring how well a trace fits the process model.
pub const PROCESS_MINING_FITNESS: &str = "process.mining.fitness";

/// Minimum fitness score threshold for conformance acceptance [0.0, 1.0].
pub const PROCESS_MINING_FITNESS_THRESHOLD: &str = "process.mining.fitness_threshold";

/// Number of child processes under this node in the hierarchy.
pub const PROCESS_MINING_HIERARCHY_CHILD_COUNT: &str = "process.mining.hierarchy.child_count";

/// Depth of the process in the process hierarchy tree.
pub const PROCESS_MINING_HIERARCHY_DEPTH: &str = "process.mining.hierarchy.depth";

/// Identifier of the parent process in the hierarchy.
pub const PROCESS_MINING_HIERARCHY_PARENT_PROCESS_ID: &str =
    "process.mining.hierarchy.parent_process_id";

/// Number of cuts made during inductive mining.
pub const PROCESS_MINING_INDUCTIVE_CUT_COUNT: &str = "process.mining.inductive.cut_count";

/// Type of split in inductive miner tree.
pub const PROCESS_MINING_INDUCTIVE_SPLIT_TYPE: &str = "process.mining.inductive.split_type";

/// Values for [`PROCESS_MINING_INDUCTIVE_SPLIT_TYPE`].
pub mod process_mining_inductive_split_type {
    /// exclusive
    pub const EXCLUSIVE: &str = "exclusive";
    /// parallel
    pub const PARALLEL: &str = "parallel";
    /// loop
    pub const LOOP: &str = "loop";
    /// sequence
    pub const SEQUENCE: &str = "sequence";
}

/// Maximum depth of inductive miner tree.
pub const PROCESS_MINING_INDUCTIVE_TREE_DEPTH: &str = "process.mining.inductive.tree_depth";

/// Unique identifier of the event log being processed.
pub const PROCESS_MINING_LOG_ID: &str = "process.mining.log.id";

/// Number of event log entries (events) processed in this mining operation.
pub const PROCESS_MINING_LOG_SIZE: &str = "process.mining.log.size";

/// ISO 8601 timestamp of the earliest event in the event log.
pub const PROCESS_MINING_LOG_START_TIMESTAMP: &str = "process.mining.log.start_timestamp";

/// File path or identifier of the XES event log being mined.
pub const PROCESS_MINING_LOG_PATH: &str = "process.mining.log_path";

/// The type of process model used for conformance checking.
pub const PROCESS_MINING_MODEL_TYPE: &str = "process.mining.model.type";

/// Values for [`PROCESS_MINING_MODEL_TYPE`].
pub mod process_mining_model_type {
    /// petri_net
    pub const PETRI_NET: &str = "petri_net";
    /// bpmn
    pub const BPMN: &str = "bpmn";
    /// dfg
    pub const DFG: &str = "dfg";
    /// declare
    pub const DECLARE: &str = "declare";
}

/// Number of places in the discovered Petri net model.
pub const PROCESS_MINING_PETRI_NET_PLACE_COUNT: &str = "process.mining.petri_net.place_count";

/// Number of transitions in the discovered Petri net model.
pub const PROCESS_MINING_PETRI_NET_TRANSITION_COUNT: &str =
    "process.mining.petri_net.transition_count";

/// Confidence score of the process outcome prediction, range [0.0, 1.0].
pub const PROCESS_MINING_PREDICTION_CONFIDENCE: &str = "process.mining.prediction.confidence";

/// Time horizon (ms) for which the process outcome prediction is made.
pub const PROCESS_MINING_PREDICTION_HORIZON_MS: &str = "process.mining.prediction.horizon_ms";

/// The type of predictive model used (e.g., lstm, xgboost, conformance_replay).
pub const PROCESS_MINING_PREDICTION_MODEL_TYPE: &str = "process.mining.prediction.model_type";

/// Fitness score of the baseline model [0.0, 1.0].
pub const PROCESS_MINING_REPLAY_COMPARISON_BASELINE_FITNESS: &str =
    "process.mining.replay.comparison.baseline_fitness";

/// Difference (target - baseline) in fitness scores.
pub const PROCESS_MINING_REPLAY_COMPARISON_DELTA: &str = "process.mining.replay.comparison.delta";

/// Fitness score of the target model [0.0, 1.0].
pub const PROCESS_MINING_REPLAY_COMPARISON_TARGET_FITNESS: &str =
    "process.mining.replay.comparison.target_fitness";

/// Unique identifier for the replay comparison run.
pub const PROCESS_MINING_REPLAY_COMPARISON_ID: &str = "process.mining.replay.comparison_id";

/// Number of tokens consumed during the complete token replay.
pub const PROCESS_MINING_REPLAY_CONSUMED_TOKENS: &str = "process.mining.replay.consumed_tokens";

/// Number of transitions enabled (fireable) during token replay.
pub const PROCESS_MINING_REPLAY_ENABLED_TRANSITIONS: &str =
    "process.mining.replay.enabled_transitions";

/// Replay fitness score [0.0, 1.0] measuring how well the log fits the discovered model via token replay.
pub const PROCESS_MINING_REPLAY_FITNESS: &str = "process.mining.replay.fitness";

/// Generalization score — measures how well the model generalizes beyond observed traces [0.0, 1.0].
pub const PROCESS_MINING_REPLAY_GENERALIZATION: &str = "process.mining.replay.generalization";

/// Number of missing tokens encountered during token replay conformance checking.
pub const PROCESS_MINING_REPLAY_MISSING_TOKENS: &str = "process.mining.replay.missing_tokens";

/// Precision score of replay conformance check — measures how much of the model behaviour is in the log [0.0, 1.0].
pub const PROCESS_MINING_REPLAY_PRECISION: &str = "process.mining.replay.precision";

/// Simplicity score — measures the structural simplicity of the discovered model [0.0, 1.0].
pub const PROCESS_MINING_REPLAY_SIMPLICITY: &str = "process.mining.replay.simplicity";

/// Number of tokens produced and consumed during token replay conformance checking.
pub const PROCESS_MINING_REPLAY_TOKEN_COUNT: &str = "process.mining.replay.token_count";

/// Confidence score for the root cause classification [0.0, 1.0].
pub const PROCESS_MINING_ROOT_CAUSE_CONFIDENCE: &str = "process.mining.root_cause.confidence";

/// Identifier of the root cause detected in the process anomaly.
pub const PROCESS_MINING_ROOT_CAUSE_ID: &str = "process.mining.root_cause.id";

/// Type classification of the detected root cause.
pub const PROCESS_MINING_ROOT_CAUSE_TYPE: &str = "process.mining.root_cause.type";

/// Values for [`PROCESS_MINING_ROOT_CAUSE_TYPE`].
pub mod process_mining_root_cause_type {
    /// data_quality
    pub const DATA_QUALITY: &str = "data_quality";
    /// model_drift
    pub const MODEL_DRIFT: &str = "model_drift";
    /// process_change
    pub const PROCESS_CHANGE: &str = "process_change";
    /// resource_bottleneck
    pub const RESOURCE_BOTTLENECK: &str = "resource_bottleneck";
    /// compliance_violation
    pub const COMPLIANCE_VIOLATION: &str = "compliance_violation";
}

/// Number of process cases (traces) generated in the simulation run.
pub const PROCESS_MINING_SIMULATION_CASES: &str = "process.mining.simulation.cases";

/// Duration of the simulation run in milliseconds.
pub const PROCESS_MINING_SIMULATION_DURATION_MS: &str = "process.mining.simulation.duration_ms";

/// Fraction of simulated traces that include random noise/deviations, range [0.0, 1.0].
pub const PROCESS_MINING_SIMULATION_NOISE_RATE: &str = "process.mining.simulation.noise_rate";

/// Maximum betweenness centrality score across all nodes in the social network.
pub const PROCESS_MINING_SOCIAL_NETWORK_CENTRALITY_MAX: &str =
    "process.mining.social_network.centrality_max";

/// Density of the social network graph derived from the process log, range [0.0, 1.0].
pub const PROCESS_MINING_SOCIAL_NETWORK_DENSITY: &str = "process.mining.social_network.density";

/// Number of handover-of-work edges in the social network.
pub const PROCESS_MINING_SOCIAL_NETWORK_HANDOVER_COUNT: &str =
    "process.mining.social_network.handover_count";

/// Number of nodes (resources/roles) in the social network.
pub const PROCESS_MINING_SOCIAL_NETWORK_NODE_COUNT: &str =
    "process.mining.social_network.node_count";

/// Current throughput rate of the streaming process mining engine.
pub const PROCESS_MINING_STREAMING_EVENTS_PER_SECOND: &str =
    "process.mining.streaming.events_per_second";

/// Current lag in milliseconds between event stream and mining output.
pub const PROCESS_MINING_STREAMING_LAG_MS: &str = "process.mining.streaming.lag_ms";

/// Sliding window size in number of events for streaming process mining.
pub const PROCESS_MINING_STREAMING_WINDOW_SIZE: &str = "process.mining.streaming.window_size";

/// Temporal drift detected in the process — deviation from expected timing baseline in milliseconds.
pub const PROCESS_MINING_TEMPORAL_DRIFT_MS: &str = "process.mining.temporal.drift_ms";

/// Detected seasonality period in the process temporal pattern in milliseconds.
pub const PROCESS_MINING_TEMPORAL_SEASONALITY_PERIOD_MS: &str =
    "process.mining.temporal.seasonality_period_ms";

/// Slope of the temporal trend in the process — positive = accelerating, negative = decelerating.
pub const PROCESS_MINING_TEMPORAL_TREND_SLOPE: &str = "process.mining.temporal.trend_slope";

/// Average throughput time (start to completion) across all trace instances, in milliseconds.
pub const PROCESS_MINING_THROUGHPUT_TIME_MS: &str = "process.mining.throughput_time_ms";

/// Identifier of the process trace from the XES event log.
pub const PROCESS_MINING_TRACE_ID: &str = "process.mining.trace_id";

/// Deviation score from the reference model for this variant, range [0.0, 1.0]. Higher = more deviant.
pub const PROCESS_MINING_VARIANT_DEVIATION_SCORE: &str = "process.mining.variant.deviation_score";

/// Relative frequency of this variant in the event log, range [0.0, 1.0].
pub const PROCESS_MINING_VARIANT_FREQUENCY: &str = "process.mining.variant.frequency";

/// Unique identifier for a process variant (distinct execution trace pattern).
pub const PROCESS_MINING_VARIANT_ID: &str = "process.mining.variant.id";

/// Whether this variant represents the optimal (most efficient) process path.
pub const PROCESS_MINING_VARIANT_IS_OPTIMAL: &str = "process.mining.variant.is_optimal";

/// Number of unique trace variants in the event log.
pub const PROCESS_MINING_VARIANT_COUNT: &str = "process.mining.variant_count";
