// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/rdf/registry.yaml

/// Rdf Attributes
/// Number of RDF triples produced by a CONSTRUCT query result.
pub const RDF_RESULT_TRIPLE_COUNT: &str = "rdf.result.triple_count";

/// Base URL of the SPARQL/Oxigraph endpoint receiving the operation.
pub const RDF_SPARQL_ENDPOINT: &str = "rdf.sparql.endpoint";

/// Type of SPARQL query or update operation being executed.
pub const RDF_SPARQL_QUERY_TYPE: &str = "rdf.sparql.query_type";

/// Values for [`RDF_SPARQL_QUERY_TYPE`].
pub mod rdf_sparql_query_type {
    /// SELECT
    pub const SELECT: &str = "SELECT";
    /// CONSTRUCT
    pub const CONSTRUCT: &str = "CONSTRUCT";
    /// ASK
    pub const ASK: &str = "ASK";
    /// DESCRIBE
    pub const DESCRIBE: &str = "DESCRIBE";
    /// INSERT
    pub const INSERT: &str = "INSERT";
}

/// Number of result rows returned by a SPARQL SELECT or ASK query.
pub const RDF_SPARQL_RESULT_COUNT: &str = "rdf.sparql.result_count";

/// Timeout in milliseconds applied to the SPARQL query or update.
pub const RDF_SPARQL_TIMEOUT_MS: &str = "rdf.sparql.timeout_ms";

/// MIME type of the RDF serialization format used for write operations.
pub const RDF_WRITE_FORMAT: &str = "rdf.write.format";

/// Values for [`RDF_WRITE_FORMAT`].
pub mod rdf_write_format {
    /// text/turtle
    pub const TURTLE: &str = "text/turtle";
    /// application/n-triples
    pub const NTRIPLES: &str = "application/n-triples";
    /// application/ld+json
    pub const JSONLD: &str = "application/ld+json";
}

/// Number of RDF triples written in the store operation.
pub const RDF_WRITE_TRIPLE_COUNT: &str = "rdf.write.triple_count";
