// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/service/registry.yaml

/// Service Attributes
/// Name of the service.
pub const SERVICE_NAME: &str = "service.name";

/// Namespace of the service.
pub const SERVICE_NAMESPACE: &str = "service.namespace";

/// Version of the service.
pub const SERVICE_VERSION: &str = "service.version";
