// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/signal/registry.yaml

/// Signal Attributes
/// Effective information bandwidth as fraction of total tokens [0.0, 1.0].
pub const SIGNAL_BANDWIDTH: &str = "signal.bandwidth";

/// Number of signals dropped during batch aggregation due to capacity limits.
pub const SIGNAL_BATCH_DROP_COUNT: &str = "signal.batch.drop_count";

/// Number of signals in the batch aggregate.
pub const SIGNAL_BATCH_SIZE: &str = "signal.batch.size";

/// Time window in milliseconds over which signals are batched.
pub const SIGNAL_BATCH_WINDOW_MS: &str = "signal.batch.window_ms";

/// The identifier of the channel this signal is transmitted through.
pub const SIGNAL_CHANNEL_ID: &str = "signal.channel.id";

/// The classifier module or model that analyzed and scored the signal.
pub const SIGNAL_CLASSIFIER: &str = "signal.classifier";

/// Compression ratio applied to the signal [0.0, 1.0]. 1.0 = no compression.
pub const SIGNAL_COMPRESSION_RATIO: &str = "signal.compression.ratio";

/// Wire encoding format used to serialize the signal payload.
pub const SIGNAL_ENCODING: &str = "signal.encoding";

/// Values for [`SIGNAL_ENCODING`].
pub mod signal_encoding {
    /// json
    pub const JSON: &str = "json";
    /// protobuf
    pub const PROTOBUF: &str = "protobuf";
    /// msgpack
    pub const MSGPACK: &str = "msgpack";
    /// plain
    pub const PLAIN: &str = "plain";
}

/// The format component (F) of the signal — the container or serialization format.
pub const SIGNAL_FORMAT: &str = "signal.format";

/// Values for [`SIGNAL_FORMAT`].
pub mod signal_format {
    /// Markdown formatted text
    pub const MARKDOWN: &str = "markdown";
    /// Raw source code
    pub const CODE: &str = "code";
    /// JSON structured data
    pub const JSON: &str = "json";
    /// YAML structured data
    pub const YAML: &str = "yaml";
    /// HTML document
    pub const HTML: &str = "html";
    /// Plain text
    pub const TEXT: &str = "text";
    /// Tabular data
    pub const TABLE: &str = "table";
    /// Visual diagram description
    pub const DIAGRAM: &str = "diagram";
}

/// The genre component (G) of the signal — the document or interaction type.
pub const SIGNAL_GENRE: &str = "signal.genre";

/// Values for [`SIGNAL_GENRE`].
pub mod signal_genre {
    /// Technical specification document
    pub const SPEC: &str = "spec";
    /// Short summary or briefing
    pub const BRIEF: &str = "brief";
    /// Analysis or status report
    pub const REPORT: &str = "report";
    /// Execution or project plan
    pub const PLAN: &str = "plan";
    /// Architecture Decision Record
    pub const ADR: &str = "adr";
    /// Email or message communication
    pub const EMAIL: &str = "email";
    /// Code review feedback
    pub const CODE_REVIEW: &str = "code_review";
    /// Sales pitch or proposal presentation
    pub const PITCH: &str = "pitch";
    /// Formal decision record or ruling
    pub const DECISION: &str = "decision";
    /// Deep-dive analysis or investigation
    pub const ANALYSIS: &str = "analysis";
}

/// Number of routing hops the signal traversed before reaching the final destination.
pub const SIGNAL_HOP_COUNT: &str = "signal.hop_count";

/// Signal propagation latency in milliseconds from generation to delivery.
pub const SIGNAL_LATENCY_MS: &str = "signal.latency_ms";

/// The mode component (M) of the signal — how information is encoded.
pub const SIGNAL_MODE: &str = "signal.mode";

/// Values for [`SIGNAL_MODE`].
pub mod signal_mode {
    /// Natural language text output
    pub const LINGUISTIC: &str = "linguistic";
    /// Visual or diagrammatic output
    pub const VISUAL: &str = "visual";
    /// Source code or executable artifact
    pub const CODE: &str = "code";
    /// Structured data payload (JSON, YAML, CSV)
    pub const DATA: &str = "data";
    /// Combination of multiple modes
    pub const MIXED: &str = "mixed";
    /// High-level reasoning output
    pub const COGNITIVE: &str = "cognitive";
    /// System operation signal
    pub const OPERATIONAL: &str = "operational";
    /// Response to stimulus
    pub const REACTIVE: &str = "reactive";
}

/// Noise level of the signal in range [0.0, 1.0]. Complement of signal weight for clean signals.
pub const SIGNAL_NOISE_LEVEL: &str = "signal.noise_level";

/// Priority level of the signal for queue ordering and routing decisions.
pub const SIGNAL_PRIORITY: &str = "signal.priority";

/// Values for [`SIGNAL_PRIORITY`].
pub mod signal_priority {
    /// critical
    pub const CRITICAL: &str = "critical";
    /// high
    pub const HIGH: &str = "high";
    /// normal
    pub const NORMAL: &str = "normal";
    /// low
    pub const LOW: &str = "low";
}

/// Whether signal quality has degraded below acceptable threshold.
pub const SIGNAL_QUALITY_DEGRADED: &str = "signal.quality.degraded";

/// Composite quality score for the signal, range [0.0, 1.0]. Combines S/N ratio, bandwidth, and latency metrics.
pub const SIGNAL_QUALITY_SCORE: &str = "signal.quality.score";

/// The configured S/N quality threshold below which signals are rejected. Default is 0.7.
pub const SIGNAL_QUALITY_THRESHOLD: &str = "signal.quality.threshold";

/// Number of retransmission retries attempted for this signal.
pub const SIGNAL_RETRY_COUNT: &str = "signal.retry.count";

/// Shannon signal-to-noise ratio score in range [0.0, 1.0]. Values >= 0.7 pass the S/N gate for transmission.
pub const SIGNAL_SN_RATIO: &str = "signal.sn_ratio";

/// The source channel through which the signal was received.
pub const SIGNAL_SOURCE: &str = "signal.source";

/// Time-to-live for the signal in milliseconds — signal expires if not consumed.
pub const SIGNAL_TTL_MS: &str = "signal.ttl_ms";

/// The type component (T) of the signal — the speech act or communicative intent.
pub const SIGNAL_TYPE: &str = "signal.type";

/// Values for [`SIGNAL_TYPE`].
pub mod signal_type {
    /// Direct instruction or command
    pub const DIRECT: &str = "direct";
    /// Information transfer without action required
    pub const INFORM: &str = "inform";
    /// Commitment or promise of future action
    pub const COMMIT: &str = "commit";
    /// Decision that changes system state
    pub const DECIDE: &str = "decide";
    /// Expressive or emotive content
    pub const EXPRESS: &str = "express";
}

/// Signal weight (W) — signal-to-noise ratio in range [0.0, 1.0]. Values >= 0.7 pass the S/N gate.
pub const SIGNAL_WEIGHT: &str = "signal.weight";
