// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/telemetry/registry.yaml

/// Telemetry Attributes
/// Programming language of OpenTelemetry SDK.
pub const TELEMETRY_SDK_LANGUAGE: &str = "telemetry.sdk.language";

/// OpenTelemetry SDK name.
pub const TELEMETRY_SDK_NAME: &str = "telemetry.sdk.name";

/// Version of OpenTelemetry SDK.
pub const TELEMETRY_SDK_VERSION: &str = "telemetry.sdk.version";
