// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/workflow/registry.yaml

/// Workflow Attributes
/// Number of branches currently active in a multi-choice split.
pub const WORKFLOW_ACTIVE_BRANCHES: &str = "workflow.active_branches";

/// Number of active branches in a parallel split or join pattern.
pub const WORKFLOW_BRANCH_COUNT: &str = "workflow.branch_count";

/// Reason for cancellation of the workflow activity or region.
pub const WORKFLOW_CANCEL_REASON: &str = "workflow.cancel.reason";

/// The evaluated condition expression used to select an XOR branch.
pub const WORKFLOW_CHOICE_CONDITION: &str = "workflow.choice.condition";

/// Workflow engine executing the workflow.
pub const WORKFLOW_ENGINE: &str = "workflow.engine";

/// Values for [`WORKFLOW_ENGINE`].
pub mod workflow_engine {
    /// canopy
    pub const CANOPY: &str = "canopy";
    /// yawl
    pub const YAWL: &str = "yawl";
    /// business_os
    pub const BUSINESS_OS: &str = "business_os";
}

/// Number of branches that have fired/triggered so far.
pub const WORKFLOW_FIRED_BRANCHES: &str = "workflow.fired_branches";

/// Unique identifier for the workflow instance.
pub const WORKFLOW_ID: &str = "workflow.id";

/// Number of completed instances out of total in multi-instance activity.
pub const WORKFLOW_INSTANCE_COMPLETED: &str = "workflow.instance.completed";

/// Number of active instances in a multi-instance activity pattern.
pub const WORKFLOW_INSTANCE_COUNT: &str = "workflow.instance.count";

/// Current iteration count of a structured loop activity.
pub const WORKFLOW_LOOP_ITERATION: &str = "workflow.loop.iteration";

/// Maximum allowed iterations for a structured loop (boundedness guarantee).
pub const WORKFLOW_LOOP_MAX_ITERATIONS: &str = "workflow.loop.max_iterations";

/// Policy for merging concurrent branches at a join point.
pub const WORKFLOW_MERGE_POLICY: &str = "workflow.merge.policy";

/// Values for [`WORKFLOW_MERGE_POLICY`].
pub mod workflow_merge_policy {
    /// first
    pub const FIRST: &str = "first";
    /// all
    pub const ALL: &str = "all";
    /// threshold
    pub const THRESHOLD: &str = "threshold";
}

/// Condition expression that gates milestone execution.
pub const WORKFLOW_MILESTONE_CONDITION: &str = "workflow.milestone.condition";

/// Human-readable name of the workflow definition.
pub const WORKFLOW_NAME: &str = "workflow.name";

/// YAWL workflow control-flow pattern applied in this step.
pub const WORKFLOW_PATTERN: &str = "workflow.pattern";

/// Values for [`WORKFLOW_PATTERN`].
pub mod workflow_pattern {
    /// sequence
    pub const SEQUENCE: &str = "sequence";
    /// parallel_split
    pub const PARALLEL_SPLIT: &str = "parallel_split";
    /// synchronization
    pub const SYNCHRONIZATION: &str = "synchronization";
    /// exclusive_choice
    pub const EXCLUSIVE_CHOICE: &str = "exclusive_choice";
    /// multi_choice
    pub const MULTI_CHOICE: &str = "multi_choice";
    /// structured_loop
    pub const STRUCTURED_LOOP: &str = "structured_loop";
    /// deferred_choice
    pub const DEFERRED_CHOICE: &str = "deferred_choice";
    /// milestone
    pub const MILESTONE: &str = "milestone";
    /// discriminator
    pub const DISCRIMINATOR: &str = "discriminator";
    /// n_out_of_m
    pub const N_OUT_OF_M: &str = "n_out_of_m";
    /// partial_join
    pub const PARTIAL_JOIN: &str = "partial_join";
    /// cancel_region
    pub const CANCEL_REGION: &str = "cancel_region";
    /// interleaved_parallel
    pub const INTERLEAVED_PARALLEL: &str = "interleaved_parallel";
    /// critical_section
    pub const CRITICAL_SECTION: &str = "critical_section";
    /// recursion
    pub const RECURSION: &str = "recursion";
    /// transient_trigger
    pub const TRANSIENT_TRIGGER: &str = "transient_trigger";
    /// persistent_trigger
    pub const PERSISTENT_TRIGGER: &str = "persistent_trigger";
    /// event_based_choice
    pub const EVENT_BASED_CHOICE: &str = "event_based_choice";
    /// cancel_activity
    pub const CANCEL_ACTIVITY: &str = "cancel_activity";
    /// multi_instance_sync
    pub const MULTI_INSTANCE_SYNC: &str = "multi_instance_sync";
    /// simple_merge
    pub const SIMPLE_MERGE: &str = "simple_merge";
    /// multiple_instance
    pub const MULTIPLE_INSTANCE: &str = "multiple_instance";
    /// structured_sync_merge
    pub const STRUCTURED_SYNC_MERGE: &str = "structured_sync_merge";
}

/// Number of branches required to complete before a N-out-of-M join activates.
pub const WORKFLOW_REQUIRED_BRANCHES: &str = "workflow.required_branches";

/// Number of concurrent branches created in a parallel split (WP-2).
pub const WORKFLOW_SPLIT_COUNT: &str = "workflow.split.count";

/// Execution state of the workflow instance.
pub const WORKFLOW_STATE: &str = "workflow.state";

/// Values for [`WORKFLOW_STATE`].
pub mod workflow_state {
    /// pending
    pub const PENDING: &str = "pending";
    /// active
    pub const ACTIVE: &str = "active";
    /// completed
    pub const COMPLETED: &str = "completed";
    /// failed
    pub const FAILED: &str = "failed";
    /// cancelled
    pub const CANCELLED: &str = "cancelled";
    /// suspended
    pub const SUSPENDED: &str = "suspended";
}

/// The current step or activity name within the workflow.
pub const WORKFLOW_STEP: &str = "workflow.step";

/// Total number of steps completed so far in the workflow.
pub const WORKFLOW_STEP_COUNT: &str = "workflow.step_count";

/// Timeout in milliseconds for synchronized merge to complete (Armstrong WvdA bounded).
pub const WORKFLOW_SYNC_TIMEOUT_MS: &str = "workflow.sync.timeout_ms";

/// Total number of branches in a parallel split pattern (M in N-out-of-M).
pub const WORKFLOW_TOTAL_BRANCHES: &str = "workflow.total_branches";

/// The type of trigger that initiated the workflow transition.
pub const WORKFLOW_TRIGGER_TYPE: &str = "workflow.trigger_type";

/// Values for [`WORKFLOW_TRIGGER_TYPE`].
pub mod workflow_trigger_type {
    /// timer
    pub const TIMER: &str = "timer";
    /// event
    pub const EVENT: &str = "event";
    /// signal
    pub const SIGNAL: &str = "signal";
    /// manual
    pub const MANUAL: &str = "manual";
    /// message
    pub const MESSAGE: &str = "message";
    /// external
    pub const EXTERNAL: &str = "external";
    /// condition
    pub const CONDITION: &str = "condition";
}
