// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/workspace/registry.yaml

/// Workspace Attributes
/// Total number of activities performed in the workspace session.
pub const WORKSPACE_ACTIVITY_COUNT: &str = "workspace.activity.count";

/// Duration of the workspace activity in milliseconds.
pub const WORKSPACE_ACTIVITY_DURATION_MS: &str = "workspace.activity.duration_ms";

/// Type of activity performed in the workspace.
pub const WORKSPACE_ACTIVITY_TYPE: &str = "workspace.activity.type";

/// Values for [`WORKSPACE_ACTIVITY_TYPE`].
pub mod workspace_activity_type {
    /// code_edit
    pub const CODE_EDIT: &str = "code_edit";
    /// file_read
    pub const FILE_READ: &str = "file_read";
    /// terminal_exec
    pub const TERMINAL_EXEC: &str = "terminal_exec";
    /// web_search
    pub const WEB_SEARCH: &str = "web_search";
    /// agent_spawn
    pub const AGENT_SPAWN: &str = "agent_spawn";
    /// tool_call
    pub const TOOL_CALL: &str = "tool_call";
    /// memory_update
    pub const MEMORY_UPDATE: &str = "memory_update";
}

/// Number of active agents in this workspace session.
pub const WORKSPACE_AGENT_COUNT: &str = "workspace.agent.count";

/// The role of the agent in this workspace session.
pub const WORKSPACE_AGENT_ROLE: &str = "workspace.agent.role";

/// Values for [`WORKSPACE_AGENT_ROLE`].
pub mod workspace_agent_role {
    /// planner
    pub const PLANNER: &str = "planner";
    /// executor
    pub const EXECUTOR: &str = "executor";
    /// reviewer
    pub const REVIEWER: &str = "reviewer";
    /// coordinator
    pub const COORDINATOR: &str = "coordinator";
    /// researcher
    pub const RESEARCHER: &str = "researcher";
}

/// Unique identifier of the workspace checkpoint or savepoint.
pub const WORKSPACE_CHECKPOINT_ID: &str = "workspace.checkpoint.id";

/// Compression ratio achieved when compressing context [0.0, 1.0].
pub const WORKSPACE_CONTEXT_COMPRESSION_RATIO: &str = "workspace.context.compression_ratio";

/// Current context window usage in tokens.
pub const WORKSPACE_CONTEXT_SIZE: &str = "workspace.context.size";

/// Size of the workspace context in tokens before compression.
pub const WORKSPACE_CONTEXT_SIZE_TOKENS: &str = "workspace.context.size_tokens";

/// Identifier of the workspace context snapshot.
pub const WORKSPACE_CONTEXT_SNAPSHOT_ID: &str = "workspace.context.snapshot_id";

/// Maximum context window size in tokens for this workspace session.
pub const WORKSPACE_CONTEXT_WINDOW_SIZE: &str = "workspace.context.window_size";

/// Number of orchestration iterations completed in this workspace session.
pub const WORKSPACE_ITERATION_COUNT: &str = "workspace.iteration.count";

/// Duration of the memory compaction operation in milliseconds.
pub const WORKSPACE_MEMORY_COMPACTION_MS: &str = "workspace.memory.compaction_ms";

/// Ratio of memory reduced by compaction, range (0.0, 1.0). Value of 0.4 means 40% reduction.
pub const WORKSPACE_MEMORY_COMPACTION_RATIO: &str = "workspace.memory.compaction_ratio";

/// Number of memory items after compaction.
pub const WORKSPACE_MEMORY_ITEMS_AFTER: &str = "workspace.memory.items_after";

/// Number of memory items before compaction.
pub const WORKSPACE_MEMORY_ITEMS_BEFORE: &str = "workspace.memory.items_before";

/// Current memory usage of the workspace context in bytes.
pub const WORKSPACE_MEMORY_USAGE_BYTES: &str = "workspace.memory.usage_bytes";

/// The orchestration pattern governing how agents coordinate work in this workspace.
pub const WORKSPACE_ORCHESTRATION_PATTERN: &str = "workspace.orchestration.pattern";

/// Values for [`WORKSPACE_ORCHESTRATION_PATTERN`].
pub mod workspace_orchestration_pattern {
    /// sequential
    pub const SEQUENTIAL: &str = "sequential";
    /// parallel
    pub const PARALLEL: &str = "parallel";
    /// reactive
    pub const REACTIVE: &str = "reactive";
    /// proactive
    pub const PROACTIVE: &str = "proactive";
    /// event_driven
    pub const EVENT_DRIVEN: &str = "event_driven";
}

/// Current lifecycle phase of the workspace session.
pub const WORKSPACE_PHASE: &str = "workspace.phase";

/// Values for [`WORKSPACE_PHASE`].
pub mod workspace_phase {
    /// startup
    pub const STARTUP: &str = "startup";
    /// active
    pub const ACTIVE: &str = "active";
    /// idle
    pub const IDLE: &str = "idle";
    /// shutdown
    pub const SHUTDOWN: &str = "shutdown";
}

/// Duration of the workspace session in milliseconds.
pub const WORKSPACE_SESSION_DURATION_MS: &str = "workspace.session.duration_ms";

/// Unique identifier for the workspace session.
pub const WORKSPACE_SESSION_ID: &str = "workspace.session.id";

/// Total tokens consumed across all LLM calls in the workspace session.
pub const WORKSPACE_SESSION_TOKEN_BUDGET_USED: &str = "workspace.session.token_budget_used";

/// Total number of tool calls made during the workspace session.
pub const WORKSPACE_SESSION_TOOL_CALL_COUNT: &str = "workspace.session.tool_call_count";

/// Number of agents that have access to the shared workspace.
pub const WORKSPACE_SHARING_AGENT_COUNT: &str = "workspace.sharing.agent_count";

/// Comma-separated list of permissions granted in the shared workspace (read,write,execute).
pub const WORKSPACE_SHARING_PERMISSIONS: &str = "workspace.sharing.permissions";

/// Scope of workspace sharing — who can access the shared workspace.
pub const WORKSPACE_SHARING_SCOPE: &str = "workspace.sharing.scope";

/// Values for [`WORKSPACE_SHARING_SCOPE`].
pub mod workspace_sharing_scope {
    /// private
    pub const PRIVATE: &str = "private";
    /// team
    pub const TEAM: &str = "team";
    /// org
    pub const ORG: &str = "org";
    /// public
    pub const PUBLIC: &str = "public";
}

/// Current depth of the workspace task queue — pending tasks awaiting dispatch.
pub const WORKSPACE_TASK_QUEUE_DEPTH: &str = "workspace.task.queue.depth";

/// Functional category of the workspace tool being invoked.
pub const WORKSPACE_TOOL_CATEGORY: &str = "workspace.tool.category";

/// Values for [`WORKSPACE_TOOL_CATEGORY`].
pub mod workspace_tool_category {
    /// read
    pub const READ: &str = "read";
    /// write
    pub const WRITE: &str = "write";
    /// search
    pub const SEARCH: &str = "search";
    /// compute
    pub const COMPUTE: &str = "compute";
    /// communicate
    pub const COMMUNICATE: &str = "communicate";
    /// transform
    pub const TRANSFORM: &str = "transform";
}

/// Total number of tool invocations in this workspace session.
pub const WORKSPACE_TOOL_COUNT: &str = "workspace.tool.count";

/// Name of the tool being invoked in the workspace.
pub const WORKSPACE_TOOL_NAME: &str = "workspace.tool.name";

/// Provider or source of the workspace tool (e.g., "built-in", "mcp", "plugin").
pub const WORKSPACE_TOOL_PROVIDER: &str = "workspace.tool.provider";
