// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/yawl/registry.yaml

/// Yawl Attributes
/// YAWL workflow case identifier — the root correlation key for a workflow instance.
pub const YAWL_CASE_ID: &str = "yawl.case.id";

/// YAWL workflow event type from the SSE event stream.
pub const YAWL_EVENT_TYPE: &str = "yawl.event.type";

/// Values for [`YAWL_EVENT_TYPE`].
pub mod yawl_event_type {
    /// New workflow case started.
    pub const INSTANCE_CREATED: &str = "INSTANCE_CREATED";
    /// Task enabled — input conditions have tokens (transition fireable).
    pub const TASK_ENABLED: &str = "TASK_ENABLED";
    /// Task started — input tokens consumed (transition fired).
    pub const TASK_STARTED: &str = "TASK_STARTED";
    /// Task completed — output tokens produced to successor conditions.
    pub const TASK_COMPLETED: &str = "TASK_COMPLETED";
    /// Task failed — tokens left in error condition.
    pub const TASK_FAILED: &str = "TASK_FAILED";
    /// Workflow case reached output condition (Petri net reached final marking).
    pub const INSTANCE_COMPLETED: &str = "INSTANCE_COMPLETED";
    /// Workflow case cancelled before completion.
    pub const INSTANCE_CANCELLED: &str = "INSTANCE_CANCELLED";
}

/// YAWL task identifier within a workflow net (matches task id in YAWL XML spec).
pub const YAWL_TASK_ID: &str = "yawl.task.id";

/// YAWL workflow instance identifier (internal engine identifier).
pub const YAWL_INSTANCE_ID: &str = "yawl.instance.id";

/// YAWL SSE event identifier from the event stream.
pub const YAWL_SPEC_EVENT_ID: &str = "yawl.spec.event_id";

/// YAWL specification URI — the workflow definition being executed.
pub const YAWL_SPEC_URI: &str = "yawl.spec.uri";

/// Number of tokens consumed from input conditions when this task fires.
pub const YAWL_TOKEN_CONSUMED: &str = "yawl.token.consumed";

/// Number of tokens produced to output conditions after this task fires.
pub const YAWL_TOKEN_PRODUCED: &str = "yawl.token.produced";

/// YAWL Workflow Control-flow Pattern identifier being exercised.
pub const YAWL_WCP_PATTERN: &str = "yawl.wcp_pattern";

/// YAWL work item unique identifier in caseID:taskID:uniqueID format.
pub const YAWL_WORK_ITEM_ID: &str = "yawl.work_item.id";
