// Auto-generated by OTel Weaver — DO NOT EDIT.
// Source: semconv/model/yawlv6/registry.yaml

/// Yawlv6 Attributes
/// Number of YAWLv6 modules with passing tests during checkpoint execution.
pub const YAWLV6_MODULES_COMPLETE: &str = "yawlv6.modules_complete";

/// Number of YAWLv6 tests that failed during checkpoint execution.
pub const YAWLV6_TESTS_FAILED: &str = "yawlv6.tests_failed";

/// Number of YAWLv6 tests that passed during checkpoint execution.
pub const YAWLV6_TESTS_PASSED: &str = "yawlv6.tests_passed";
